// Function: gimli::constants::DwForm::static_string::hff55cb7cf4b846d2
// RVA: 0x3455ec, Size: 852 bytes
int64_t _ZN5gimli9constants6DwForm13static_string17hff55cb7cf4b846d2E(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    const char* str = "DW_FORM_nullDwFormDW_ATE_hi_userDW_ATE_lo_userDW_ATE_ASCIIDW_ATE_UCSDW_ATE_UTFDW_ATE_decimal_floatDW_ATE_unsigned_fixedDW_ATE_si";
    const char* str = "DW_FORM_addrDW_FORM_nullDwFormDW_ATE_hi_userDW_ATE_lo_userDW_ATE_ASCIIDW_ATE_UCSDW_ATE_UTFDW_ATE_decimal_floatDW_ATE_unsigned_fi";
    const char* str = "DW_FORM_GNU_addr_indexDW_FORM_addrx4DW_FORM_addrx3DW_FORM_addrx2DW_FORM_addrx1DW_FORM_strx4DW_FORM_strx3DW_FORM_strx2DW_FORM_str";
    const char* str = "DW_FORM_block2DW_FORM_addrDW_FORM_nullDwFormDW_ATE_hi_userDW_ATE_lo_userDW_ATE_ASCIIDW_ATE_UCSDW_ATE_UTFDW_ATE_decimal_floatDW_A";
    const char* str = "DW_FORM_block4DW_FORM_block2DW_FORM_addrDW_FORM_nullDwFormDW_ATE_hi_userDW_ATE_lo_userDW_ATE_ASCIIDW_ATE_UCSDW_ATE_UTFDW_ATE_dec";
    const char* str = "DW_FORM_data2DW_FORM_block4DW_FORM_block2DW_FORM_addrDW_FORM_nullDwFormDW_ATE_hi_userDW_ATE_lo_userDW_ATE_ASCIIDW_ATE_UCSDW_ATE_";
    const char* str = "DW_FORM_data4DW_FORM_data2DW_FORM_block4DW_FORM_block2DW_FORM_addrDW_FORM_nullDwFormDW_ATE_hi_userDW_ATE_lo_userDW_ATE_ASCIIDW_A";
    const char* str = "DW_FORM_data8DW_FORM_data4DW_FORM_data2DW_FORM_block4DW_FORM_block2DW_FORM_addrDW_FORM_nullDwFormDW_ATE_hi_userDW_ATE_lo_userDW_";
    const char* str = "DW_FORM_stringDW_FORM_data8DW_FORM_data4DW_FORM_data2DW_FORM_block4DW_FORM_block2DW_FORM_addrDW_FORM_nullDwFormDW_ATE_hi_userDW_";
    const char* str = "DW_FORM_blockDW_FORM_stringDW_FORM_data8DW_FORM_data4DW_FORM_data2DW_FORM_block4DW_FORM_block2DW_FORM_addrDW_FORM_nullDwFormDW_A";
    const char* str = "DW_FORM_block1DW_FORM_blockDW_FORM_stringDW_FORM_data8DW_FORM_data4DW_FORM_data2DW_FORM_block4DW_FORM_block2DW_FORM_addrDW_FORM_";
    const char* str = "DW_FORM_data1DW_FORM_block1DW_FORM_blockDW_FORM_stringDW_FORM_data8DW_FORM_data4DW_FORM_data2DW_FORM_block4DW_FORM_block2DW_FORM";
    const char* str = "DW_FORM_flagDW_FORM_data1DW_FORM_block1DW_FORM_blockDW_FORM_stringDW_FORM_data8DW_FORM_data4DW_FORM_data2DW_FORM_block4DW_FORM_b";
    const char* str = "DW_FORM_sdataDW_FORM_flagDW_FORM_data1DW_FORM_block1DW_FORM_blockDW_FORM_stringDW_FORM_data8DW_FORM_data4DW_FORM_data2DW_FORM_bl";
    const char* str = "DW_FORM_strpDW_FORM_sdataDW_FORM_flagDW_FORM_data1DW_FORM_block1DW_FORM_blockDW_FORM_stringDW_FORM_data8DW_FORM_data4DW_FORM_dat";
    const char* str = "DW_FORM_udataDW_FORM_strpDW_FORM_sdataDW_FORM_flagDW_FORM_data1DW_FORM_block1DW_FORM_blockDW_FORM_stringDW_FORM_data8DW_FORM_dat";
    const char* str = "DW_FORM_ref1DW_FORM_udataDW_FORM_strpDW_FORM_sdataDW_FORM_flagDW_FORM_data1DW_FORM_block1DW_FORM_blockDW_FORM_stringDW_FORM_data";
    const char* str = "DW_FORM_ref2DW_FORM_ref1DW_FORM_udataDW_FORM_strpDW_FORM_sdataDW_FORM_flagDW_FORM_data1DW_FORM_block1DW_FORM_blockDW_FORM_string";
    const char* str = "DW_FORM_ref4DW_FORM_ref2DW_FORM_ref1DW_FORM_udataDW_FORM_strpDW_FORM_sdataDW_FORM_flagDW_FORM_data1DW_FORM_block1DW_FORM_blockDW";
    const char* str = "DW_FORM_ref8DW_FORM_ref4DW_FORM_ref2DW_FORM_ref1DW_FORM_udataDW_FORM_strpDW_FORM_sdataDW_FORM_flagDW_FORM_data1DW_FORM_block1DW_";
    const char* str = "DW_FORM_ref_udataDW_FORM_ref8DW_FORM_ref4DW_FORM_ref2DW_FORM_ref1DW_FORM_udataDW_FORM_strpDW_FORM_sdataDW_FORM_flagDW_FORM_data1";
    const char* str = "DW_FORM_sec_offsetDW_FORM_ref_udataDW_FORM_ref8DW_FORM_ref4DW_FORM_ref2DW_FORM_ref1DW_FORM_udataDW_FORM_strpDW_FORM_sdataDW_FORM";
    const char* str = "DW_FORM_exprlocDW_FORM_sec_offsetDW_FORM_ref_udataDW_FORM_ref8DW_FORM_ref4DW_FORM_ref2DW_FORM_ref1DW_FORM_udataDW_FORM_strpDW_FO";
    const char* str = "DW_FORM_flag_presentDW_FORM_exprlocDW_FORM_sec_offsetDW_FORM_ref_udataDW_FORM_ref8DW_FORM_ref4DW_FORM_ref2DW_FORM_ref1DW_FORM_ud";
    const char* str = "DW_FORM_strxDW_FORM_flag_presentDW_FORM_exprlocDW_FORM_sec_offsetDW_FORM_ref_udataDW_FORM_ref8DW_FORM_ref4DW_FORM_ref2DW_FORM_re";
    const char* str = "DW_FORM_addrxDW_FORM_strxDW_FORM_flag_presentDW_FORM_exprlocDW_FORM_sec_offsetDW_FORM_ref_udataDW_FORM_ref8DW_FORM_ref4DW_FORM_r";
    const char* str = "DW_FORM_strp_sup	";
    const char* str = "DW_FORM_data16DW_FORM_addrxDW_FORM_strxDW_FORM_flag_presentDW_FORM_exprlocDW_FORM_sec_offsetDW_FORM_ref_udataDW_FORM_ref8DW_FORM";
    const char* str = "DW_FORM_line_strpDW_FORM_data16DW_FORM_addrxDW_FORM_strxDW_FORM_flag_presentDW_FORM_exprlocDW_FORM_sec_offsetDW_FORM_ref_udataDW";
    const char* str = "DW_FORM_ref_sig8{invalid syntax}";
    const char* str = "DW_FORM_implicit_constDW_FORM_line_strpDW_FORM_data16DW_FORM_addrxDW_FORM_strxDW_FORM_flag_presentDW_FORM_exprlocDW_FORM_sec_off";
    const char* str = "DW_FORM_rnglistx";
    const char* str = "DW_FORM_ref_sup8DW_IDX_type_hash";
    const char* str = "DW_FORM_strx1DW_FORM_implicit_constDW_FORM_line_strpDW_FORM_data16DW_FORM_addrxDW_FORM_strxDW_FORM_flag_presentDW_FORM_exprlocDW";
    const char* str = "DW_FORM_strx2DW_FORM_strx1DW_FORM_implicit_constDW_FORM_line_strpDW_FORM_data16DW_FORM_addrxDW_FORM_strxDW_FORM_flag_presentDW_F";
    const char* str = "DW_FORM_strx3DW_FORM_strx2DW_FORM_strx1DW_FORM_implicit_constDW_FORM_line_strpDW_FORM_data16DW_FORM_addrxDW_FORM_strxDW_FORM_fla";
    const char* str = "DW_FORM_strx4DW_FORM_strx3DW_FORM_strx2DW_FORM_strx1DW_FORM_implicit_constDW_FORM_line_strpDW_FORM_data16DW_FORM_addrxDW_FORM_st";
    const char* str = "DW_FORM_addrx1DW_FORM_strx4DW_FORM_strx3DW_FORM_strx2DW_FORM_strx1DW_FORM_implicit_constDW_FORM_line_strpDW_FORM_data16DW_FORM_a";
    const char* str = "DW_FORM_addrx2DW_FORM_addrx1DW_FORM_strx4DW_FORM_strx3DW_FORM_strx2DW_FORM_strx1DW_FORM_implicit_constDW_FORM_line_strpDW_FORM_d";
    const char* str = "DW_FORM_addrx3DW_FORM_addrx2DW_FORM_addrx1DW_FORM_strx4DW_FORM_strx3DW_FORM_strx2DW_FORM_strx1DW_FORM_implicit_constDW_FORM_line";
    const char* str = "DW_FORM_addrx4DW_FORM_addrx3DW_FORM_addrx2DW_FORM_addrx1DW_FORM_strx4DW_FORM_strx3DW_FORM_strx2DW_FORM_strx1DW_FORM_implicit_con";
    const char* str = "DW_FORM_GNU_str_indexDW_FORM_GNU_addr_indexDW_FORM_addrx4DW_FORM_addrx3DW_FORM_addrx2DW_FORM_addrx1DW_FORM_strx4DW_FORM_strx3DW_";
    const char* str = "DW_FORM_GNU_ref_altDW_FORM_GNU_str_indexDW_FORM_GNU_addr_indexDW_FORM_addrx4DW_FORM_addrx3DW_FORM_addrx2DW_FORM_addrx1DW_FORM_st";
    const char* str = "DW_FORM_GNU_strp_altDW_FORM_GNU_ref_altDW_FORM_GNU_str_indexDW_FORM_GNU_addr_indexDW_FORM_addrx4DW_FORM_addrx3DW_FORM_addrx2DW_F";
    return a0;
    return a0;
}
