import csv
from pathlib import Path

out_csv = Path(".ai/reports/TASK_042_HAIR_V2_MODULAR_REFERENCE_INTAKE_BENCHMARK/01_V1_16_MODULE_FUNCTION_INVENTORY.csv")

rows = [
    {
        "module_file": "hair_v2_barrier.cpp",
        "header_file": "hair_v2_barrier.h",
        "function_name": "buildAnatomicalProtectionMask",
        "return_type": "HairV2Status",
        "parameter_signature": "const float* landmarks106, int numLandmarks, float yaw, float pitch, const FrameGeometry& geom, uint8_t* protectMask",
        "inputs": "landmarks106 (106x2 points), numLandmarks, yaw/pitch pose, FrameGeometry",
        "outputs": "protectMask (uint8_t WxH buffer; 255=forbidden skin/ear/face, 0=allowed)",
        "dependencies": "hair_v2_barrier.h, <cmath>, <cstring>, <vector>, <algorithm>",
        "algorithm_claims": "Anatomical protection mask using 106 landmarks and yaw/pitch rotation compensation to prevent skin leakage",
        "numerical_constants": "cx=0.5W, cy=0.48H, rx=0.22W, ry=0.28H, numLandmarks=106",
        "time_complexity": "O(W * H * N_poly)",
        "space_complexity": "O(W * H)",
        "integration_assumptions": "Landmarks ordered by 106-point standard; face centered; float coordinates normalized or pixel",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_barrier.cpp",
        "header_file": "hair_v2_barrier.h",
        "function_name": "pointInPolygon",
        "return_type": "bool",
        "parameter_signature": "float px, float py, const std::vector<Point2D>& poly",
        "inputs": "Point coordinate (px, py), polygon vertices list",
        "outputs": "Boolean inside/outside",
        "dependencies": "<vector>",
        "algorithm_claims": "Ray-casting Jordan curve theorem point-in-polygon test",
        "numerical_constants": "None",
        "time_complexity": "O(N_vertices)",
        "space_complexity": "O(1)",
        "integration_assumptions": "2D planar non-self-intersecting polygon",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_base_tone.cpp",
        "header_file": "hair_v2_dye.h",
        "function_name": "estimateBaseHairState",
        "return_type": "HairV2Status",
        "parameter_signature": "const float* linearRgb, const AlphaMatteBuffer& matte, const FrameGeometry& geom, BaseHairState& out",
        "inputs": "linearRgb (float 3*N), AlphaMatteBuffer, FrameGeometry",
        "outputs": "BaseHairState (meanLuma, shadowLuma, highlightLuma, chroma, warmth, darkness, dyedConfidence)",
        "dependencies": "hair_v2_dye.h, <cmath>, <vector>, <algorithm>, <omp.h>",
        "algorithm_claims": "Base hair statistical luminance distribution & melanin warmth estimation with 10th/90th percentiles",
        "numerical_constants": "alpha_thresh=0.15, luma_w=[0.2126, 0.7152, 0.0722], bins=256, p10=0.10, p90=0.90",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(256)",
        "integration_assumptions": "Alpha matte pre-thresholded; linear RGB normalized [0, 1]",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_color.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "srgbToLinear",
        "return_type": "float",
        "parameter_signature": "float c",
        "inputs": "sRGB channel [0, 1]",
        "outputs": "Linear RGB channel [0, 1]",
        "dependencies": "<cmath>",
        "algorithm_claims": "Exact IEC 61966-2-1 piecewise gamma transfer function",
        "numerical_constants": "thresh=0.04045, div=12.92, offset=0.055, scale=1.055, gamma=2.4",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Normalized float input",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_color.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "linearToSrgb",
        "return_type": "float",
        "parameter_signature": "float c",
        "inputs": "Linear RGB channel [0, 1]",
        "outputs": "sRGB channel [0, 1]",
        "dependencies": "<cmath>",
        "algorithm_claims": "Exact inverse IEC 61966-2-1 piecewise gamma transfer function",
        "numerical_constants": "thresh=0.0031308, mul=12.92, offset=0.055, scale=1.055, inv_gamma=1/2.4",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Normalized float input clamped >= 0",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_color.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "batchSrgbToLinear",
        "return_type": "void",
        "parameter_signature": "const uint32_t* srcArgb, float* dstLinearRgb, size_t numPixels",
        "inputs": "srcArgb (uint32_t ARGB8888), numPixels",
        "outputs": "dstLinearRgb (float 3*N linear RGB)",
        "dependencies": "<cmath>, <omp.h>",
        "algorithm_claims": "Multi-threaded batch color unspooling and linearization",
        "numerical_constants": "None",
        "time_complexity": "O(N)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Contiguous memory layout; 64-byte aligned",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_color.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "batchLinearToSrgb",
        "return_type": "void",
        "parameter_signature": "const float* srcLinearRgb, uint32_t* dstArgb, size_t numPixels",
        "inputs": "srcLinearRgb (float 3*N linear RGB), numPixels",
        "outputs": "dstArgb (uint32_t ARGB8888)",
        "dependencies": "<cmath>, <omp.h>",
        "algorithm_claims": "Multi-threaded batch gamma encoding and ARGB packing",
        "numerical_constants": "None",
        "time_complexity": "O(N)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Contiguous memory layout; alpha set to 0xFF",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_color.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "softChromaCompress",
        "return_type": "void",
        "parameter_signature": "float& r, float& g, float& b, float maxChroma",
        "inputs": "Linear RGB channels (inout), maxChroma threshold",
        "outputs": "Chroma-compressed RGB channels",
        "dependencies": "<cmath>, <algorithm>",
        "algorithm_claims": "Knee-curve soft chroma desaturation to prevent harsh out-of-gamut clipping",
        "numerical_constants": "maxChroma=0.95, knee=0.75*maxChroma",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Preserves luminance while desaturating chroma",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_directional_filter.cpp",
        "header_file": "hair_v2_texture.h",
        "function_name": "sampleBilinear",
        "return_type": "float",
        "parameter_signature": "const float* src, int W, int H, float x, float y",
        "inputs": "src buffer, width W, height H, float coordinate (x, y)",
        "outputs": "Bilinearly interpolated value",
        "dependencies": "<cmath>, <algorithm>",
        "algorithm_claims": "Continuous subpixel coordinate bilinear interpolation with clamping boundary",
        "numerical_constants": "None",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "0 <= x < W, 0 <= y < H",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_directional_filter.cpp",
        "header_file": "hair_v2_texture.h",
        "function_name": "directionalFilter1D",
        "return_type": "void",
        "parameter_signature": "const float* src, float* dst, const HairFlowField& flow, const FrameGeometry& geom, int radius, bool alongTangent",
        "inputs": "src buffer, HairFlowField (tangent, normal), FrameGeometry, filter radius, alongTangent flag",
        "outputs": "dst filtered buffer",
        "dependencies": "hair_v2_texture.h, <cmath>, <vector>, <omp.h>",
        "algorithm_claims": "1D flow-aligned continuous Gaussian filter along fiber tangents or across normals",
        "numerical_constants": "sigma=0.5*radius",
        "time_complexity": "O(W * H * radius)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Hair flow field must be unit normalized",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_dye.cpp",
        "header_file": "hair_v2_dye.h",
        "function_name": "applyHairDye",
        "return_type": "HairV2Status",
        "parameter_signature": "const float* linearRgb, const AlphaMatteBuffer& matte, const TextureDecomposition& texture, const DyeResponseBuffer& response, const FrameGeometry& geom, float* outLinearRgb",
        "inputs": "linearRgb, AlphaMatteBuffer, TextureDecomposition, DyeResponseBuffer, FrameGeometry",
        "outputs": "outLinearRgb (dyed linear RGB)",
        "dependencies": "hair_v2_dye.h, <cmath>, <algorithm>, <omp.h>",
        "algorithm_claims": "Base-aware dye application with texture preservation and shadow/highlight protection",
        "numerical_constants": "micro_weight=1.0, meso_weight=1.0",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(1)",
        "integration_assumptions": "DyeResponseBuffer must match input geometry",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_flow.cpp",
        "header_file": "hair_v2_flow.h",
        "function_name": "gaussianBlurSeparable",
        "return_type": "void",
        "parameter_signature": "const float* src, float* dst, int W, int H, float sigma",
        "inputs": "src buffer, width W, height H, sigma",
        "outputs": "dst smoothed buffer",
        "dependencies": "<cmath>, <cstring>, <vector>, <omp.h>",
        "algorithm_claims": "Separable 1D horizontal + vertical Gaussian convolution with discrete kernel truncation",
        "numerical_constants": "k_radius=std::ceil(2.5*sigma)",
        "time_complexity": "O(W * H * sigma)",
        "space_complexity": "O(W * H) temp buffer",
        "integration_assumptions": "Edge clamp boundary condition",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_flow.cpp",
        "header_file": "hair_v2_flow.h",
        "function_name": "computeHairFlow",
        "return_type": "HairV2Status",
        "parameter_signature": "const float* luminance, const AlphaMatteBuffer& matte, const FrameGeometry& geom, HairFlowField& out",
        "inputs": "luminance (float WxH), AlphaMatteBuffer, FrameGeometry",
        "outputs": "HairFlowField (tangentX, tangentY, normalX, normalY, theta, coherence)",
        "dependencies": "hair_v2_flow.h, <cmath>, <vector>, <omp.h>",
        "algorithm_claims": "Structure Tensor (Jxx, Jyy, Jxy) eigendecomposition for hair strand orientation and coherence",
        "numerical_constants": "sigma=2.0, epsilon=1e-6",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(W * H) tensor buffers",
        "integration_assumptions": "Grayscale luminance normalized [0, 1]",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_flow_regularizer.cpp",
        "header_file": "hair_v2_flow.h",
        "function_name": "regularizeHairFlow",
        "return_type": "HairV2Status",
        "parameter_signature": "const AlphaMatteBuffer& matte, const FrameGeometry& geom, HairFlowField& flow",
        "inputs": "AlphaMatteBuffer, FrameGeometry, HairFlowField (inout)",
        "outputs": "HairFlowField with regularized axial vectors and smoothed theta",
        "dependencies": "hair_v2_flow.h, <cmath>, <vector>, <omp.h>",
        "algorithm_claims": "Axial double-angle vector smoothing (u=cos 2theta, v=sin 2theta) with coherence weighting",
        "numerical_constants": "radius=2 (5x5 window)",
        "time_complexity": "O(W * H * 25)",
        "space_complexity": "O(W * H)",
        "integration_assumptions": "Theta in [0, PI); avoids PI-wrapping phase cancellation",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_flow_regularizer.cpp",
        "header_file": "hair_v2_flow.h",
        "function_name": "propagateLowConfidenceFlow",
        "return_type": "HairV2Status",
        "parameter_signature": "const AlphaMatteBuffer& matte, const FrameGeometry& geom, HairFlowField& flow",
        "inputs": "AlphaMatteBuffer, FrameGeometry, HairFlowField (inout)",
        "outputs": "HairFlowField with propagated orientation in low-coherence areas",
        "dependencies": "hair_v2_flow.h, <queue>, <vector>",
        "algorithm_claims": "Multi-source BFS propagation from high-coherence strand seeds into low-coherence shadow areas",
        "numerical_constants": "COHERENCE_HIGH=0.35, COHERENCE_LOW=0.20",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(W * H)",
        "integration_assumptions": "Avoids vertical gravity fallback by borrowing orientation from adjacent curls",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_lab.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "fCie",
        "return_type": "float",
        "parameter_signature": "float t",
        "inputs": "Normalized tristimulus ratio t",
        "outputs": "f(t) nonlinear response",
        "dependencies": "<cmath>",
        "algorithm_claims": "CIE standard cube-root transfer with linear low-light extension",
        "numerical_constants": "delta=6/29, delta^3=216/24389",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Standard D65 daylight illuminant",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_lab.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "linearRgbToCIELab",
        "return_type": "CIELab",
        "parameter_signature": "float r, float g, float b",
        "inputs": "Linear RGB float channels",
        "outputs": "CIELab struct (L [0..100], a, b)",
        "dependencies": "hair_v2_color.h, <cmath>",
        "algorithm_claims": "D65 sRGB linear matrix conversion to CIEXYZ then CIELAB",
        "numerical_constants": "Xn=0.95047, Yn=1.00000, Zn=1.08883",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Inputs in [0, 1] range",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_lab.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "deltaE2000",
        "return_type": "double",
        "parameter_signature": "const CIELab& lab1, const CIELab& lab2",
        "inputs": "Two CIELab color coordinates",
        "outputs": "Perceptual color difference deltaE00 (double)",
        "dependencies": "hair_v2_color.h, <cmath>",
        "algorithm_claims": "Full ISO/CIE CIEDE2000 standard formula with rotation factor RT and hue weighting SH",
        "numerical_constants": "kL=1, kC=1, kH=1, standard parametric coefficients",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Industrial standard color perception metric",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_lift_curve.cpp",
        "header_file": "hair_v2_dye.h",
        "function_name": "computeDyeResponse",
        "return_type": "HairV2Status",
        "parameter_signature": "const BaseHairState& base, const HairPreset& preset, float intensity, const FrameGeometry& geom, DyeResponseBuffer& out",
        "inputs": "BaseHairState, HairPreset, intensity, FrameGeometry",
        "outputs": "DyeResponseBuffer (targetLinearRgb, liftMap, chromaMap, shadowProtection, highlightProtection)",
        "dependencies": "hair_v2_dye.h, <cmath>, <omp.h>",
        "algorithm_claims": "Salon bleach lift curve and melanin response calculation based on base darkness",
        "numerical_constants": "base_threshold=0.3, shadow_preserve=0.85, highlight_preserve=0.90",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(W * H)",
        "integration_assumptions": "Intensity in [0.0, 1.0]",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_matting.cpp",
        "header_file": "hair_v2_matting.h",
        "function_name": "computeIntegralImage",
        "return_type": "void",
        "parameter_signature": "const float* src, float* dst, int W, int H",
        "inputs": "src float buffer (WxH)",
        "outputs": "dst integral image buffer (WxH)",
        "dependencies": "<cstring>",
        "algorithm_claims": "Prefix-sum 2D integral image computation for O(1) box filtering",
        "numerical_constants": "None",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(W * H)",
        "integration_assumptions": "Contiguous float array",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_matting.cpp",
        "header_file": "hair_v2_matting.h",
        "function_name": "getBoxSum",
        "return_type": "float",
        "parameter_signature": "const float* integral, int W, int H, int x1, int y1, int x2, int y2",
        "inputs": "integral buffer, bounding box (x1, y1) to (x2, y2)",
        "outputs": "Sum of values in bounding box",
        "dependencies": "<algorithm>",
        "algorithm_claims": "4-point integral image lookup",
        "numerical_constants": "None",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Clamped box boundaries",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_matting.cpp",
        "header_file": "hair_v2_matting.h",
        "function_name": "refineHairAlpha",
        "return_type": "HairV2Status",
        "parameter_signature": "const uint32_t* argb, const AlphaMatteBuffer& trimapInput, const FrameGeometry& geom, AlphaMatteBuffer& out",
        "inputs": "argb source pixels, trimapInput, FrameGeometry",
        "outputs": "out AlphaMatteBuffer (refined alpha [0, 1])",
        "dependencies": "hair_v2_matting.h, <cmath>, <vector>, <omp.h>",
        "algorithm_claims": "He et al. Guided Filter alpha matting using integral images and protectMask enforcement",
        "numerical_constants": "r=6, eps=1e-4",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(4 * W * H) ~19.6MB",
        "integration_assumptions": "Trimap defines definite foreground (255) and definite background (0)",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_oklab.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "linearRgbToOKLab",
        "return_type": "OKLab",
        "parameter_signature": "float r, float g, float b",
        "inputs": "Linear RGB float channels",
        "outputs": "OKLab struct (L, a, b)",
        "dependencies": "hair_v2_color.h, <cmath>",
        "algorithm_claims": "Bjorn Ottosson OKLab perceptual color space transform",
        "numerical_constants": "Ottosson M1, M2 matrix constants",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Linear RGB [0, 1]",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_oklab.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "okLabToLinearRgb",
        "return_type": "void",
        "parameter_signature": "const OKLab& lab, float& r, float& g, float& b",
        "inputs": "OKLab struct",
        "outputs": "Linear RGB float channels (out)",
        "dependencies": "hair_v2_color.h, <cmath>",
        "algorithm_claims": "Inverse OKLab transform to linear RGB via cube exponent and inverse matrices",
        "numerical_constants": "Ottosson inv M1, inv M2 matrices",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Cubes l, m, s responses",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_oklab.cpp",
        "header_file": "hair_v2_color.h",
        "function_name": "deltaE_OK",
        "return_type": "float",
        "parameter_signature": "const OKLab& a, const OKLab& b",
        "inputs": "Two OKLab color coordinates",
        "outputs": "Euclidean distance in OKLab space",
        "dependencies": "<cmath>",
        "algorithm_claims": "Perceptually uniform color distance in OKLab",
        "numerical_constants": "None",
        "time_complexity": "O(1)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Euclidean metric valid due to OKLab uniformity",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_pipeline.cpp",
        "header_file": "hair_v2_pipeline.h",
        "function_name": "processHairPipelineV2",
        "return_type": "HairV2Status",
        "parameter_signature": "const uint32_t* srcArgb, const float* coarseHairProb, const uint8_t* faceMask, const LandmarkSet* landmarks, const PoseEstimate* pose, const HairPreset& preset, float intensity, const HairV2Config& config, const FrameGeometry& geom, uint32_t* dstArgb",
        "inputs": "srcArgb, coarseHairProb, faceMask, landmarks, pose, preset, intensity, config, geom",
        "outputs": "dstArgb (processed ARGB pixels)",
        "dependencies": "hair_v2_pipeline.h, all modular headers, <vector>, <cstring>",
        "algorithm_claims": "End-to-end 12-stage sequential hair recolor pipeline coordinator",
        "numerical_constants": "guidedRadius=8, guidedEps=1e-3",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(12 * W * H * 4) ~60MB",
        "integration_assumptions": "Allocates aligned intermediate buffers; monolithic synchronous C++ flow",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_relighting.cpp",
        "header_file": "hair_v2_relighting.h",
        "function_name": "applyHairRelighting",
        "return_type": "HairV2Status",
        "parameter_signature": "const float* dyedLinearRgb, const float* sheen, const AlphaMatteBuffer& matte, const FrameGeometry& geom, float* outLinearRgb",
        "inputs": "dyedLinearRgb, sheen, AlphaMatteBuffer, FrameGeometry",
        "outputs": "outLinearRgb (relighted linear RGB)",
        "dependencies": "hair_v2_relighting.h, <cmath>, <omp.h>",
        "algorithm_claims": "Additive anisotropic specular sheen blending modulated by alpha matte",
        "numerical_constants": "clamp=[0.0, 1.0]",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Linear color space addition",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_specular.cpp",
        "header_file": "hair_v2_relighting.h",
        "function_name": "estimateImageSpaceLightDirection",
        "return_type": "HairV2Status",
        "parameter_signature": "const float* originalLinearRgb, const AlphaMatteBuffer& matte, const FrameGeometry& geom, LightEstimate& out",
        "inputs": "originalLinearRgb, AlphaMatteBuffer, FrameGeometry",
        "outputs": "LightEstimate (dirX, dirY, dirZ, intensity)",
        "dependencies": "hair_v2_relighting.h, <cmath>, <omp.h>",
        "algorithm_claims": "Image-space key light estimation from highlight centroid relative to hair mass center",
        "numerical_constants": "luma_highlight_thresh=0.60, default_dir=(0.0, -0.894, 0.447)",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Assumes primary key light creates dominant highlight",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_specular.cpp",
        "header_file": "hair_v2_relighting.h",
        "function_name": "computeAnisotropicHairSheen",
        "return_type": "HairV2Status",
        "parameter_signature": "const HairFlowField& flow, const TextureDecomposition& texture, const LightEstimate& light, const RelightingParams& params, const AlphaMatteBuffer& matte, const FrameGeometry& geom, float* outSheen",
        "inputs": "HairFlowField, TextureDecomposition, LightEstimate, RelightingParams, AlphaMatteBuffer, FrameGeometry",
        "outputs": "outSheen (float WxH specular map)",
        "dependencies": "hair_v2_relighting.h, <cmath>, <omp.h>",
        "algorithm_claims": "Dual-lobe Kajiya-Kay / Marschner anisotropic specular model (R primary + TRT secondary)",
        "numerical_constants": "a1=3deg (0.052rad), a2=-6deg (-0.105rad), primary_exp=32, secondary_exp=8",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Cuticle shift angles match real human hair anatomy",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_texture.cpp",
        "header_file": "hair_v2_texture.h",
        "function_name": "decomposeHairTexture",
        "return_type": "HairV2Status",
        "parameter_signature": "const float* linearRgb, const AlphaMatteBuffer& matte, const HairFlowField& flow, const FrameGeometry& geom, TextureDecomposition& out",
        "inputs": "linearRgb, AlphaMatteBuffer, HairFlowField, FrameGeometry",
        "outputs": "TextureDecomposition (low volume, meso curls, micro flyaways, crease shadows)",
        "dependencies": "hair_v2_texture.h, <cmath>, <vector>, <omp.h>",
        "algorithm_claims": "Tri-band anisotropic texture frequency decomposition along and across flow tangents",
        "numerical_constants": "radius=6, alongTangent=true/false",
        "time_complexity": "O(W * H * radius)",
        "space_complexity": "O(W * H) buffers",
        "integration_assumptions": "Hair flow field must be populated",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_texture.cpp",
        "header_file": "hair_v2_texture.h",
        "function_name": "reconstructHairTexture",
        "return_type": "HairV2Status",
        "parameter_signature": "const TextureDecomposition& tex, const float* recoloredBase, const AlphaMatteBuffer& matte, const FrameGeometry& geom, float* outLinearRgb",
        "inputs": "TextureDecomposition, recoloredBase, AlphaMatteBuffer, FrameGeometry",
        "outputs": "outLinearRgb with reconstructed hair fibers",
        "dependencies": "hair_v2_texture.h, <cmath>, <omp.h>",
        "algorithm_claims": "High-frequency strand fiber re-injection with anti-halo clamping and crease shadow modulation",
        "numerical_constants": "micro_gain=1.2, crease_atten=0.5",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(1)",
        "integration_assumptions": "Anti-halo clamp prevents negative luminance",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    },
    {
        "module_file": "hair_v2_trimap.cpp",
        "header_file": "hair_v2_trimap.h",
        "function_name": "buildAdaptiveTrimap",
        "return_type": "HairV2Status",
        "parameter_signature": "const uint32_t* argb, const float* coarseHairProb, const uint8_t* faceMask, const FrameGeometry& geom, AlphaMatteBuffer& out",
        "inputs": "argb, coarseHairProb, faceMask, FrameGeometry",
        "outputs": "out (AlphaMatteBuffer with trimap: 0=BG, 128=unknown, 255=FG)",
        "dependencies": "hair_v2_trimap.h, <cmath>, <vector>, <omp.h>",
        "algorithm_claims": "Adaptive morphological trimap generation with dual-thresholding and unknown band dilation",
        "numerical_constants": "fg_thresh=0.85, bg_thresh=0.15, dilate_radius=3",
        "time_complexity": "O(W * H)",
        "space_complexity": "O(W * H)",
        "integration_assumptions": "Face mask takes precedence over hair probability",
        "provenance": "PROJECT_RECONSTRUCTED_SOURCE"
    }
]

with open(out_csv, "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=list(rows[0].keys()))
    writer.writeheader()
    writer.writerows(rows)

print(f"Wrote {len(rows)} function records to {out_csv}")
