-- @author: xyg2@meitu.com
------ ui

ui = {
    -- 有效力度 = 整体×0.5 + 左/右×0.5（可叠加）
    upperDeformIntensity = { step = 0.01, precision = 3.00, ui_type = "slider", ui_name = "力度:整体", max = 1.0, min = -1, value = 0.0 },
    upperLeftDeformIntensity = { step = 0.01, precision = 3.00, ui_type = "slider", ui_name = "力度:左臂", max = 1.0, min = -1, value = 0.0 },
    upperRightDeformIntensity = { step = 0.01, precision = 3.00, ui_type = "slider", ui_name = "力度:右臂", max = 1.0, min = -1, value = 0.0 },
    liquifyAmpScale = {step = 0.01, precision = 2.0, ui_type = "slider", ui_name = "变形因子", max = 2.0, min = 0.05, value = 0.7},
    order={"upperDeformIntensity","upperLeftDeformIntensity","upperRightDeformIntensity","showUpperArmRegionBoxes","liquifyAmpScale","antiShake","regionVideo","debug"},
    showUpperArmRegionBoxes = { ui_type = "switch", value = false, ui_name = "显示大臂法向方框" },
    antiShake = {
        ui_type = "groupbox",
        ui_title = true,
        ui_name = "渲染",
        visible = false,
        order = {
            "offsetRTFixedSize",
            "offsetEncodeScale",
            "forearmMaskStrength",
            "forearmGaussianScale",
            "forearmGaussianIter",
            "forearmGaussianKernelSize",
        },
        offsetRTFixedSize = {
            step = 128,
            precision = 0,
            ui_type = "slider",
            ui_name = "位移图RT边长(0=半分辨率)",
            max = 2048.0,
            min = 0.0,
            value = 1024.0,
        },
        offsetEncodeScale = {
            step = 1,
            precision = 1,
            ui_type = "slider",
            ui_name = "位移烘焙放大(默认64)",
            max = 64.0,
            min = 1.0,
            value = 64.0,
        },
        forearmMaskStrength = {
            step = 0.01,
            precision = 2,
            ui_type = "slider",
            ui_name = "小臂保护强度",
            max = 1.0,
            min = 0.0,
            value = 1.0,
        },
        forearmGaussianScale = {
            step = 0.02,
            precision = 2,
            ui_type = "slider",
            ui_name = "小臂Mask模糊Scale",
            max = 3.0,
            min = 0.25,
            value = 1.35,
        },
        forearmGaussianIter = {
            step = 1,
            precision = 0,
            ui_type = "slider",
            ui_name = "小臂Mask模糊次数",
            max = 8,
            min = 1,
            value = 4,
        },
        forearmGaussianKernelSize = {
            step = 1,
            precision = 0,
            ui_type = "slider",
            ui_name = "小臂Mask模糊核尺寸",
            max = 20,
            min = 1,
            value = 6,
        },
    },
    regionVideo = {
        ui_type = "groupbox",
        ui_title = true,
        ui_name = "范围控制",
        visible = true,
        order = {
            "smoothAlpha",
            "armBoxBandCoef",
            "armSoftBandLateralScale",
            "armBoneAlongCoefUp",
            "armBoneAlongCoefDown",
        },
        smoothAlpha = {
            step = 0.01,
            precision = 3.0,
            ui_type = "slider",
            ui_name = "骨骼/框点一阶平滑",
            max = 1.0,
            min = 0.0,
            value = 0.6,
        },
        armBoxBandCoef = { step = 0.01, precision = 2.0, ui_type = "slider", ui_name = "宽度", max = 2.5, min = 0.5, value = 2.0 },
        armSoftBandLateralScale = { step = 0.01, precision = 2.0, ui_type = "slider", ui_name = "外侧软化范围系数", max = 3, min = 0.5, value = 1.0 },
        armBoneAlongCoefUp = { step = 0.01, precision = 2.0, ui_type = "slider", ui_name = "上基线延伸", max = 1.0, min = 0.0, value = 0.35 },
        armBoneAlongCoefDown = { step = 0.01, precision = 2.0, ui_type = "slider", ui_name = "下基线延伸", max = 0.5, min = 0.0, value = 0.3 },
    },
    debug={
        visible=true,
        ui_type = "groupbox",
        ui_title = true,
        ui_name = "显示",
        ui_fold = true,
        order={"showLeftSlim","showRightSlim","showLeftAlgoBox","showRightAlgoBox","showForearmContour","showForearmContourLines","showBodyPoints","showForearmMaskPoints","showSkeletonPoints","showContour","showMeshPoints"},
        showLeftSlim = { ui_type = "switch", value = false, ui_name = "左轮廓点" },
        showRightSlim = { ui_type = "switch", value = false, ui_name = "右轮廓点" },
        showLeftAlgoBox = { ui_type = "switch", value = false, ui_name = "左重建轮廓" },
        showRightAlgoBox = { ui_type = "switch", value = false, ui_name = "右重建轮廓" },
        showForearmContour = { ui_type = "switch", value = false, ui_name = "小臂轮廓点" },
        showForearmContourLines = { ui_type = "switch", value = false, ui_name = "小臂轮廓线" },
        showBodyPoints = { ui_type = "switch", value = false, ui_name = "身体点" },
        showForearmMaskPoints = { ui_type = "switch", value = false, ui_name = "小臂Mask点" },
        showSkeletonPoints = { ui_type = "switch", value = false, ui_name = "骨骼点" },
        showContour = { ui_type = "switch", value = false, ui_name = "轮廓线" },
        showMeshPoints = { step = 1, ui_type = "slider", ui_name = "显示内部点", max = 7, min = 0, value = 0 }, 
    },
}


paramTable = {}
paramTable["MVAR"]= {
    upperDeformIntensity = ui.upperDeformIntensity,
    upperLeftDeformIntensity = ui.upperLeftDeformIntensity,
    upperRightDeformIntensity = ui.upperRightDeformIntensity,
}

return {ui = ui, paramTable = paramTable}
