// Reconstructed Pseudocode for libMTFilterKernel_fn_000d1410 (_ZN14MTFilterKernel16MTAmbianceFilter4initEPNS_15GPUImageContextE)
// Library: libMTFilterKernel.so | RVA: 0x000d1410 | Size: 224 bytes
// Visibility: EXPORTED | Semantic: GPU_FBO_RENDER_PASS
// Referenced Strings:
//   'varying highp vec2 textureCoordinate; varying vec2 textureCoordinate2; uniform sampler2D inputImageTexture; uniform sampler2D inputImageTexture2; uniform sampler2D maskTexture; uniform float ambianceAlpha; uniform float saturationAlpha; uniform float isWithColorWeight; uniform float levelAlpha; uniform float levelBlack; uniform float levelWhite; vec3 overlay(lowp vec3 lowerColor, lowp vec3 upperColor) { vec3 stepEdge = step(0.5, lowerColor); vec3 inverseStepEdge = -stepEdge * 2.0 + 1.0; vec3 common1 = inverseStepEdge * (2.0 * lowerColor * upperColor); vec3 preAndMinValue = stepEdge * ((2.0 * upperColor) + (lowerColor - (1.0 - lowerColor))); vec3 result = common1 + preAndMinValue; return result; } vec3 getTanSpecail(lowp vec3 v1, lowp vec3 v2) { vec3 deltaV= (v1 - v2)* 2.0; vec3 stepSign=step(0.0,deltaV)*2.0-1.0; vec3 absVal=abs(deltaV); vec3 result=clamp(v2 + (-0.27765*absVal*absVal+1.0653*absVal)*stepSign/ 2.75,0.0,1.0); return result; } vec3 ApplySaturation(lowp vec3 color) { float saturation = saturationAlpha; if (saturationAlpha > 0.00){ float r = color.r; float g = color.g; float b = color.b; float maxValue = max(r, max(g, b)); float minValue = min(r, min(g, b)); float current_saturation = 0.00; if (maxValue != 0.00) { current_saturation = (maxValue - minValue) / maxValue; } float falloff = 1.0 - current_saturation; saturation *= falloff * 2.0; } saturation += 1.0; float luminance = 0.299 * color.r + 0.587 * color.g + 0.114 * color.b; vec3 result = clamp(mix(vec3(luminance), color, saturation), 0.0, 1.0); return result; } void main() { lowp vec3 color = texture2D(inputImageTexture, textureCoordinate).rgb; lowp vec3 blurColor = texture2D(inputImageTexture2, textureCoordinate2).rgb; lowp vec3 preProcColor=getTanSpecail(blurColor,color); preProcColor=mix(blurColor,preProcColor,step((blurColor.r+blurColor.g+blurColor.b)/3.0,(color.r+color.g+color.b)/3.0)); preProcColor = 1.0- preProcColor; lowp float extColor = (preProcColor.r + preProcColor.g + preProcColor.b) * 0.66667; lowp vec3 diffColor = clamp(extColor - preProcColor,0.0,1.0); lowp float avgColor = (diffColor.r+diffColor.g+diffColor.b) /3.0; lowp float extColor2 = avgColor * 0.5; preProcColor = diffColor * 0.5 + extColor2; vec3 overlayColor = overlay(color, preProcColor); float colorWeight = 1.0; if(isWithColorWeight>0.5) { float colorMin = min(min(color.r, color.g), color.b); float colorMax = max(max(color.r, color.g), color.b); float colorDiffWeight = 1.0-clamp((colorMax - colorMin-0.058)/0.132,0.0,1.0); colorWeight = 1.0-colorDiffWeight*clamp(colorMin-0.5, 0.0, 1.0)/0.5; } lowp float mask = texture2D(maskTexture, textureCoordinate).r; vec3 newColor = mix(color, overlayColor, ambianceAlpha*colorWeight); newColor = ApplySaturation(newColor); newColor = mix(newColor, clamp((newColor - vec3(levelBlack)) / (levelWhite-levelBlack), 0.0, 1.0), levelAlpha); newColor = mix(newColor, color, mask); gl_FragColor = vec4(newColor, 1.0); }'

void libMTFilterKernel_fn_000d1410(void* env, void* obj, ...) {
    call_func_0x001b42d0(...);
    call_func_0x001b4290(...);
    call_func_0x0010c20c(...);
    call_func_0x001b42e0(...);
    call_func_0x001b42e0(...);
    call_func_0x001b0544(...);
    call_func_0x001b4280(...);
    return;
}
