// Function: sub_92D558
// RVA: 0x92d558, Size: 4096 bytes
int64_t sub_92D558(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    const char* str = "Type";
    (*x8)(...);
    const char* str = "Script";
    sub_58F19C(...); // call internal at 0x92d5c0
    (*x8)(...);
    _ZdlPv(...); // call PLT API at 0x92d5e4
    const char* str = "EnableTouch";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableTouchGesture";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableSlam";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableARPlane";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableHorizontalARPlane";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableVerticalARPlane";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableARSkeleton";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableARInstantPlacement";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableGesture";
    (*x8)(...);
    (*x8)(...);
    const char* str = "ScriptEffectType";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFood";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableAnimal";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableHandPose";
    (*x8)(...);
    (*x8)(...);
    const char* str = "SegmentType";
    (*x8)(...);
    (*x8)(...);
    const char* str = "MultiplySegmentType";
    (*x8)(...);
    sub_92EA50(...); // call internal at 0x92d8b8
    const char* str = "EnableGyroscope";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableSkeleton";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableBodyContours";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFaceMouthMask";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFace";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableExternalPosEstimator";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnablePictureMode";
    (*x8)(...);
    (*x8)(...);
    const char* str = "NeedOriginImageRGBA";
    (*x8)(...);
    (*x8)(...);
    const char* str = "NeedCustomImageData";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableStickerLayer";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableTextLayer";
    (*x8)(...);
    (*x8)(...);
    const char* str = "IgnoreVisible";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFaceSegmemt";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableSegmentEye";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableHuman3D";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableInteractiveSegment";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableInstanceSegment";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableBodyInOne";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableBodyInOneBreast";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableBodyInOneNeck";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFaceDL3DReconstructor";
    (*x8)(...);
    (*x8)(...);
    const char* str = "SpaceDepth";
    (*x8)(...);
    (*x8)(...);
    const char* str = "SpaceNormal";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFaceReconstructor";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFace2DReconstructor";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFace2DBackgroundReconstructor";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableCGTexture";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableNails";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableOutstanding";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableDenserHair";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableDenserHairMask";
    (*x8)(...);
    (*x8)(...);
    sub_59C57C(...); // call internal at 0x92dea8
    _ZdlPv(...); // call PLT API at 0x92deec
    sub_59C57C(...); // call internal at 0x92df50
    _ZdlPv(...); // call PLT API at 0x92df9c
    const char* str = "GenSegmentMaskEdge";
    (*x8)(...);
    sub_5C09E0(...); // call internal at 0x92dfc0
    _ZdlPv(...); // call PLT API at 0x92dfd0
    const char* str = "EnableMultiMaskEdge";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableMultiplyInstance";
    (*x8)(...);
    (*x8)(...);
    const char* str = "MessageType";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFaceDL3DNet";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableEar";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableNeck";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableEmotionDetect";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableMemoryCount";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableAIKit";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableAiDetect";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFace3DFA";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFace3DFAMesh";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableFaceHead";
    (*x8)(...);
    (*x8)(...);
    const char* str = "EnableARImageTracking";
    (*x8)(...);
    (*x8)(...);
    sub_5A09F4(...); // call internal at 0x92e308
    _ZdlPv(...); // call PLT API at 0x92e350
    const char* str = "BPRequire";
    (*x8)(...);
    sub_61E868(...); // call internal at 0x92e3b0
    _ZdlPv(...); // call PLT API at 0x92e3c0
    const char* str = "Parameters";
    (*x8)(...);
    const char* str = "EngilishTip";
    (*x8)(...);
    (*x9)(...);
    const char* str = "Type";
    (*x8)(...);
    sub_932938(...); // call internal at 0x92e488
    (*x8)(...);
    const char* str = "Flag";
    (*x8)(...);
    (*x9)(...);
    (*x8)(...);
    const char* str = "Key";
    (*x8)(...);
    sub_A047C8(...); // call internal at 0x92e50c
    (*x8)(...);
    _ZdlPv(...); // call PLT API at 0x92e530
    const char* str = "ChineseTip";
    (*x8)(...);
}
