// Function: sub_7BAA60
// RVA: 0x7baa60, Size: 4096 bytes
int64_t sub_7BAA60(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    _Znwm(...); // call PLT API at 0x7baa9c
    _Znwm(...); // call PLT API at 0x7baad0
    _Znwm(...); // call PLT API at 0x7bab08
    _Znwm(...); // call PLT API at 0x7bab40
    _Znwm(...); // call PLT API at 0x7bab74
    _Znwm(...); // call PLT API at 0x7baba4
    _Znwm(...); // call PLT API at 0x7babdc
    _Znwm(...); // call PLT API at 0x7bac10
    _Znwm(...); // call PLT API at 0x7bac40
    _Znwm(...); // call PLT API at 0x7bac78
    _Znwm(...); // call PLT API at 0x7bacb0
    _Znwm(...); // call PLT API at 0x7bace8
    _Znwm(...); // call PLT API at 0x7bad20
    _Znwm(...); // call PLT API at 0x7bad58
    _Znwm(...); // call PLT API at 0x7bad90
    _Znwm(...); // call PLT API at 0x7badc8
    _Znwm(...); // call PLT API at 0x7bae00
    _Znwm(...); // call PLT API at 0x7bae38
    _Znwm(...); // call PLT API at 0x7bae70
    _Znwm(...); // call PLT API at 0x7baea8
    _Znwm(...); // call PLT API at 0x7baedc
    _Znwm(...); // call PLT API at 0x7baf14
    _Znwm(...); // call PLT API at 0x7baf4c
    _Znwm(...); // call PLT API at 0x7baf80
    _Znwm(...); // call PLT API at 0x7bafb8
    _Znwm(...); // call PLT API at 0x7bafec
    _Znwm(...); // call PLT API at 0x7bb024
    _Znwm(...); // call PLT API at 0x7bb058
    _Znwm(...); // call PLT API at 0x7bb090
    _Znwm(...); // call PLT API at 0x7bb0c8
    _Znwm(...); // call PLT API at 0x7bb100
    _Znwm(...); // call PLT API at 0x7bb138
    _Znwm(...); // call PLT API at 0x7bb170
    _Znwm(...); // call PLT API at 0x7bb1a8
    _Znwm(...); // call PLT API at 0x7bb1e0
    _Znwm(...); // call PLT API at 0x7bb218
    _Znwm(...); // call PLT API at 0x7bb250
    _Znwm(...); // call PLT API at 0x7bb288
    _Znwm(...); // call PLT API at 0x7bb2c0
    _Znwm(...); // call PLT API at 0x7bb2f8
    _Znwm(...); // call PLT API at 0x7bb328
    _Znwm(...); // call PLT API at 0x7bb358
    _Znwm(...); // call PLT API at 0x7bb390
    _Znwm(...); // call PLT API at 0x7bb3c8
    _Znwm(...); // call PLT API at 0x7bb400
    _Znwm(...); // call PLT API at 0x7bb438
    _Znwm(...); // call PLT API at 0x7bb470
    _Znwm(...); // call PLT API at 0x7bb4a8
    _Znwm(...); // call PLT API at 0x7bb4e0
    _Znwm(...); // call PLT API at 0x7bb518
    _Znwm(...); // call PLT API at 0x7bb550
    _Znwm(...); // call PLT API at 0x7bb588
    _Znwm(...); // call PLT API at 0x7bb5c0
    _Znwm(...); // call PLT API at 0x7bb5f8
    _Znwm(...); // call PLT API at 0x7bb630
    _Znwm(...); // call PLT API at 0x7bb664
    _Znwm(...); // call PLT API at 0x7bb69c
    _Znwm(...); // call PLT API at 0x7bb6d4
    _Znwm(...); // call PLT API at 0x7bb70c
    _Znwm(...); // call PLT API at 0x7bb744
    _Znwm(...); // call PLT API at 0x7bb77c
    _Znwm(...); // call PLT API at 0x7bb7b4
    _Znwm(...); // call PLT API at 0x7bb7ec
    _Znwm(...); // call PLT API at 0x7bb824
    _Znwm(...); // call PLT API at 0x7bb85c
    _Znwm(...); // call PLT API at 0x7bb894
    _Znwm(...); // call PLT API at 0x7bb8cc
    _Znwm(...); // call PLT API at 0x7bb904
    _Znwm(...); // call PLT API at 0x7bb93c
    _Znwm(...); // call PLT API at 0x7bb974
    _Znwm(...); // call PLT API at 0x7bb9ac
    _Znwm(...); // call PLT API at 0x7bb9e4
    _Znwm(...); // call PLT API at 0x7bba1c
    _Znwm(...); // call PLT API at 0x7bba54
}
