// Function: mizar::CodeName(int)
// RVA: 0xe9c44, Size: 1932 bytes
int64_t _ZN5mizar8CodeNameEi(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    const char* str = "OP_INFERSHAPE_ERROR";
    return a0;
    const char* str = "OPENVINO_INIT_ERROR";
    return a0;
    const char* str = "BACKEND_NOT_SUPPORT";
    return a0;
    const char* str = "TEXTURE_CONVERT_ERROR";
    return a0;
    const char* str = "OK";
    return a0;
    const char* str = "CPU_RUNTIME_ERROR";
    return a0;
    const char* str = "OP_PARAM_ERROR";
    return a0;
    const char* str = "QNN_INIT_ERROR";
    return a0;
    const char* str = "SIZE_MISMATCH";
    return a0;
    const char* str = "OPENGL_INIT_FAIL";
    return a0;
    const char* str = "INVALID_MEM";
    return a0;
    const char* str = "PARSER_ERROR";
    return a0;
    const char* str = "LIBRARY_LOAD_FAIL";
    return a0;
    const char* str = "OPENCL_INIT_FAIL";
    return a0;
    const char* str = "INSTANCE_OUTPUT_ERROR";
    return a0;
    const char* str = "APU_RUNTIME_ERROR";
    return a0;
    const char* str = "MODEL_PARAM_ERROR";
    return a0;
    const char* str = "METAL_RUNTIME_ERROR";
    return a0;
    const char* str = "MEM_MAP_FAIL";
    return a0;
    const char* str = "ONNX_OP_UNSUPPORT";
    return a0;
    const char* str = "CHECK";
    return a0;
    const char* str = "OPENCL_KERNELBUILD_ERROR";
    return a0;
    const char* str = "INSTANCE_INIT_ERROR";
    return a0;
    const char* str = "QNN_PARAM_ERROR";
    return a0;
    const char* str = "VALUE_OUT_OF_RANGE";
    return a0;
    const char* str = "OPENGL_RUNTIME_ERROR";
    return a0;
    const char* str = "GRAPH_STRUCTURE_ERROR";
    return a0;
    const char* str = "HIAI_RUNTIME_ERROR";
    return a0;
    const char* str = "MODEL_LOAD_FAIL";
    return a0;
    const char* str = "COREML_RUNTIME_ERROR";
    return a0;
    const char* str = "MEM_COPY_FAIL";
    return a0;
    const char* str = "COREML_PARSE_ERROR";
    return a0;
    const char* str = "TYPE_MISMATCH";
    return a0;
    const char* str = "OPENGL_KERNELBUILD_ERROR";
    return a0;
    const char* str = "INSTANCE_CONFIG_ERROR";
    return a0;
    const char* str = "INVALID_NET";
    return a0;
    const char* str = "MODEL_SHAPE_ERROR";
    return a0;
    const char* str = "METAL_COMPILE_ERROR";
    return a0;
    const char* str = "MEM_ALLOC_FAIL";
    return a0;
    const char* str = "ONNX_PARSE_ERROR";
    return a0;
    const char* str = "MODEL_SAVE_FAIL";
    return a0;
    const char* str = "DIRECTX_RUNTIME_ERROR";
    return a0;
    const char* str = "MEM_POOL_STATE_ERROR";
    return a0;
    const char* str = "LAYOUT_CONVERT_ERROR";
    return a0;
    const char* str = "CONTINUE";
    return a0;
    const char* str = "KERNEL_UNSUPPORTED";
    return a0;
    const char* str = "OP_INPUT_ERROR";
    return a0;
    const char* str = "OPENVINO_RUNTIME_ERROR";
    return a0;
    const char* str = "INVALID_USAGE";
    return a0;
    const char* str = "OPENCL_API_ERROR";
    return a0;
    const char* str = "INSTANCE_INPUT_ERROR";
    return a0;
    const char* str = "APU_INIT_ERROR";
    return a0;
    const char* str = "TODO";
    return a0;
    const char* str = "OPENCL_RUNTIME_ERROR";
    return a0;
    const char* str = "OP_BROADCAST_ERROR";
    return a0;
    const char* str = "QNN_RUNTIME_ERROR";
    return a0;
    const char* str = "NULL_POINTER";
    return a0;
    const char* str = "OPENCL_INTEROP_ERROR";
    return a0;
    const char* str = "INSTANCE_OP_CREATE_FAIL";
    return a0;
    const char* str = "HIAI_INIT_ERROR";
    return a0;
    const char* str = "MODEL_COMPILE_FAIL";
    return a0;
    const char* str = "COREML_COMPILE_ERROR";
    return a0;
    const char* str = "MEM_UNMAP_FAIL";
    return a0;
    const char* str = "MANIS_PARSE_ERROR";
    return a0;
    const char* str = "MODEL_TYPE_UNSUPPORT";
    return a0;
    const char* str = "DIRECTX_INIT_ERROR";
    return a0;
    const char* str = "MEM_SIZE_INSUFFICIENT";
    return a0;
    const char* str = "CONVERT_ERROR";
    return a0;
    const char* str = "UNDEFINED";
    return a0;
}
