package com.mt.mtxx.mtxx.beauty

/**
 * Canonical Registry of 12 Face/Beauty Modules and 104 Audited Features
 * with Testability Classification according to TASK_008 standard.
 */
enum class TestabilityClass(
    val code: String,
    val description: String
) {
    CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM("CLASS_A", "Parameter Transformation & Boundary Clamping"),
    CLASS_B_LANDMARK_AND_GEOMETRIC_BOUNDS("CLASS_B", "Landmark & ROI Geometric Bounds Validation"),
    CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE("CLASS_C", "Color LUT / Palette & Discrete Preset Selection"),
    CLASS_D_UNCHANGED_REGION_AND_ROI_PRESERVATION("CLASS_D", "Unchanged-Region & Alpha Matte Mask Boundaries"),
    CLASS_E_PIPELINE_CONTRACT_AND_CRASH_SAFETY("CLASS_E", "End-to-End Pipeline & Native Crash Safety Contracts")
}

data class FeatureTestDefinition(
    val moduleId: String,
    val moduleName: String,
    val featureId: String,
    val featureName: String,
    val testabilityClass: TestabilityClass,
    val cppSymbol: String,
    val jniFunction: String,
    val kotlinBinding: String,
    val uiToolId: String,
    val sliderMin: Float = 0f,
    val sliderMax: Float = 100f,
    val nominalDefault: Float = 0f,
    val engineMin: Float = 0f,
    val engineMax: Float = 1f,
    val roiTarget: String = "FULL_FACE"
)

object FaceBeautyTestabilityRegistry {

    val ALL_104_FEATURES: List<FeatureTestDefinition> = listOf(
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_01",
            featureName = "Eye Enlarge",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyeRetouchEngine::applyEyeEnlarge",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeEnlarge",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeEnlarge",
            uiToolId = "tool_eye_enlarge",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_02",
            featureName = "Eye Brighten",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyeRetouchEngine::applyEyeBrighten",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeBrighten",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeBrighten",
            uiToolId = "tool_eye_brighten",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_03",
            featureName = "Eye Clarity",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyeRetouchEngine::applyEyeClarity",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeClarity",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeClarity",
            uiToolId = "tool_eye_clarity",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_04",
            featureName = "Dark Circle Removal",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyeRetouchEngine::applyDarkCircleRemoval",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyDarkCircleRemoval",
            kotlinBinding = "MeituNativeEngine.nativeApplyDarkCircleRemoval",
            uiToolId = "tool_eye_dark_circle",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_05",
            featureName = "Eye Bag Removal",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyeRetouchEngine::applyEyeBagRemoval",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeBagRemoval",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeBagRemoval",
            uiToolId = "tool_eye_bag",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_06",
            featureName = "Crow Feet Removal",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyeRetouchEngine::applyCrowFeetRemoval",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyCrowFeetRemoval",
            kotlinBinding = "MeituNativeEngine.nativeApplyCrowFeetRemoval",
            uiToolId = "tool_eye_crow_feet",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_07",
            featureName = "Inner Canthus Opening",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyeRetouchEngine::applyEyeInnerCanthus",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeInnerCanthus",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeInnerCanthus",
            uiToolId = "tool_eye_inner_canthus",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_08",
            featureName = "Outer Canthus Opening",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyeRetouchEngine::applyEyeOuterCanthus",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeOuterCanthus",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeOuterCanthus",
            uiToolId = "tool_eye_outer_canthus",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_09",
            featureName = "Eye Shape Round",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyEyeShape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeShape",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeShape",
            uiToolId = "tool_eye_round",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_10",
            featureName = "Eye Shape Almond",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyEyeShape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeShape",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeShape",
            uiToolId = "tool_eye_almond",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_11",
            featureName = "Eye Shape Phoenix",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyEyeShape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeShape",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeShape",
            uiToolId = "tool_eye_phoenix",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_12",
            featureName = "Eye Shape Drooping",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyEyeShape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeShape",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeShape",
            uiToolId = "tool_eye_drooping",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_13",
            featureName = "Eye Shape Smiling",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyEyeShape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeShape",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeShape",
            uiToolId = "tool_eye_smiling",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_14",
            featureName = "Eye Shape Cat",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyEyeShape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeShape",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeShape",
            uiToolId = "tool_eye_cat",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_15",
            featureName = "Eye Shape Deep",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyEyeShape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyeShape",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyeShape",
            uiToolId = "tool_eye_deep",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_16",
            featureName = "Double Eyelid Parallel",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyDoubleEyelid",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyDoubleEyelid",
            kotlinBinding = "MeituNativeEngine.nativeApplyDoubleEyelid",
            uiToolId = "tool_eye_parallel",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_17",
            featureName = "Double Eyelid Fan",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyDoubleEyelid",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyDoubleEyelid",
            kotlinBinding = "MeituNativeEngine.nativeApplyDoubleEyelid",
            uiToolId = "tool_eye_fan",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_18",
            featureName = "Double Eyelid Crescent",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyDoubleEyelid",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyDoubleEyelid",
            kotlinBinding = "MeituNativeEngine.nativeApplyDoubleEyelid",
            uiToolId = "tool_eye_crescent",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_19",
            featureName = "Double Eyelid European",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyDoubleEyelid",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyDoubleEyelid",
            kotlinBinding = "MeituNativeEngine.nativeApplyDoubleEyelid",
            uiToolId = "tool_eye_europ",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_20",
            featureName = "Eye Catchlight",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyCatchlight",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyCatchlight",
            kotlinBinding = "MeituNativeEngine.nativeApplyCatchlight",
            uiToolId = "tool_eye_catchlight_star",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_21",
            featureName = "Iris / Pupil Color",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyIrisColor",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyIrisColor",
            kotlinBinding = "MeituNativeEngine.nativeApplyIrisColor",
            uiToolId = "tool_eye_pupil_color",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_01",
            moduleName = "Eyes",
            featureId = "EYE_22",
            featureName = "Red Eye Removal",
            testabilityClass = TestabilityClass.CLASS_D_UNCHANGED_REGION_AND_ROI_PRESERVATION,
            cppSymbol = "EyeRetouchEngine::applyRedEyeRemoval",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyRedEyeRemoval",
            kotlinBinding = "MeituNativeEngine.nativeApplyRedEyeRemoval",
            uiToolId = "tool_eye_red_eye",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_02",
            moduleName = "Eyebrows",
            featureId = "BROW_01",
            featureName = "Eyebrow Density",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyebrowLashEngine::applyEyebrowLash",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyebrowLash",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyebrowLash",
            uiToolId = "tool_eyebrow_density",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_02",
            moduleName = "Eyebrows",
            featureId = "BROW_02",
            featureName = "Eyebrow Thickness",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyebrowLashEngine::applyEyebrowLash",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyebrowLash",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyebrowLash",
            uiToolId = "tool_eyebrow_thickness",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_02",
            moduleName = "Eyebrows",
            featureId = "BROW_03",
            featureName = "Eyebrow Arch Height",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyebrowLashEngine::applyEyebrowLash",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyebrowLash",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyebrowLash",
            uiToolId = "tool_eyebrow_arch",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_02",
            moduleName = "Eyebrows",
            featureId = "BROW_04",
            featureName = "Eyebrow Position Shift",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyebrowLashEngine::applyEyebrowLash",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyebrowLash",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyebrowLash",
            uiToolId = "tool_eyebrow_position",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_02",
            moduleName = "Eyebrows",
            featureId = "BROW_05",
            featureName = "Eyebrow Distance / Spacing",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyebrowLashEngine::applyEyebrowLash",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyebrowLash",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyebrowLash",
            uiToolId = "tool_eyebrow_distance",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_02",
            moduleName = "Eyebrows",
            featureId = "BROW_06",
            featureName = "Eyebrow Color (5 shades)",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "EyeRetouchEngine::applyEyebrowColor",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyebrowColor",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyebrowColor",
            uiToolId = "NONE",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_03",
            moduleName = "Eyelashes",
            featureId = "LASH_01",
            featureName = "Eyelash Density (BrowLashEngine)",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyebrowLashEngine::applyEyebrowLash",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyebrowLash",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyebrowLash",
            uiToolId = "tool_lash_density",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_03",
            moduleName = "Eyelashes",
            featureId = "LASH_02",
            featureName = "Eyelash Length (BrowLashEngine)",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyebrowLashEngine::applyEyebrowLash",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyebrowLash",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyebrowLash",
            uiToolId = "tool_lash_length",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_03",
            moduleName = "Eyelashes",
            featureId = "LASH_03",
            featureName = "Eyelash Curl (BrowLashEngine)",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "EyebrowLashEngine::applyEyebrowLash",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyebrowLash",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyebrowLash",
            uiToolId = "tool_lash_curl",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_03",
            moduleName = "Eyelashes",
            featureId = "LASH_04",
            featureName = "Procedural Bezier Keratin Lashes",
            testabilityClass = TestabilityClass.CLASS_B_LANDMARK_AND_GEOMETRIC_BOUNDS,
            cppSymbol = "EyelashEngine::applyEyelash",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEyelash",
            kotlinBinding = "MeituNativeEngine.nativeApplyEyelash",
            uiToolId = "NONE",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EYE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_04",
            moduleName = "Nose",
            featureId = "NOSE_01",
            featureName = "Nose Size (Overall)",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyNoseEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyNoseEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyNoseEdit",
            uiToolId = "tool_nose_size",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "NOSE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_04",
            moduleName = "Nose",
            featureId = "NOSE_02",
            featureName = "Nose Bridge Lift",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyNoseEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyNoseEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyNoseEdit",
            uiToolId = "tool_nose_bridge_lift",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "NOSE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_04",
            moduleName = "Nose",
            featureId = "NOSE_03",
            featureName = "Nose Bridge Width",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyNoseEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyNoseEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyNoseEdit",
            uiToolId = "tool_nose_bridge_width",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "NOSE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_04",
            moduleName = "Nose",
            featureId = "NOSE_04",
            featureName = "Nose Tip Lift",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyNoseEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyNoseEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyNoseEdit",
            uiToolId = "tool_nose_tip_lift",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "NOSE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_04",
            moduleName = "Nose",
            featureId = "NOSE_05",
            featureName = "Nose Tip Size",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyNoseEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyNoseEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyNoseEdit",
            uiToolId = "tool_nose_tip_size",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "NOSE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_04",
            moduleName = "Nose",
            featureId = "NOSE_06",
            featureName = "Nose Ala Width",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyNoseEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyNoseEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyNoseEdit",
            uiToolId = "tool_nose_ala_width",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "NOSE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_04",
            moduleName = "Nose",
            featureId = "NOSE_07",
            featureName = "Nose Root Lift",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyNoseEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyNoseEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyNoseEdit",
            uiToolId = "tool_nose_root_lift",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "NOSE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_04",
            moduleName = "Nose",
            featureId = "NOSE_08",
            featureName = "Philtrum Length",
            testabilityClass = TestabilityClass.CLASS_B_LANDMARK_AND_GEOMETRIC_BOUNDS,
            cppSymbol = "NoseMouthBeardEngine::applyPhiltrumEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyPhiltrumEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyPhiltrumEdit",
            uiToolId = "NONE",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "NOSE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_04",
            moduleName = "Nose",
            featureId = "NOSE_09",
            featureName = "Philtrum Depth",
            testabilityClass = TestabilityClass.CLASS_D_UNCHANGED_REGION_AND_ROI_PRESERVATION,
            cppSymbol = "NoseMouthBeardEngine::applyPhiltrumEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyPhiltrumEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyPhiltrumEdit",
            uiToolId = "NONE",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "NOSE_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_01",
            featureName = "Mouth Overall Size",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyMouthEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyMouthEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyMouthEdit",
            uiToolId = "tool_mouth_size",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_02",
            featureName = "Lip Overall Thickness",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyMouthEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyMouthEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyMouthEdit",
            uiToolId = "tool_lip_thickness",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_03",
            featureName = "Upper Lip Thickness",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyMouthEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyMouthEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyMouthEdit",
            uiToolId = "tool_upper_lip_thickness",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_04",
            featureName = "Lower Lip Thickness",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyMouthEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyMouthEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyMouthEdit",
            uiToolId = "tool_lower_lip_thickness",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_05",
            featureName = "Mouth Corner Lift",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyMouthEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyMouthEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyMouthEdit",
            uiToolId = "tool_mouth_corner_lift",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_06",
            featureName = "Lip Peak Height",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyMouthEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyMouthEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyMouthEdit",
            uiToolId = "tool_lip_peak",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_07",
            featureName = "Smile Intensity",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyMouthEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyMouthEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyMouthEdit",
            uiToolId = "tool_smile",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_08",
            featureName = "Lipstick Matte",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "NoseMouthBeardEngine::applyLipstick",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyLipstick",
            kotlinBinding = "MeituNativeEngine.nativeApplyLipstick",
            uiToolId = "tool_lip_matte",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_09",
            featureName = "Lipstick Gloss",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "NoseMouthBeardEngine::applyLipstick",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyLipstick",
            kotlinBinding = "MeituNativeEngine.nativeApplyLipstick",
            uiToolId = "tool_lip_gloss",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_10",
            featureName = "Lipstick Velvet",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "NoseMouthBeardEngine::applyLipstick",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyLipstick",
            kotlinBinding = "MeituNativeEngine.nativeApplyLipstick",
            uiToolId = "tool_lip_velvet",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_11",
            featureName = "Lipstick Metallic",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "NoseMouthBeardEngine::applyLipstick",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyLipstick",
            kotlinBinding = "MeituNativeEngine.nativeApplyLipstick",
            uiToolId = "tool_lip_metallic",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_05",
            moduleName = "Mouth_Lips",
            featureId = "LIP_12",
            featureName = "Lipstick Water Light",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "NoseMouthBeardEngine::applyLipstick",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyLipstick",
            kotlinBinding = "MeituNativeEngine.nativeApplyLipstick",
            uiToolId = "tool_lip_water",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_06",
            moduleName = "Teeth",
            featureId = "TEETH_01",
            featureName = "Teeth Whitening",
            testabilityClass = TestabilityClass.CLASS_D_UNCHANGED_REGION_AND_ROI_PRESERVATION,
            cppSymbol = "TeethEarEngine::applyTeethWhitening",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyTeethWhitening",
            kotlinBinding = "MeituNativeEngine.nativeApplyTeethWhitening",
            uiToolId = "tool_teeth_whiten",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_06",
            moduleName = "Teeth",
            featureId = "TEETH_02",
            featureName = "Teeth Align (JNI Exists, UI Bypassed)",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "TeethEarEngine::applyTeethReshape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyTeethReshape",
            kotlinBinding = "MeituNativeEngine.nativeApplyTeethReshape",
            uiToolId = "tool_teeth_align",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_06",
            moduleName = "Teeth",
            featureId = "TEETH_03",
            featureName = "Teeth Protrusion (JNI Exists, UI Bypassed)",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "TeethEarEngine::applyTeethReshape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyTeethReshape",
            kotlinBinding = "MeituNativeEngine.nativeApplyTeethReshape",
            uiToolId = "tool_teeth_protrusion",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_06",
            moduleName = "Teeth",
            featureId = "TEETH_04",
            featureName = "Teeth Gap Reduction",
            testabilityClass = TestabilityClass.CLASS_B_LANDMARK_AND_GEOMETRIC_BOUNDS,
            cppSymbol = "TeethEarEngine::applyTeethReshape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyTeethReshape",
            kotlinBinding = "MeituNativeEngine.nativeApplyTeethReshape",
            uiToolId = "NONE",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "MOUTH_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_07",
            moduleName = "Ears",
            featureId = "EAR_01",
            featureName = "Ear Buddha Shape",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "TeethEarEngine::applyEarStyle",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEarStyle",
            kotlinBinding = "MeituNativeEngine.nativeApplyEarStyle",
            uiToolId = "tool_ear_buddha",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EAR_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_07",
            moduleName = "Ears",
            featureId = "EAR_02",
            featureName = "Ear Mouse Shape",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "TeethEarEngine::applyEarStyle",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEarStyle",
            kotlinBinding = "MeituNativeEngine.nativeApplyEarStyle",
            uiToolId = "tool_ear_mouse",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EAR_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_07",
            moduleName = "Ears",
            featureId = "EAR_03",
            featureName = "Ear Pig Shape",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "TeethEarEngine::applyEarStyle",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEarStyle",
            kotlinBinding = "MeituNativeEngine.nativeApplyEarStyle",
            uiToolId = "tool_ear_pig",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EAR_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_07",
            moduleName = "Ears",
            featureId = "EAR_04",
            featureName = "Ear Elf Shape",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "TeethEarEngine::applyEarStyle",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEarStyle",
            kotlinBinding = "MeituNativeEngine.nativeApplyEarStyle",
            uiToolId = "tool_ear_elf",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EAR_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_07",
            moduleName = "Ears",
            featureId = "EAR_05",
            featureName = "Ear Press / Flatten",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "TeethEarEngine::applyEarStyle",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEarStyle",
            kotlinBinding = "MeituNativeEngine.nativeApplyEarStyle",
            uiToolId = "tool_ear_press",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "EAR_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_07",
            moduleName = "Ears",
            featureId = "EAR_06",
            featureName = "Ear Protrude / Fan",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "TeethEarEngine::applyEarStyle",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEarStyle",
            kotlinBinding = "MeituNativeEngine.nativeApplyEarStyle",
            uiToolId = "tool_ear_protrude",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "EAR_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_07",
            moduleName = "Ears",
            featureId = "EAR_07",
            featureName = "Ear Lobe Thickness",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "TeethEarEngine::applyEarStyle",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEarStyle",
            kotlinBinding = "MeituNativeEngine.nativeApplyEarStyle",
            uiToolId = "tool_ear_thickness",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EAR_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_07",
            moduleName = "Ears",
            featureId = "EAR_08",
            featureName = "Ear Rosy Tint",
            testabilityClass = TestabilityClass.CLASS_D_UNCHANGED_REGION_AND_ROI_PRESERVATION,
            cppSymbol = "TeethEarEngine::applyEarStyle",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyEarStyle",
            kotlinBinding = "MeituNativeEngine.nativeApplyEarStyle",
            uiToolId = "tool_ear_rosy",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "EAR_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_08",
            moduleName = "Beard",
            featureId = "BEARD_01",
            featureName = "Beard Density",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "NoseMouthBeardEngine::applyBeardEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyBeardEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyBeardEdit",
            uiToolId = "tool_beard_density",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_08",
            moduleName = "Beard",
            featureId = "BEARD_02",
            featureName = "Beard Color / Darken",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "NoseMouthBeardEngine::applyBeardEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyBeardEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyBeardEdit",
            uiToolId = "tool_beard_color",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_08",
            moduleName = "Beard",
            featureId = "BEARD_03",
            featureName = "Mustache Style",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "NoseMouthBeardEngine::applyBeardEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyBeardEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyBeardEdit",
            uiToolId = "tool_beard_mustache",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_08",
            moduleName = "Beard",
            featureId = "BEARD_04",
            featureName = "Goatee Style",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "NoseMouthBeardEngine::applyBeardEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyBeardEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyBeardEdit",
            uiToolId = "tool_beard_goatee",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_08",
            moduleName = "Beard",
            featureId = "BEARD_05",
            featureName = "Full Beard Style",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "NoseMouthBeardEngine::applyBeardEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyBeardEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyBeardEdit",
            uiToolId = "tool_beard_full",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_08",
            moduleName = "Beard",
            featureId = "BEARD_06",
            featureName = "Stubble Beard Style",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "NoseMouthBeardEngine::applyBeardEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyBeardEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyBeardEdit",
            uiToolId = "tool_beard_stubble",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_08",
            moduleName = "Beard",
            featureId = "BEARD_07",
            featureName = "Beard Gray-Away",
            testabilityClass = TestabilityClass.CLASS_D_UNCHANGED_REGION_AND_ROI_PRESERVATION,
            cppSymbol = "NoseMouthBeardEngine::applyBeardEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyBeardEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyBeardEdit",
            uiToolId = "tool_beard_gray_away",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_09",
            moduleName = "Cheeks_Blush",
            featureId = "CHEEK_01",
            featureName = "Cheekbone Reduce",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "FaceReshapeEngine::applyFaceReshape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyFaceReshape",
            kotlinBinding = "MeituNativeEngine.nativeApplyFaceReshape",
            uiToolId = "tool_cheekbone_reduce",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_09",
            moduleName = "Cheeks_Blush",
            featureId = "CHEEK_02",
            featureName = "Cheekbone Lift",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "FaceReshapeEngine::applyFaceReshape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyFaceReshape",
            kotlinBinding = "MeituNativeEngine.nativeApplyFaceReshape",
            uiToolId = "tool_cheekbone_lift",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_09",
            moduleName = "Cheeks_Blush",
            featureId = "CHEEK_03",
            featureName = "Cheekbone Width",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "FaceReshapeEngine::applyFaceReshape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyFaceReshape",
            kotlinBinding = "MeituNativeEngine.nativeApplyFaceReshape",
            uiToolId = "tool_cheekbone_width",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_09",
            moduleName = "Cheeks_Blush",
            featureId = "CHEEK_04",
            featureName = "Blush Matte",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "MakeupEngine::applyBlush",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyBlush",
            kotlinBinding = "MeituNativeEngine.nativeApplyBlush",
            uiToolId = "tool_blush_matte",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_09",
            moduleName = "Cheeks_Blush",
            featureId = "CHEEK_05",
            featureName = "Blush Dewy",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "MakeupEngine::applyBlush",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyBlush",
            kotlinBinding = "MeituNativeEngine.nativeApplyBlush",
            uiToolId = "tool_blush_dewy",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_09",
            moduleName = "Cheeks_Blush",
            featureId = "CHEEK_06",
            featureName = "Blush Contour",
            testabilityClass = TestabilityClass.CLASS_C_DISCRETE_PRESET_AND_COLOR_PALETTE,
            cppSymbol = "MakeupEngine::applyBlush",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyBlush",
            kotlinBinding = "MeituNativeEngine.nativeApplyBlush",
            uiToolId = "tool_blush_contour",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_01",
            featureName = "Skin Smoothing (Bilateral/Guided)",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "SkinRetouchEngine::applySkinSmooth",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplySkinSmooth",
            kotlinBinding = "MeituNativeEngine.nativeApplySkinSmooth",
            uiToolId = "tool_skin_smooth",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_02",
            featureName = "Skin Whitening / Brightening",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "SkinRetouchEngine::applySkinWhiten",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplySkinWhiten",
            kotlinBinding = "MeituNativeEngine.nativeApplySkinWhiten",
            uiToolId = "tool_skin_whiten",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_03",
            featureName = "Skin Tone Color Adjustment",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "SkinRetouchEngine::applySkinTone",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplySkinTone",
            kotlinBinding = "MeituNativeEngine.nativeApplySkinTone",
            uiToolId = "tool_skin_tone",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_04",
            featureName = "Acne Removal (Auto Blob/DoG)",
            testabilityClass = TestabilityClass.CLASS_B_LANDMARK_AND_GEOMETRIC_BOUNDS,
            cppSymbol = "SkinRetouchEngine::applyAcneRemoval",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyAcneRemoval",
            kotlinBinding = "MeituNativeEngine.nativeApplyAcneRemoval",
            uiToolId = "tool_skin_acne_auto",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_05",
            featureName = "Acne Removal (Manual Tap)",
            testabilityClass = TestabilityClass.CLASS_D_UNCHANGED_REGION_AND_ROI_PRESERVATION,
            cppSymbol = "SkinRetouchEngine::applyAcneManual",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyAcneManual",
            kotlinBinding = "MeituNativeEngine.nativeApplyAcneManual",
            uiToolId = "tool_skin_acne_manual",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_06",
            featureName = "Pore Minimizer",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "SkinRetouchEngine::applyPoreMinimizer",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyPoreMinimizer",
            kotlinBinding = "MeituNativeEngine.nativeApplyPoreMinimizer",
            uiToolId = "tool_skin_pore_minimize",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_07",
            featureName = "Oil Control / Matte Skin",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "SkinRetouchEngine::applyOilControl",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyOilControl",
            kotlinBinding = "MeituNativeEngine.nativeApplyOilControl",
            uiToolId = "tool_skin_matte_oil",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_08",
            featureName = "Micro-pore Texture Preservation",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "SkinRetouchEngine::applyTexturePreserve",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyTexturePreserve",
            kotlinBinding = "MeituNativeEngine.nativeApplyTexturePreserve",
            uiToolId = "tool_skin_texture_preserve",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_09",
            featureName = "Forehead Wrinkle Removal",
            testabilityClass = TestabilityClass.CLASS_D_UNCHANGED_REGION_AND_ROI_PRESERVATION,
            cppSymbol = "SkinRetouchEngine::applyWrinkleRemoval",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyWrinkleRemoval",
            kotlinBinding = "MeituNativeEngine.nativeApplyWrinkleRemoval",
            uiToolId = "tool_skin_wrinkle_forehead",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_10",
            featureName = "Nasolabial Fold Wrinkle Removal",
            testabilityClass = TestabilityClass.CLASS_D_UNCHANGED_REGION_AND_ROI_PRESERVATION,
            cppSymbol = "SkinRetouchEngine::applyWrinkleRemoval",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyWrinkleRemoval",
            kotlinBinding = "MeituNativeEngine.nativeApplyWrinkleRemoval",
            uiToolId = "tool_skin_wrinkle_nasolabial",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_10",
            moduleName = "Skin",
            featureId = "SKIN_11",
            featureName = "Neck Wrinkle Removal",
            testabilityClass = TestabilityClass.CLASS_D_UNCHANGED_REGION_AND_ROI_PRESERVATION,
            cppSymbol = "SkinRetouchEngine::applyWrinkleRemoval",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyWrinkleRemoval",
            kotlinBinding = "MeituNativeEngine.nativeApplyWrinkleRemoval",
            uiToolId = "tool_skin_wrinkle_neck",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_11",
            moduleName = "Jaw_Chin_3DMM",
            featureId = "CONTOUR_01",
            featureName = "Face Contour Slimming",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "FaceReshapeEngine::applyFaceReshape",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyFaceReshape",
            kotlinBinding = "MeituNativeEngine.nativeApplyFaceReshape",
            uiToolId = "tool_face_contour_slim",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_11",
            moduleName = "Jaw_Chin_3DMM",
            featureId = "CONTOUR_02",
            featureName = "Jaw Width Adjustment",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "FaceReshapeEngine::applyJawEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyJawEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyJawEdit",
            uiToolId = "tool_face_jaw_width",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_11",
            moduleName = "Jaw_Chin_3DMM",
            featureId = "CONTOUR_03",
            featureName = "Chin Length Adjustment",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "FaceReshapeEngine::applyChinEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyChinEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyChinEdit",
            uiToolId = "tool_face_chin_length",
            sliderMin = -100f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = -1.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_11",
            moduleName = "Jaw_Chin_3DMM",
            featureId = "CONTOUR_04",
            featureName = "Chin Pointed / V-Line",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "FaceReshapeEngine::applyChinEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyChinEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyChinEdit",
            uiToolId = "tool_face_chin_pointed",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_11",
            moduleName = "Jaw_Chin_3DMM",
            featureId = "CONTOUR_05",
            featureName = "Temple Fill / Widen",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "FaceReshapeEngine::applyTempleEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyTempleEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyTempleEdit",
            uiToolId = "tool_face_temple_fill",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_11",
            moduleName = "Jaw_Chin_3DMM",
            featureId = "CONTOUR_06",
            featureName = "Forehead Lift",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "FaceReshapeEngine::applyForeheadEdit",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyForeheadEdit",
            kotlinBinding = "MeituNativeEngine.nativeApplyForeheadEdit",
            uiToolId = "tool_face_forehead_lift",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_11",
            moduleName = "Jaw_Chin_3DMM",
            featureId = "CONTOUR_07",
            featureName = "3DMM Mesh Fitting",
            testabilityClass = TestabilityClass.CLASS_B_LANDMARK_AND_GEOMETRIC_BOUNDS,
            cppSymbol = "FaceReshape3DMMEngine::fit3DMM",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeFit3DMM",
            kotlinBinding = "MeituNativeEngine.nativeFit3DMM",
            uiToolId = "tool_3dmm_mesh_fit",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_11",
            moduleName = "Jaw_Chin_3DMM",
            featureId = "CONTOUR_08",
            featureName = "3DMM Param Adjust",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "FaceReshape3DMMEngine::apply3DMMParam",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApply3DMMParam",
            kotlinBinding = "MeituNativeEngine.nativeApply3DMMParam",
            uiToolId = "tool_3dmm_param_adjust",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_11",
            moduleName = "Jaw_Chin_3DMM",
            featureId = "CONTOUR_09",
            featureName = "Head Size Scale (Skull)",
            testabilityClass = TestabilityClass.CLASS_A_PARAMETER_CLAMPING_AND_TRANSFORM,
            cppSymbol = "SkullReshapeEngine::applyHeadScale",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyHeadScale",
            kotlinBinding = "MeituNativeEngine.nativeApplyHeadScale",
            uiToolId = "tool_face_head_size",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_12",
            moduleName = "Face_Parsing_Master",
            featureId = "PARSE_01",
            featureName = "106-Point Facial Landmark Detection",
            testabilityClass = TestabilityClass.CLASS_B_LANDMARK_AND_GEOMETRIC_BOUNDS,
            cppSymbol = "LandmarkEngine::detect106",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeDetectLandmarks106",
            kotlinBinding = "MeituNativeEngine.nativeDetectLandmarks106",
            uiToolId = "tool_landmarks_106",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_12",
            moduleName = "Face_Parsing_Master",
            featureId = "PARSE_02",
            featureName = "478-Point Dense Mesh Detection",
            testabilityClass = TestabilityClass.CLASS_B_LANDMARK_AND_GEOMETRIC_BOUNDS,
            cppSymbol = "LandmarkEngine::detect478",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeDetectLandmarks478",
            kotlinBinding = "MeituNativeEngine.nativeDetectLandmarks478",
            uiToolId = "tool_landmarks_478",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_12",
            moduleName = "Face_Parsing_Master",
            featureId = "PARSE_03",
            featureName = "BiSeNet 19-Class Semantic Parsing",
            testabilityClass = TestabilityClass.CLASS_E_PIPELINE_CONTRACT_AND_CRASH_SAFETY,
            cppSymbol = "BiSeNetParsingEngine::segment",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeSegmentFaceBisenet",
            kotlinBinding = "MeituNativeEngine.nativeSegmentFaceBisenet",
            uiToolId = "tool_bisenet_parsing",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_12",
            moduleName = "Face_Parsing_Master",
            featureId = "PARSE_04",
            featureName = "Accessory & Occlusion Detection",
            testabilityClass = TestabilityClass.CLASS_E_PIPELINE_CONTRACT_AND_CRASH_SAFETY,
            cppSymbol = "AccessoryOcclusionEngine::detect",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeDetectAccessories",
            kotlinBinding = "MeituNativeEngine.nativeDetectAccessories",
            uiToolId = "tool_accessory_occlusion",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_12",
            moduleName = "Face_Parsing_Master",
            featureId = "PARSE_05",
            featureName = "Master Beauty Pipeline (Partial)",
            testabilityClass = TestabilityClass.CLASS_E_PIPELINE_CONTRACT_AND_CRASH_SAFETY,
            cppSymbol = "BeautyParameterController::applyBeautyPipeline",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyMasterBeautyPipeline",
            kotlinBinding = "MeituNativeEngine.nativeApplyMasterBeautyPipeline",
            uiToolId = "NONE",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        ),
        FeatureTestDefinition(
            moduleId = "MOD_12",
            moduleName = "Face_Parsing_Master",
            featureId = "PARSE_06",
            featureName = "Full Human Beauty Controller (Partial)",
            testabilityClass = TestabilityClass.CLASS_E_PIPELINE_CONTRACT_AND_CRASH_SAFETY,
            cppSymbol = "FullHumanBeautyController::applyFullHumanPipeline",
            jniFunction = "Java_com_meitu_core_nativeengine_MeituNativeEngine_nativeApplyFullHumanPipeline",
            kotlinBinding = "MeituNativeEngine.nativeApplyFullHumanPipeline",
            uiToolId = "NONE",
            sliderMin = 0f,
            sliderMax = 100f,
            nominalDefault = 0f,
            engineMin = 0.0f,
            engineMax = 1.0f,
            roiTarget = "FACE_SKIN_REGION"
        )
    )

    fun getFeaturesByModule(moduleId: String): List<FeatureTestDefinition> {
        return ALL_104_FEATURES.filter { it.moduleId == moduleId }
    }

    fun getFeaturesByClass(tClass: TestabilityClass): List<FeatureTestDefinition> {
        return ALL_104_FEATURES.filter { it.testabilityClass == tClass }
    }

    // Deterministic Clamping & Transformation Math
    fun clampParameter(rawInput: Float, min: Float, max: Float): Float {
        if (rawInput.isNaN() || rawInput.isInfinite()) return 0.0f
        return rawInput.coerceIn(min, max)
    }

    fun normalizeSliderToEngine(sliderVal: Float, sMin: Float, sMax: Float, eMin: Float, eMax: Float): Float {
        val clamped = clampParameter(sliderVal, sMin, sMax)
        if (sMax == sMin) return eMin
        val t = (clamped - sMin) / (sMax - sMin)
        return eMin + t * (eMax - eMin)
    }

    // Landmark Validation Math
    fun validateLandmark(x: Float, y: Float): Boolean {
        if (x.isNaN() || y.isNaN() || x.isInfinite() || y.isInfinite()) return false
        return x in 0.0f..1.0f && y in 0.0f..1.0f
    }

    fun validateLandmarkArray(coords: FloatArray?, expectedPointCount: Int): Boolean {
        if (coords == null) return false
        if (coords.size != expectedPointCount * 2) return false
        for (i in 0 until expectedPointCount) {
            if (!validateLandmark(coords[i * 2], coords[i * 2 + 1])) return false
        }
        return true
    }

    // Discrete Preset Validation
    fun validateDiscretePresetIndex(presetIndex: Int, validCount: Int): Int {
        if (presetIndex < 0 || presetIndex >= validCount) return 0 // Safe default
        return presetIndex
    }

    // ROI Bounds & Unchanged-Region Non-Interference Math
    data class RectBounds(val left: Int, val top: Int, val right: Int, val bottom: Int)

    fun computeRoiBox(centerX: Float, centerY: Float, radX: Float, radY: Float, width: Int, height: Int): RectBounds {
        val l = ((centerX - radX) * width).toInt().coerceIn(0, width)
        val r = ((centerX + radX) * width).toInt().coerceIn(0, width)
        val t = ((centerY - radY) * height).toInt().coerceIn(0, height)
        val b = ((centerY + radY) * height).toInt().coerceIn(0, height)
        return RectBounds(l, t, r, b)
    }

    fun isPixelInRoi(x: Int, y: Int, bounds: RectBounds): Boolean {
        return x in bounds.left..bounds.right && y in bounds.top..bounds.bottom
    }
}
