// Function: decltype(from_json_array_impl(fp, fp0, nlohmann::json_abi_v3_12_0::detail::priority_tag<3u>{}), fp.get<std::__ndk1::vector<LayerFlowNS::CLFCreativeEffectStickerConfig, std::__ndk1::allocator<LayerFlowNS::CLFCreativeEffectStickerConfig>>::value_type>(), (void)()) nlohmann::json_abi_v3_12_0::detail::from_json<nlohmann::json_abi_v3_12_0::basic_json<std::__ndk1::map, std::__ndk1::vector, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, bool, long, unsigned long, double, std::__ndk1::allocator, nlohmann::json_abi_v3_12_0::adl_serializer, std::__ndk1::vector<unsigned char, std::__ndk1::allocator<unsigned char>>, void>, std::__ndk1::vector<LayerFlowNS::CLFCreativeEffectStickerConfig, std::__ndk1::allocator<LayerFlowNS::CLFCreativeEffectStickerConfig>>, 0>(nlohmann::json_abi_v3_12_0::basic_json<std::__ndk1::map, std::__ndk1::vector, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, bool, long, unsigned long, double, std::__ndk1::allocator, nlohmann::json_abi_v3_12_0::adl_serializer, std::__ndk1::vector<unsigned char, std::__ndk1::allocator<unsigned char>>, void> const&, std::__ndk1::vector<LayerFlowNS::CLFCreativeEffectStickerConfig, std::__ndk1::allocator<LayerFlowNS::CLFCreativeEffectStickerConfig>>&)
// RVA: 0x398a1c, Size: 276 bytes
int64_t _ZN8nlohmann16json_abi_v3_12_06detail9from_jsonINS0_10basic_jsonINSt6__ndk13mapENS4_6vectorENS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEblmdSA_NS0_14adl_serializerENS6_IhNSA_IhEEEEvEENS6_IN11LayerFlowNS30CLFCreativeEffectStickerConfigENSA_ISI_EEEETnNS4_9enable_ifIXaaaaaaaasr27is_constructible_array_typeIT_T0_EE5valuentsr28is_constructible_object_typeISM_SN_EE5valuentsr28is_constructible_string_typeISM_SN_EE5valuentsr3std7is_sameISN_NSM_8binary_tEEE5valuentsr13is_basic_jsonISN_EE5valueEiE4typeELi0EEEDTcmcmcl20from_json_array_implfp_fp0_tlNS1_12priority_tagILj3EEEEEcldtfp_3getINSN_10value_typeEEEcvv_EERKSM_RSN_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    _ZN8nlohmann16json_abi_v3_12_06detail20from_json_array_implINS0_10basic_jsonINSt6__ndk13mapENS4_6vectorENS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEblmdSA_NS0_14adl_serializerENS6_IhNSA_IhEEEEvEENS6_IN11LayerFlowNS30CLFCreativeEffectStickerConfigENSA_ISI_EEEETnNS4_9enable_ifIXsr3std13is_assignableIRT0_SM_EE5valueEiE4typeELi0EEEDTcmcmcldtfp0_7reserveclsr3stdE7declvalINSM_9size_typeEEEEcldtfp_3getINSM_10value_typeEEEcvv_EERKT_SN_NS1_12priority_tagILj1EEE(...); // call internal at 0x398a68
    __cxa_allocate_exception(...); // call PLT API at 0x398a74
    _ZNK8nlohmann16json_abi_v3_12_010basic_jsonINSt6__ndk13mapENS2_6vectorENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEblmdS8_NS0_14adl_serializerENS4_IhNS8_IhEEEEvE9type_nameEv(...); // call internal at 0x398a84
    const char* str = "type must be array, but is ";
    _ZN8nlohmann16json_abi_v3_12_06detail6concatINSt6__ndk112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEJRA28_KcPSA_EEET_DpOT0_(...); // call internal at 0x398a9c
    _ZN8nlohmann16json_abi_v3_12_06detail10type_error6createIPKNS0_10basic_jsonINSt6__ndk13mapENS5_6vectorENS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEblmdSB_NS0_14adl_serializerENS7_IhNSB_IhEEEEvEETnNS5_9enable_ifIXsr21is_basic_json_contextIT_EE5valueEiE4typeELi0EEES2_iRKSD_SL_(...); // call internal at 0x398ab4
    __cxa_throw(...); // call PLT API at 0x398ae0
    _ZdlPv(...); // call PLT API at 0x398afc
    __cxa_free_exception(...); // call PLT API at 0x398b10
    sub_526544(...); // call internal at 0x398b28
    __stack_chk_fail(...); // call PLT API at 0x398b2c
}
