// Function: void nlohmann::extended_from_json<std::__ndk1::vector<std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::vector<int, std::__ndk1::allocator<int>>, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, std::__ndk1::vector<int, std::__ndk1::allocator<int>>>>>, std::__ndk1::allocator<std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::vector<int, std::__ndk1::allocator<int>>, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, std::__ndk1::vector<int, std::__ndk1::allocator<int>>>>>>>>(nlohmann::json_abi_v3_12_0::basic_json<std::__ndk1::map, std::__ndk1::vector, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, bool, long, unsigned long, double, std::__ndk1::allocator, nlohmann::json_abi_v3_12_0::adl_serializer, std::__ndk1::vector<unsigned char, std::__ndk1::allocator<unsigned char>>, void> const&, char const*, std::__ndk1::vector<std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::vector<int, std::__ndk1::allocator<int>>, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, std::__ndk1::vector<int, std::__ndk1::allocator<int>>>>>, std::__ndk1::allocator<std::__ndk1::map<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, std::__ndk1::vector<int, std::__ndk1::allocator<int>>, std::__ndk1::less<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>>, std::__ndk1::allocator<std::__ndk1::pair<std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const, std::__ndk1::vector<int, std::__ndk1::allocator<int>>>>>>>&)
// RVA: 0x377fa8, Size: 540 bytes
int64_t _ZN8nlohmann18extended_from_jsonINSt6__ndk16vectorINS1_3mapINS1_12basic_stringIcNS1_11char_traitsIcEENS1_9allocatorIcEEEENS2_IiNS7_IiEEEENS1_4lessIS9_EENS7_INS1_4pairIKS9_SB_EEEEEENS7_ISI_EEEEEEvRKNS_16json_abi_v3_12_010basic_jsonIS3_S2_S9_blmdS7_NSL_14adl_serializerENS2_IhNS7_IhEEEEvEEPKcRT_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    strlen(...); // call PLT API at 0x377fe0
    _Znwm(...); // call PLT API at 0x378018
    memcpy(...); // call PLT API at 0x378038
    sub_358DE8(...); // call internal at 0x378048
    _ZdlPv(...); // call PLT API at 0x378058
    _ZNSt6__ndk16__treeINS_12__value_typeINS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEN8nlohmann16json_abi_v3_12_010basic_jsonINS_3mapENS_6vectorES7_blmdS5_NS9_14adl_serializerENSC_IhNS5_IhEEEEvEEEENS_19__map_value_compareIS7_SH_NS_4lessIvEELb1EEENS5_ISH_EEE4findIS7_EENS_15__tree_iteratorISH_PNS_11__tree_nodeISH_PvEElEERKT_(...); // call internal at 0x37809c
    _ZNK8nlohmann16json_abi_v3_12_06detail9iter_implIKNS0_10basic_jsonINSt6__ndk13mapENS4_6vectorENS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEblmdSA_NS0_14adl_serializerENS6_IhNSA_IhEEEEvEEEeqISI_TnNS4_9enable_ifIXoosr3std7is_sameIT_SI_EE5valuesr3std7is_sameISL_NS2_ISG_EEEE5valueEDnE4typeELDn0EEEbRKSL_(...); // call internal at 0x378110
    _ZNK8nlohmann16json_abi_v3_12_06detail9iter_implIKNS0_10basic_jsonINSt6__ndk13mapENS4_6vectorENS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEblmdSA_NS0_14adl_serializerENS6_IhNSA_IhEEEEvEEEptEv(...); // call internal at 0x37811c
    _ZN8nlohmann16json_abi_v3_12_06detail9from_jsonINS0_10basic_jsonINSt6__ndk13mapENS4_6vectorENS4_12basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEblmdSA_NS0_14adl_serializerENS6_IhNSA_IhEEEEvEENS6_INS5_ISC_NS6_IiNSA_IiEEEENS4_4lessISC_EENSA_INS4_4pairIKSC_SI_EEEEEENSA_ISP_EEEETnNS4_9enable_ifIXaaaaaaaasr27is_constructible_array_typeIT_T0_EE5valuentsr28is_constructible_object_typeIST_SU_EE5valuentsr28is_constructible_string_typeIST_SU_EE5valuentsr3std7is_sameISU_NST_8binary_tEEE5valuentsr13is_basic_jsonISU_EE5valueEiE4typeELi0EEEDTcmcmcl20from_json_array_implfp_fp0_tlNS1_12priority_tagILj3EEEEEcldtfp_3getINSU_10value_typeEEEcvv_EERKST_RSU_(...); // call internal at 0x378124
    _ZdlPv(...); // call PLT API at 0x378134
    return a0;
    sub_2BC2E0(...); // call internal at 0x378178
    _ZdlPv(...); // call PLT API at 0x3781a4
    sub_526544(...); // call internal at 0x3781bc
    __stack_chk_fail(...); // call PLT API at 0x3781c0
}
