// Function: std::__ndk1::__hash_const_iterator<std::__ndk1::__hash_node<std::__ndk1::__hash_value_type<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>, std::__ndk1::tuple<bool, bool, MTImageKitNS::CMTIKEditRotateType_T>>, void*>*> std::__ndk1::__hash_table<std::__ndk1::__hash_value_type<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>, std::__ndk1::tuple<bool, bool, MTImageKitNS::CMTIKEditRotateType_T>>, std::__ndk1::__unordered_map_hasher<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>, std::__ndk1::__hash_value_type<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>, std::__ndk1::tuple<bool, bool, MTImageKitNS::CMTIKEditRotateType_T>>, std::__ndk1::hash<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>>, std::__ndk1::equal_to<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>>, true>, std::__ndk1::__unordered_map_equal<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>, std::__ndk1::__hash_value_type<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>, std::__ndk1::tuple<bool, bool, MTImageKitNS::CMTIKEditRotateType_T>>, std::__ndk1::equal_to<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>>, std::__ndk1::hash<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>>, true>, std::__ndk1::allocator<std::__ndk1::__hash_value_type<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>, std::__ndk1::tuple<bool, bool, MTImageKitNS::CMTIKEditRotateType_T>>>>::find<std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>>>(std::__ndk1::basic_string_view<char, std::__ndk1::char_traits<char>> const&) const
// RVA: 0x348ecc, Size: 384 bytes
int64_t _ZNKSt6__ndk112__hash_tableINS_17__hash_value_typeINS_17basic_string_viewIcNS_11char_traitsIcEEEENS_5tupleIJbbN12MTImageKitNS21CMTIKEditRotateType_TEEEEEENS_22__unordered_map_hasherIS5_SA_NS_4hashIS5_EENS_8equal_toIS5_EELb1EEENS_21__unordered_map_equalIS5_SA_SF_SD_Lb1EEENS_9allocatorISA_EEE4findIS5_EENS_21__hash_const_iteratorIPNS_11__hash_nodeISA_PvEEEERKT_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    sub_3488A8(...); // call internal at 0x348f08
    memcmp(...); // call PLT API at 0x348fac
    memcmp(...); // call PLT API at 0x349004
    return a0;
    __stack_chk_fail(...); // call PLT API at 0x349044
    sub_2BF8C4(...); // call internal at 0x349048
}
