// Function: void std::__ndk1::__tree<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, std::__ndk1::__map_value_compare<int, std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, std::__ndk1::less<int>, true>, std::__ndk1::allocator<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>>>::__assign_multi<std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, void*>*, long>>(std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, void*>*, long>, std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, void*>*, long>)
// RVA: 0x2f8d94, Size: 988 bytes
int64_t _ZNSt6__ndk16__treeINS_12__value_typeIiNS_6vectorINS_4pairIN12MTImageKitNS5_Vec2IfEEfEENS_9allocatorIS7_EEEEEENS_19__map_value_compareIiSB_NS_4lessIiEELb1EEENS8_ISB_EEE14__assign_multiINS_21__tree_const_iteratorISB_PNS_11__tree_nodeISB_PvEElEEEEvT_SP_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    _ZNSt6__ndk16vectorINS_4pairIN12MTImageKitNS5_Vec2IfEEfEENS_9allocatorIS5_EEE18__assign_with_sizeB8ne180000IPS5_SA_EEvT_T0_l(...); // call internal at 0x2f8ea0
    sub_2BC34C(...); // call internal at 0x2f8f08
    sub_2BDB7C(...); // call internal at 0x2f8ff0
    sub_2BDB7C(...); // call internal at 0x2f9004
    sub_2BDB7C(...); // call internal at 0x2f9028
    _ZNSt6__ndk16__treeINS_12__value_typeIiNS_6vectorINS_4pairIN12MTImageKitNS5_Vec2IfEEfEENS_9allocatorIS7_EEEEEENS_19__map_value_compareIiSB_NS_4lessIiEELb1EEENS8_ISB_EEE16__construct_nodeIJRKNS3_IKiSA_EEEEENS_10unique_ptrINS_11__tree_nodeISB_PvEENS_22__tree_node_destructorINS8_ISQ_EEEEEEDpOT_(...); // call internal at 0x2f9054
    sub_2BC34C(...); // call internal at 0x2f90bc
    return a0;
    sub_2F9170(...); // call internal at 0x2f9150
    sub_526544(...); // call internal at 0x2f9168
    __stack_chk_fail(...); // call PLT API at 0x2f916c
}
