// Function: decltype(auto) std::__ndk1::__variant_detail::__visitation::__base::__dispatcher<2ul, 2ul>::__dispatch[abi:ne180000]<void std::__ndk1::__variant_detail::__assignment<std::__ndk1::__variant_detail::__traits<LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>>::__generic_assign[abi:ne180000]<std::__ndk1::__variant_detail::__copy_assignment<std::__ndk1::__variant_detail::__traits<LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>, (std::__ndk1::__variant_detail::_Trait)1> const&>(std::__ndk1::__variant_detail::__copy_assignment<std::__ndk1::__variant_detail::__traits<LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>, (std::__ndk1::__variant_detail::_Trait)1> const&)::'lambda'(std::__ndk1::__variant_detail::__copy_assignment<std::__ndk1::__variant_detail::__traits<LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>, (std::__ndk1::__variant_detail::_Trait)1> const&, auto&&)&&, std::__ndk1::__variant_detail::__base<(std::__ndk1::__variant_detail::_Trait)1, LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>&, std::__ndk1::__variant_detail::__base<(std::__ndk1::__variant_detail::_Trait)1, LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont> const&>(std::__ndk1::__variant_detail::__copy_assignment<std::__ndk1::__variant_detail::__traits<LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>, (std::__ndk1::__variant_detail::_Trait)1> const&, std::__ndk1::__variant_detail::__base<(std::__ndk1::__variant_detail::_Trait)1, LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>&, std::__ndk1::__variant_detail::__base<(std::__ndk1::__variant_detail::_Trait)1, LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont> const&)
// RVA: 0x451b50, Size: 144 bytes
int64_t _ZNSt6__ndk116__variant_detail12__visitation6__base12__dispatcherIJLm2ELm2EEE10__dispatchB8ne180000IOZNS0_12__assignmentINS0_8__traitsIJN11LayerFlowNS15CLFHttpResourceENS8_18CLFFormulaMaterialENS8_14CLFFormulaFontEEEEE16__generic_assignB8ne180000IRKNS0_17__copy_assignmentISC_LNS0_6_TraitE1EEEEEvOT_EUlRSK_OT0_E_JRNS0_6__baseILSG_1EJS9_SA_SB_EEERKSS_EEEDcSK_DpT0_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    _ZNSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEaSERKS5_(...); // call PLT API at 0x451b90
    _ZNSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEaSERKS5_(...); // call PLT API at 0x451b9c
    sub_451DF0(...); // call internal at 0x451bb4
    return a0;
    __stack_chk_fail(...); // call PLT API at 0x451bdc
}
