// Function: decltype(auto) std::__ndk1::__variant_detail::__visitation::__base::__dispatcher<1ul, 1ul>::__dispatch[abi:ne180000]<void std::__ndk1::__variant_detail::__assignment<std::__ndk1::__variant_detail::__traits<LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>>::__generic_assign[abi:ne180000]<std::__ndk1::__variant_detail::__copy_assignment<std::__ndk1::__variant_detail::__traits<LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>, (std::__ndk1::__variant_detail::_Trait)1> const&>(std::__ndk1::__variant_detail::__copy_assignment<std::__ndk1::__variant_detail::__traits<LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>, (std::__ndk1::__variant_detail::_Trait)1> const&)::'lambda'(std::__ndk1::__variant_detail::__copy_assignment<std::__ndk1::__variant_detail::__traits<LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>, (std::__ndk1::__variant_detail::_Trait)1> const&, auto&&)&&, std::__ndk1::__variant_detail::__base<(std::__ndk1::__variant_detail::_Trait)1, LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>&, std::__ndk1::__variant_detail::__base<(std::__ndk1::__variant_detail::_Trait)1, LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont> const&>(std::__ndk1::__variant_detail::__copy_assignment<std::__ndk1::__variant_detail::__traits<LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>, (std::__ndk1::__variant_detail::_Trait)1> const&, std::__ndk1::__variant_detail::__base<(std::__ndk1::__variant_detail::_Trait)1, LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont>&, std::__ndk1::__variant_detail::__base<(std::__ndk1::__variant_detail::_Trait)1, LayerFlowNS::CLFHttpResource, LayerFlowNS::CLFFormulaMaterial, LayerFlowNS::CLFFormulaFont> const&)
// RVA: 0x451a98, Size: 184 bytes
int64_t _ZNSt6__ndk116__variant_detail12__visitation6__base12__dispatcherIJLm1ELm1EEE10__dispatchB8ne180000IOZNS0_12__assignmentINS0_8__traitsIJN11LayerFlowNS15CLFHttpResourceENS8_18CLFFormulaMaterialENS8_14CLFFormulaFontEEEEE16__generic_assignB8ne180000IRKNS0_17__copy_assignmentISC_LNS0_6_TraitE1EEEEEvOT_EUlRSK_OT0_E_JRNS0_6__baseILSG_1EJS9_SA_SB_EEERKSS_EEEDcSK_DpT0_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    _ZNSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEaSERKS5_(...); // call PLT API at 0x451ad8
    _ZNSt6__ndk112basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEaSERKS5_(...); // call PLT API at 0x451ae4
    _ZNSt6__ndk123__optional_storage_baseIN11LayerFlowNS20CLFMaterialExtraInfoELb0EE13__assign_fromB8ne180000IRKNS_27__optional_copy_assign_baseIS2_Lb0EEEEEvOT_(...); // call internal at 0x451b18
    sub_451D14(...); // call internal at 0x451b24
    return a0;
    __stack_chk_fail(...); // call PLT API at 0x451b4c
}
