// Function: void std::__ndk1::map<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>, std::__ndk1::less<int>, std::__ndk1::allocator<std::__ndk1::pair<int const, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>>>::insert[abi:ne180000]<std::__ndk1::__map_const_iterator<std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, void*>*, long>>>(std::__ndk1::__map_const_iterator<std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, void*>*, long>>, std::__ndk1::__map_const_iterator<std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::vector<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>, std::__ndk1::allocator<std::__ndk1::pair<MTImageKitNS::_Vec2<float>, float>>>>, void*>*, long>>)
// RVA: 0x2bd740, Size: 284 bytes
int64_t _ZNSt6__ndk13mapIiNS_6vectorINS_4pairIN12MTImageKitNS5_Vec2IfEEfEENS_9allocatorIS6_EEEENS_4lessIiEENS7_INS2_IKiS9_EEEEE6insertB8ne180000INS_20__map_const_iteratorINS_21__tree_const_iteratorINS_12__value_typeIiS9_EEPNS_11__tree_nodeISK_PvEElEEEEEEvT_SR_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    _ZNSt6__ndk16__treeINS_12__value_typeIiNS_6vectorINS_4pairIN12MTImageKitNS5_Vec2IfEEfEENS_9allocatorIS7_EEEEEENS_19__map_value_compareIiSB_NS_4lessIiEELb1EEENS8_ISB_EEE12__find_equalIiEERPNS_16__tree_node_baseIPvEENS_21__tree_const_iteratorISB_PNS_11__tree_nodeISB_SK_EElEERPNS_15__tree_end_nodeISM_EESN_RKT_(...); // call internal at 0x2bd79c
    _ZNSt6__ndk16__treeINS_12__value_typeIiNS_6vectorINS_4pairIN12MTImageKitNS5_Vec2IfEEfEENS_9allocatorIS7_EEEEEENS_19__map_value_compareIiSB_NS_4lessIiEELb1EEENS8_ISB_EEE16__construct_nodeIJRKNS3_IKiSA_EEEEENS_10unique_ptrINS_11__tree_nodeISB_PvEENS_22__tree_node_destructorINS8_ISQ_EEEEEEDpOT_(...); // call internal at 0x2bd7c4
    sub_2BC34C(...); // call internal at 0x2bd7f0
    return a0;
    __stack_chk_fail(...); // call PLT API at 0x2bd858
}
