// Function: void std::__ndk1::map<int, std::__ndk1::vector<float, std::__ndk1::allocator<float>>, std::__ndk1::less<int>, std::__ndk1::allocator<std::__ndk1::pair<int const, std::__ndk1::vector<float, std::__ndk1::allocator<float>>>>>::insert[abi:ne180000]<std::__ndk1::__map_const_iterator<std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::vector<float, std::__ndk1::allocator<float>>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::vector<float, std::__ndk1::allocator<float>>>, void*>*, long>>>(std::__ndk1::__map_const_iterator<std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::vector<float, std::__ndk1::allocator<float>>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::vector<float, std::__ndk1::allocator<float>>>, void*>*, long>>, std::__ndk1::__map_const_iterator<std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::vector<float, std::__ndk1::allocator<float>>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::vector<float, std::__ndk1::allocator<float>>>, void*>*, long>>)
// RVA: 0x2bcfdc, Size: 284 bytes
int64_t _ZNSt6__ndk13mapIiNS_6vectorIfNS_9allocatorIfEEEENS_4lessIiEENS2_INS_4pairIKiS4_EEEEE6insertB8ne180000INS_20__map_const_iteratorINS_21__tree_const_iteratorINS_12__value_typeIiS4_EEPNS_11__tree_nodeISG_PvEElEEEEEEvT_SN_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    _ZNSt6__ndk16__treeINS_12__value_typeIiNS_6vectorIfNS_9allocatorIfEEEEEENS_19__map_value_compareIiS6_NS_4lessIiEELb1EEENS3_IS6_EEE12__find_equalIiEERPNS_16__tree_node_baseIPvEENS_21__tree_const_iteratorIS6_PNS_11__tree_nodeIS6_SF_EElEERPNS_15__tree_end_nodeISH_EESI_RKT_(...); // call internal at 0x2bd038
    _ZNSt6__ndk16__treeINS_12__value_typeIiNS_6vectorIfNS_9allocatorIfEEEEEENS_19__map_value_compareIiS6_NS_4lessIiEELb1EEENS3_IS6_EEE16__construct_nodeIJRKNS_4pairIKiS5_EEEEENS_10unique_ptrINS_11__tree_nodeIS6_PvEENS_22__tree_node_destructorINS3_ISM_EEEEEEDpOT_(...); // call internal at 0x2bd060
    sub_2BC34C(...); // call internal at 0x2bd08c
    return a0;
    __stack_chk_fail(...); // call PLT API at 0x2bd0f4
}
