// Function: void std::__ndk1::__variant_detail::__assignment<std::__ndk1::__variant_detail::__traits<LFOriginModular, LFIdentityPhotoModular, LFPuzzleModular, LFPuzzleFrameModular, LFPuzzleImageModular, LFPuzzleLayoutModular, LFPuzzleFusionModular, LFPuzzleSpliceModular, LFAutoBeautyModular, LFCreativeModular, LFSpecialEffectModular, LFEditModular, LFEnhanceModular, LFCompareModular, LFBgBeautifyModular, LFFilterModular, LFStickerModular, LFLiveStickerModular, LFMarkModular, LFFrameModular, LFTextModular, LFBlurModular, LFAutoBrushModular, LFSkinWhitenModular, LFSkinGlowUpModular, LFOneTapPhotoModular, LFFaceRemoldModular, LFFaceFullModular, LFMakeUpModular, LFMakeupBagModular, LFWakeSkinModular, LFDermabrasionModular, LFMatteModular, LFAkneModular, LFFixTeethModular, LFBodyShapeModular, LFHeadScaleModular, LFWrinkleCleanModular, LFSlimmingModular, LFEyeModular, LFDenseHairModular, LFOneClickBeautyModular, LFAutoMosaicModular, LFAutoColorCorrectModular, LFAutoSlimModular, LFAutoWrinkleCleanModular, LFAutoDermabrasionModular, LFAutoRemoveModular, LFCommonAigcModular>>::__assign_alt[abi:ne180000]<48ul, LFCommonAigcModular, LFCommonAigcModular>(std::__ndk1::__variant_detail::__alt<48ul, LFCommonAigcModular>&, LFCommonAigcModular&&)
// RVA: 0x396cb0, Size: 468 bytes
int64_t _ZNSt6__ndk116__variant_detail12__assignmentINS0_8__traitsIJ15LFOriginModular22LFIdentityPhotoModular15LFPuzzleModular20LFPuzzleFrameModular20LFPuzzleImageModular21LFPuzzleLayoutModular21LFPuzzleFusionModular21LFPuzzleSpliceModular19LFAutoBeautyModular17LFCreativeModular22LFSpecialEffectModular13LFEditModular16LFEnhanceModular16LFCompareModular19LFBgBeautifyModular15LFFilterModular16LFStickerModular20LFLiveStickerModular13LFMarkModular14LFFrameModular13LFTextModular13LFBlurModular18LFAutoBrushModular19LFSkinWhitenModular19LFSkinGlowUpModular20LFOneTapPhotoModular19LFFaceRemoldModular17LFFaceFullModular15LFMakeUpModular18LFMakeupBagModular17LFWakeSkinModular21LFDermabrasionModular14LFMatteModular13LFAkneModular17LFFixTeethModular18LFBodyShapeModular18LFHeadScaleModular21LFWrinkleCleanModular17LFSlimmingModular12LFEyeModular18LFDenseHairModular23LFOneClickBeautyModular19LFAutoMosaicModular25LFAutoColorCorrectModular17LFAutoSlimModular25LFAutoWrinkleCleanModular25LFAutoDermabrasionModular19LFAutoRemoveModular19LFCommonAigcModularEEEE12__assign_altB8ne180000ILm48ES1F_S1F_EEvRNS0_5__altIXT_ET0_EEOT1_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    _ZdlPv(...); // call PLT API at 0x396d08
    sub_38FA8C(...); // call internal at 0x396d28
    _ZN11LayerFlowNS21CLFExtraInfoAiSdkDataaSEOS0_(...); // call internal at 0x396d54
    (*x8)(...);
    return a0;
    __stack_chk_fail(...); // call PLT API at 0x396e7c
    sub_2BF8C4(...); // call internal at 0x396e80
}
