// Function: void std::__ndk1::map<int, std::__ndk1::shared_ptr<LayerFlowNS::LFBody3DEffectRequestResult>, std::__ndk1::less<int>, std::__ndk1::allocator<std::__ndk1::pair<int const, std::__ndk1::shared_ptr<LayerFlowNS::LFBody3DEffectRequestResult>>>>::insert[abi:ne180000]<std::__ndk1::__map_const_iterator<std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::shared_ptr<LayerFlowNS::LFBody3DEffectRequestResult>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::shared_ptr<LayerFlowNS::LFBody3DEffectRequestResult>>, void*>*, long>>>(std::__ndk1::__map_const_iterator<std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::shared_ptr<LayerFlowNS::LFBody3DEffectRequestResult>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::shared_ptr<LayerFlowNS::LFBody3DEffectRequestResult>>, void*>*, long>>, std::__ndk1::__map_const_iterator<std::__ndk1::__tree_const_iterator<std::__ndk1::__value_type<int, std::__ndk1::shared_ptr<LayerFlowNS::LFBody3DEffectRequestResult>>, std::__ndk1::__tree_node<std::__ndk1::__value_type<int, std::__ndk1::shared_ptr<LayerFlowNS::LFBody3DEffectRequestResult>>, void*>*, long>>)
// RVA: 0x33b18c, Size: 316 bytes
int64_t _ZNSt6__ndk13mapIiNS_10shared_ptrIN11LayerFlowNS27LFBody3DEffectRequestResultEEENS_4lessIiEENS_9allocatorINS_4pairIKiS4_EEEEE6insertB8ne180000INS_20__map_const_iteratorINS_21__tree_const_iteratorINS_12__value_typeIiS4_EEPNS_11__tree_nodeISH_PvEElEEEEEEvT_SO_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    _ZNSt6__ndk16__treeINS_12__value_typeIiNS_10shared_ptrIN11LayerFlowNS27LFBody3DEffectRequestResultEEEEENS_19__map_value_compareIiS6_NS_4lessIiEELb1EEENS_9allocatorIS6_EEE12__find_equalIiEERPNS_16__tree_node_baseIPvEENS_21__tree_const_iteratorIS6_PNS_11__tree_nodeIS6_SG_EElEERPNS_15__tree_end_nodeISI_EESJ_RKT_(...); // call internal at 0x33b1e8
    _Znwm(...); // call PLT API at 0x33b208
    sub_5263B0(...); // call internal at 0x33b22c
    sub_2BC34C(...); // call internal at 0x33b25c
    return a0;
    __stack_chk_fail(...); // call PLT API at 0x33b2c4
}
