// Function: auto nlohmann::json_abi_v3_12_0::adl_serializer<std::__ndk1::variant<LFOriginModular, LFIdentityPhotoModular, LFPuzzleModular, LFPuzzleFrameModular, LFPuzzleImageModular, LFPuzzleLayoutModular, LFPuzzleFusionModular, LFPuzzleSpliceModular, LFAutoBeautyModular, LFCreativeModular, LFSpecialEffectModular, LFEditModular, LFEnhanceModular, LFCompareModular, LFBgBeautifyModular, LFFilterModular, LFStickerModular, LFLiveStickerModular, LFMarkModular, LFFrameModular, LFTextModular, LFBlurModular, LFAutoBrushModular, LFSkinWhitenModular, LFSkinGlowUpModular, LFOneTapPhotoModular, LFFaceRemoldModular, LFFaceFullModular, LFMakeUpModular, LFMakeupBagModular, LFWakeSkinModular, LFDermabrasionModular, LFMatteModular, LFAkneModular, LFFixTeethModular, LFBodyShapeModular, LFHeadScaleModular, LFWrinkleCleanModular, LFSlimmingModular, LFEyeModular, LFDenseHairModular, LFOneClickBeautyModular, LFAutoMosaicModular, LFAutoColorCorrectModular, LFAutoSlimModular, LFAutoWrinkleCleanModular, LFAutoDermabrasionModular, LFAutoRemoveModular, LFCommonAigcModular>, void>::to_json(nlohmann::json_abi_v3_12_0::basic_json<std::__ndk1::map, std::__ndk1::vector, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>, bool, long, unsigned long, double, std::__ndk1::allocator, nlohmann::json_abi_v3_12_0::adl_serializer, std::__ndk1::vector<unsigned char, std::__ndk1::allocator<unsigned char>>, void>&, std::__ndk1::variant<LFOriginModular, LFIdentityPhotoModular, LFPuzzleModular, LFPuzzleFrameModular, LFPuzzleImageModular, LFPuzzleLayoutModular, LFPuzzleFusionModular, LFPuzzleSpliceModular, LFAutoBeautyModular, LFCreativeModular, LFSpecialEffectModular, LFEditModular, LFEnhanceModular, LFCompareModular, LFBgBeautifyModular, LFFilterModular, LFStickerModular, LFLiveStickerModular, LFMarkModular, LFFrameModular, LFTextModular, LFBlurModular, LFAutoBrushModular, LFSkinWhitenModular, LFSkinGlowUpModular, LFOneTapPhotoModular, LFFaceRemoldModular, LFFaceFullModular, LFMakeUpModular, LFMakeupBagModular, LFWakeSkinModular, LFDermabrasionModular, LFMatteModular, LFAkneModular, LFFixTeethModular, LFBodyShapeModular, LFHeadScaleModular, LFWrinkleCleanModular, LFSlimmingModular, LFEyeModular, LFDenseHairModular, LFOneClickBeautyModular, LFAutoMosaicModular, LFAutoColorCorrectModular, LFAutoSlimModular, LFAutoWrinkleCleanModular, LFAutoDermabrasionModular, LFAutoRemoveModular, LFCommonAigcModular> const&)::'lambda'(auto&&)::operator()<LFCommonAigcModular const&>(auto&&) const
// RVA: 0x319f54, Size: 412 bytes
int64_t _ZZN8nlohmann16json_abi_v3_12_014adl_serializerINSt6__ndk17variantIJ15LFOriginModular22LFIdentityPhotoModular15LFPuzzleModular20LFPuzzleFrameModular20LFPuzzleImageModular21LFPuzzleLayoutModular21LFPuzzleFusionModular21LFPuzzleSpliceModular19LFAutoBeautyModular17LFCreativeModular22LFSpecialEffectModular13LFEditModular16LFEnhanceModular16LFCompareModular19LFBgBeautifyModular15LFFilterModular16LFStickerModular20LFLiveStickerModular13LFMarkModular14LFFrameModular13LFTextModular13LFBlurModular18LFAutoBrushModular19LFSkinWhitenModular19LFSkinGlowUpModular20LFOneTapPhotoModular19LFFaceRemoldModular17LFFaceFullModular15LFMakeUpModular18LFMakeupBagModular17LFWakeSkinModular21LFDermabrasionModular14LFMatteModular13LFAkneModular17LFFixTeethModular18LFBodyShapeModular18LFHeadScaleModular21LFWrinkleCleanModular17LFSlimmingModular12LFEyeModular18LFDenseHairModular23LFOneClickBeautyModular19LFAutoMosaicModular25LFAutoColorCorrectModular17LFAutoSlimModular25LFAutoWrinkleCleanModular25LFAutoDermabrasionModular19LFAutoRemoveModular19LFCommonAigcModularEEEvE7to_jsonERNS0_10basic_jsonINS2_3mapENS2_6vectorENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEblmdS1P_S1_NS1L_IhNS1P_IhEEEEvEERKS1H_ENKUlOT_E_clIRKS1G_EEDaS1Z_(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    const char* str = "enable";
    _ZN8nlohmann16extended_to_jsonIbEEvRNS_16json_abi_v3_12_010basic_jsonINSt6__ndk13mapENS3_6vectorENS3_12basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEblmdS9_NS1_14adl_serializerENS5_IhNS9_IhEEEEvEEPKcRKT_(...); // call internal at 0x319f90
    const char* str = "mediaInfoList";
    _ZN8nlohmann16extended_to_jsonINSt6__ndk16vectorI21CLFExtraInfoMediaInfoNS1_9allocatorIS3_EEEEEEvRNS_16json_abi_v3_12_010basic_jsonINS1_3mapES2_NS1_12basic_stringIcNS1_11char_traitsIcEENS4_IcEEEEblmdS4_NS7_14adl_serializerENS2_IhNS4_IhEEEEvEEPKcRKT_(...); // call internal at 0x319fa4
    const char* str = "aiSdkData";
    _ZN8nlohmann16extended_to_jsonIN11LayerFlowNS21CLFExtraInfoAiSdkDataEEEvRNS_16json_abi_v3_12_010basic_jsonINSt6__ndk13mapENS5_6vectorENS5_12basic_stringIcNS5_11char_traitsIcEENS5_9allocatorIcEEEEblmdSB_NS3_14adl_serializerENS7_IhNSB_IhEEEEvEEPKcRKT_(...); // call internal at 0x319fbc
    _ZN8nlohmann16json_abi_v3_12_010basic_jsonINSt6__ndk13mapENS2_6vectorENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEblmdS8_NS0_14adl_serializerENS4_IhNS8_IhEEEEvE10json_value7destroyENS0_6detail7value_tE(...); // call internal at 0x319fe8
    _Znwm(...); // call PLT API at 0x319ffc
    sub_2BC260(...); // call internal at 0x31a028
    const char* str = "modular";
    _ZN8nlohmann16json_abi_v3_12_010basic_jsonINSt6__ndk13mapENS2_6vectorENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEblmdS8_NS0_14adl_serializerENS4_IhNS8_IhEEEEvEixIKcEERSE_PT_(...); // call internal at 0x31a03c
    _ZN8nlohmann16json_abi_v3_12_010basic_jsonINSt6__ndk13mapENS2_6vectorENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEblmdS8_NS0_14adl_serializerENS4_IhNS8_IhEEEEvE10json_value7destroyENS0_6detail7value_tE(...); // call internal at 0x31a068
    return a0;
    _ZdlPv(...); // call PLT API at 0x31a098
    sub_2BF8C4(...); // call internal at 0x31a0a4
    _ZN8nlohmann16json_abi_v3_12_010basic_jsonINSt6__ndk13mapENS2_6vectorENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEblmdS8_NS0_14adl_serializerENS4_IhNS8_IhEEEEvED2Ev(...); // call internal at 0x31a0b0
    sub_2BF8C4(...); // call internal at 0x31a0c4
    _ZN8nlohmann16json_abi_v3_12_010basic_jsonINSt6__ndk13mapENS2_6vectorENS2_12basic_stringIcNS2_11char_traitsIcEENS2_9allocatorIcEEEEblmdS8_NS0_14adl_serializerENS4_IhNS8_IhEEEEvE4dataD2Ev(...); // call internal at 0x31a0d0
    sub_526544(...); // call internal at 0x31a0e8
    __stack_chk_fail(...); // call PLT API at 0x31a0ec
}
