// FUNCTION: sub_440298
// LIBRARY: libLayerFlow.so
// RVA: 0x440298 | SIZE: 2240 bytes | SHA256: 6BB950F8D46AA2A40D6E194AB2960D0D1D88904656BF01FD7A57E4DF24095A79
// SEMANTIC_LABEL: HAIR_COLOR_PIPELINE | CONFIDENCE: HIGH_CONFIDENCE
// IMPORTED_APIS: __android_log_print, __android_log_print, __stack_chk_fail
// STRING_XREFS: mtik_, LayerFlow JNI_OnLoad GetEnv error!, mtik_, LFFormulaShop register jni methods error!, mtik_, LFJsonPlugin register jni methods error!, mtik_, LFOutputImagePlugin register jni methods error!, mtik_, LFMaterialDownloadPlugin register jni methods error!, mtik_, LFResourceDownloadPlugin register jni methods error!, mtik_, LFSetLayerPluginJNI register jni methods error!, mtik_, LFSmartActionsPluginJNI register jni methods error!, mtik_, LFMaterialJNI register jni methods error!, mtik_, LFAiModelInfoJNI register jni methods error!, mtik_, LFFontInfoJNI register jni methods error!, mtik_, LFFileInfoJNI register jni methods error!, mtik_, LFBlockingWaitJNI register jni methods error!, mtik_, LFVisionDetectServiceJNI register jni methods error!, mtik_, LFAutoMagicPenResourceDataJNI register jni methods error!, mtik_, LFBgBeautifyAutoColorInfoJNI register jni methods error!, mtik_, LFBlurResourceDataJNI register jni methods error!, mtik_, LFCreativeStickerInfoJNI register jni methods error!, mtik_, LFCreativeAigcResult_JNI register jni methods error!, mtik_, LFNetHeaderJNI register jni methods error!, mtik_, LFStickerLocateStatusJNI register jni methods error!, mtik_, LFFormulaRenderPluginJNI register jni methods error!, mtik_, LFFilterModularJNI register jni methods error!, mtik_, LFBlurModularJNI register jni methods error!, mtik_, LFCreativeModularJNI register jni methods error!, mtik_, LFSpecialEffectModularJNI register jni methods error!, mtik_, LFEditDataJNI register jni methods error!, mtik_, LFEnhanceDataJNI register jni methods error!, mtik_, LFBgBeautifyModularJNI register jni methods error!, mtik_, LFMarkModularJNI register jni methods error!, mtik_, LFStickerModularJNI register jni methods error!, mtik_, LFLiveStickerModularJNI register jni methods error!, mtik_, LFTextModularJNI register jni methods error!, mtik_, LFAutoBrushDataJNI register jni methods error!, mtik_, LFAutoBeautyModularJNI register jni methods error!, mtik_, LFFrameModularJNI register jni methods error!, mtik_, LFMakeUpModularJNI register jni methods error!, mtik_, LFMakeupRuntimeDataJNI register jni methods error!, mtik_, LFMakeupBagModularJNI register jni methods error!, mtik_, LFSkinWhitenDataJNI register jni methods error!, mtik_, LFFaceFullDataJNI register jni methods error!, mtik_, LFFaceRemoldDataJNI register jni methods error!, mtik_, LFAigcCacheDataJNI register jni methods error!, mtik_, LFImageWithPathJNI register jni methods error!, mtik_, LFStraightLegsAIGCRequestResultJNI register jni methods error!, mtik_, LFBody3DEffectRequestResultJNI register jni methods error!, mtik_, LFEffectAkneDataJNI register jni methods error!, mtik_, LFEffectAutoMosaicDataJNI register jni methods error!, mtik_, LFEffectBodyShapeDataJNI register jni methods error!, mtik_, LFEffectDenseHairDataJNI register jni methods error!, mtik_, LFEffectEyeDataJNI register jni methods error!, mtik_, LFEffectFixTeethDataJNI register jni methods error!, mtik_, LFEffectHeadScaleDataJNI register jni methods error!, mtik_, LFEffectWakeSkinDataJNI register jni methods error!, mtik_, LFEffectWrinkleCleanDataJNI register jni methods error!, mtik_, LFEffectSlimmingDataJNI register jni methods error!, mtik_, LFEffectMatteDataJNI register jni methods error!, mtik_, LFEffectDermabrasionDataJNI register jni methods error!, mtik_, LFEffectOneClickBeautyDataJNI register jni methods error!, mtik_, LFExifInfoJNI register jni methods error!, mtik_, LFAutoColorCorrectDataJNI register jni methods error!, mtik_, LFAutoSlimDataJNI register jni methods error!, mtik_, LFAutoWrinkleCleanDataJNI register jni methods error!, mtik_, LFAutoDermabrasionDataJNI register jni methods error!, JNI_OnLoad LayerFlow.so done. %s compiled at %s %s, 2.5.53.0-mtxx-63, Aug 26 2026, 18:57:58

#include <stdint.h>
#include <jni.h>

// Reconstructed C++ Native Implementation
extern "C" JNIEXPORT void* sub_440298(JNIEnv* env, jobject thiz) {
    // Function entrypoint at 0x440298
    // Call imported API: __android_log_print
    // Call imported API: __android_log_print
    // Call imported API: __stack_chk_fail
    // Literal reference: "mtik_"
    // Literal reference: "LayerFlow JNI_OnLoad GetEnv error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFFormulaShop register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFJsonPlugin register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFOutputImagePlugin register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFMaterialDownloadPlugin register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFResourceDownloadPlugin register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFSetLayerPluginJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFSmartActionsPluginJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFMaterialJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFAiModelInfoJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFFontInfoJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFFileInfoJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFBlockingWaitJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFVisionDetectServiceJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFAutoMagicPenResourceDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFBgBeautifyAutoColorInfoJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFBlurResourceDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFCreativeStickerInfoJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFCreativeAigcResult_JNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFNetHeaderJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFStickerLocateStatusJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFFormulaRenderPluginJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFFilterModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFBlurModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFCreativeModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFSpecialEffectModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEditDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEnhanceDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFBgBeautifyModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFMarkModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFStickerModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFLiveStickerModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFTextModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFAutoBrushDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFAutoBeautyModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFFrameModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFMakeUpModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFMakeupRuntimeDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFMakeupBagModularJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFSkinWhitenDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFFaceFullDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFFaceRemoldDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFAigcCacheDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFImageWithPathJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFStraightLegsAIGCRequestResultJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFBody3DEffectRequestResultJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectAkneDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectAutoMosaicDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectBodyShapeDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectDenseHairDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectEyeDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectFixTeethDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectHeadScaleDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectWakeSkinDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectWrinkleCleanDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectSlimmingDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectMatteDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectDermabrasionDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFEffectOneClickBeautyDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFExifInfoJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFAutoColorCorrectDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFAutoSlimDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFAutoWrinkleCleanDataJNI register jni methods error!"
    // Literal reference: "mtik_"
    // Literal reference: "LFAutoDermabrasionDataJNI register jni methods error!"
    // Literal reference: "JNI_OnLoad LayerFlow.so done. %s compiled at %s %s"
    // Literal reference: "2.5.53.0-mtxx-63"
    // Literal reference: "Aug 26 2026"
    // Literal reference: "18:57:58"
    return (void*)0;
}
