// Function: sub_4FA3C0
// RVA: 0x4fa3c0, Size: 472 bytes
int64_t sub_4FA3C0(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    const char* str = "No Error";
    const char* str = "OpenGL API call";
    return a0;
    const char* str = "No OpenGL support";
    return a0;
    const char* str = "Gpu API call";
    return a0;
    const char* str = "No CUDA support";
    return a0;
    const char* str = "Assertion failed";
    return a0;
    const char* str = "Memory block has been corrupted";
    return a0;
    const char* str = "The function/feature is not implemented";
    return a0;
    const char* str = "Parsing error";
    return a0;
    const char* str = "One of arguments' values is out of range";
    return a0;
    const char* str = "Unsupported format or combination of formats";
    return a0;
    const char* str = "Sizes of input arguments do not match";
    return a0;
    const char* str = "Bad type of mask argument";
    return a0;
    const char* str = "Bad parameter of type CvPoint";
    return a0;
    const char* str = "Bad flag (parameter or structure field)";
    return a0;
    const char* str = "Formats of input arguments do not match";
    return a0;
    const char* str = "Requested object was not found";
    return a0;
    const char* str = "Inplace operation is not supported";
    return a0;
    const char* str = "Division by zero occurred";
    return a0;
    const char* str = "Incorrect size of input array";
    return a0;
    const char* str = "error";
    const char* str = "status";
    sub_4FAA60(...); // call internal at 0x4fa4f4
    return a0;
    const char* str = "Null pointer";
    return a0;
    const char* str = "Input COI is not supported";
    return a0;
    const char* str = "Input image depth is not supported by function";
    return a0;
    const char* str = "Bad number of channels";
    return a0;
    const char* str = "Image step is wrong";
    return a0;
    const char* str = "Autotrace call";
    return a0;
    const char* str = "Iterations do not converge";
    return a0;
    const char* str = "Bad argument";
    return a0;
    const char* str = "Insufficient memory";
    return a0;
    const char* str = "Internal error";
    return a0;
    const char* str = "Unspecified error";
    return a0;
    const char* str = "Backtrace";
    return a0;
}
