// FUNCTION: sub_56b9dc
// LIBRARY: libarkernel3.so
// RVA: 0x56b9dc | SIZE: 4096 bytes | SHA256: 0439BDE8AECEFCE35477E0A05075B46D7AF1467590CA2068EA56DBEF86033234
// SEMANTIC_LABEL: HAIR_COLOR_PIPELINE | CONFIDENCE: HIGH_CONFIDENCE
// IMPORTED_APIS: __stack_chk_fail
// STRING_XREFS: DataRequireKey::SourceGrayImage, DataRequireKey::SourceColorImage, DataRequireKey::SourceImageGPU, DataRequireKey::TouchListener, DataRequireKey::AnimalData, DataRequireKey::FoodData, DataRequireKey::FaceData, DataRequireKey::FaceDataAdditionHead, DataRequireKey::FaceDataAdditionEar, DataRequireKey::FaceDataAdditionNeck, DataRequireKey::FaceDataAdditionMouthMask, DataRequireKey::FaceDataAdditionFaceMask, DataRequireKey::FaceDataAdditionPosEstimator, DataRequireKey::FaceDataAdditionGender, DataRequireKey::FaceDataAdditionAge, DataRequireKey::FaceDataAdditionEyelid, DataRequireKey::FaceDataAdditionEmotion, DataRequireKey::FaceDataAddition3DFA, DataRequireKey::FaceDataAddition3DFAMesh, DataRequireKey::FaceDataAdditionMakeupAdapt, DataRequireKey::Face2DReconstructorV1Data, DataRequireKey::Face2DReconstructorV2Data, DataRequireKey::Face2DReconstructorV3Data, DataRequireKey::Face2DBackgroundReconstructorData, DataRequireKey::Face3DReconstructorData, DataRequireKey::FaceDL3DData, DataRequireKey::FaceDL3DDataAdditionMesh, DataRequireKey::FaceDL3DDataAdditionPosEstimator, DataRequireKey::FaceDL3DDataAdditionBlendShapeFactor, DataRequireKey::FaceDL3DDataAdditionRigging, DataRequireKey::ShoulderData, DataRequireKey::HandData, DataRequireKey::HandDataAdditionPose, DataRequireKey::NailsData, DataRequireKey::BodyMask, DataRequireKey::BodyMaskAdditionCPU, DataRequireKey::BodyMaskAdditionGPU, DataRequireKey::HairMask, DataRequireKey::HairMaskAdditionCPU, DataRequireKey::HairMaskAdditionGPU, DataRequireKey::SkyMask, DataRequireKey::SkyMaskAdditionCPU, DataRequireKey::SkyMaskAdditionGPU, DataRequireKey::SkinMask, DataRequireKey::SkinMaskAdditionCPU, DataRequireKey::SkinMaskAdditionGPU, DataRequireKey::HeadMask, DataRequireKey::HeadMaskAdditionCPU, DataRequireKey::HeadMaskAdditionGPU, DataRequireKey::NevusMask, DataRequireKey::NevusMaskAdditionCPU, DataRequireKey::NevusMaskAdditionGPU, DataRequireKey::FaceContourMask, DataRequireKey::FaceContourMaskAdditionCPU, DataRequireKey::FaceContourMaskAdditionGPU, DataRequireKey::ClothMask, DataRequireKey::ClothMaskAdditionCPU, DataRequireKey::ClothMaskAdditionGPU, DataRequireKey::FaceNeckLineMask, DataRequireKey::FaceNeckLineMaskAdditionCPU, DataRequireKey::FaceNeckLineMaskAdditionGPU, DataRequireKey::EyeMask, DataRequireKey::Body, DataRequireKey::BodyInOne, DataRequireKey::BodyAdditionHuman, DataRequireKey::BodyAdditionJoint, DataRequireKey::BodyAdditionContour, DataRequireKey::BodyAdditionNeck, DataRequireKey::BodyAdditionBreast, DataRequireKey::ARGyroscopeQuaternion, DataRequireKey::ARFaceMesh, DataRequireKey::ARPointCloud, DataRequireKey::ARWorldTracking, DataRequireKey::ARPlaneAnchor, DataRequireKey::ARLightEstimate, DataRequireKey::ARInstantPlacement, DataRequireKey::ARSkeleton, DataRequireKey::CG, DataRequireKey::CGAdditionCPU, DataRequireKey::CGAdditionGPU, DataRequireKey::CompactBeautyData, DataRequireKey::Human3D, DataRequireKey::SpaceDepth, DataRequireKey::SpaceNormal, DataRequireKey::InteractiveMask, DataRequireKey::OutstandingMask, DataRequireKey::MultiInstanceMask, DataRequireKey::UserDefinedMask, DataRequireKey::BodySlim3DAbundantButtocks, DataRequireKey::BodySlim3DThinLowerAbdomens, DataRequireKey::BodySlim3DShoulderBrace, DataRequireKey::BodySlim3DBreastLift, DataRequireKey::BodySlim3DButtLift, DataRequireKey::BodySlim3DAbundantBreasts, DataRequireKey::BodySlim3DBreastReduction, DataRequireKey::BodySlim3DTrapezius, DataRequireKey::BodyBeautyBGFilling

#include <stdint.h>
#include <jni.h>

// Reconstructed C++ Native Implementation
extern "C" JNIEXPORT void* sub_56b9dc(JNIEnv* env, jobject thiz) {
    // Function entrypoint at 0x56b9dc
    // Call imported API: __stack_chk_fail
    // Literal reference: "DataRequireKey::SourceGrayImage"
    // Literal reference: "DataRequireKey::SourceColorImage"
    // Literal reference: "DataRequireKey::SourceImageGPU"
    // Literal reference: "DataRequireKey::TouchListener"
    // Literal reference: "DataRequireKey::AnimalData"
    // Literal reference: "DataRequireKey::FoodData"
    // Literal reference: "DataRequireKey::FaceData"
    // Literal reference: "DataRequireKey::FaceDataAdditionHead"
    // Literal reference: "DataRequireKey::FaceDataAdditionEar"
    // Literal reference: "DataRequireKey::FaceDataAdditionNeck"
    // Literal reference: "DataRequireKey::FaceDataAdditionMouthMask"
    // Literal reference: "DataRequireKey::FaceDataAdditionFaceMask"
    // Literal reference: "DataRequireKey::FaceDataAdditionPosEstimator"
    // Literal reference: "DataRequireKey::FaceDataAdditionGender"
    // Literal reference: "DataRequireKey::FaceDataAdditionAge"
    // Literal reference: "DataRequireKey::FaceDataAdditionEyelid"
    // Literal reference: "DataRequireKey::FaceDataAdditionEmotion"
    // Literal reference: "DataRequireKey::FaceDataAddition3DFA"
    // Literal reference: "DataRequireKey::FaceDataAddition3DFAMesh"
    // Literal reference: "DataRequireKey::FaceDataAdditionMakeupAdapt"
    // Literal reference: "DataRequireKey::Face2DReconstructorV1Data"
    // Literal reference: "DataRequireKey::Face2DReconstructorV2Data"
    // Literal reference: "DataRequireKey::Face2DReconstructorV3Data"
    // Literal reference: "DataRequireKey::Face2DBackgroundReconstructorData"
    // Literal reference: "DataRequireKey::Face3DReconstructorData"
    // Literal reference: "DataRequireKey::FaceDL3DData"
    // Literal reference: "DataRequireKey::FaceDL3DDataAdditionMesh"
    // Literal reference: "DataRequireKey::FaceDL3DDataAdditionPosEstimator"
    // Literal reference: "DataRequireKey::FaceDL3DDataAdditionBlendShapeFactor"
    // Literal reference: "DataRequireKey::FaceDL3DDataAdditionRigging"
    // Literal reference: "DataRequireKey::ShoulderData"
    // Literal reference: "DataRequireKey::HandData"
    // Literal reference: "DataRequireKey::HandDataAdditionPose"
    // Literal reference: "DataRequireKey::NailsData"
    // Literal reference: "DataRequireKey::BodyMask"
    // Literal reference: "DataRequireKey::BodyMaskAdditionCPU"
    // Literal reference: "DataRequireKey::BodyMaskAdditionGPU"
    // Literal reference: "DataRequireKey::HairMask"
    // Literal reference: "DataRequireKey::HairMaskAdditionCPU"
    // Literal reference: "DataRequireKey::HairMaskAdditionGPU"
    // Literal reference: "DataRequireKey::SkyMask"
    // Literal reference: "DataRequireKey::SkyMaskAdditionCPU"
    // Literal reference: "DataRequireKey::SkyMaskAdditionGPU"
    // Literal reference: "DataRequireKey::SkinMask"
    // Literal reference: "DataRequireKey::SkinMaskAdditionCPU"
    // Literal reference: "DataRequireKey::SkinMaskAdditionGPU"
    // Literal reference: "DataRequireKey::HeadMask"
    // Literal reference: "DataRequireKey::HeadMaskAdditionCPU"
    // Literal reference: "DataRequireKey::HeadMaskAdditionGPU"
    // Literal reference: "DataRequireKey::NevusMask"
    // Literal reference: "DataRequireKey::NevusMaskAdditionCPU"
    // Literal reference: "DataRequireKey::NevusMaskAdditionGPU"
    // Literal reference: "DataRequireKey::FaceContourMask"
    // Literal reference: "DataRequireKey::FaceContourMaskAdditionCPU"
    // Literal reference: "DataRequireKey::FaceContourMaskAdditionGPU"
    // Literal reference: "DataRequireKey::ClothMask"
    // Literal reference: "DataRequireKey::ClothMaskAdditionCPU"
    // Literal reference: "DataRequireKey::ClothMaskAdditionGPU"
    // Literal reference: "DataRequireKey::FaceNeckLineMask"
    // Literal reference: "DataRequireKey::FaceNeckLineMaskAdditionCPU"
    // Literal reference: "DataRequireKey::FaceNeckLineMaskAdditionGPU"
    // Literal reference: "DataRequireKey::EyeMask"
    // Literal reference: "DataRequireKey::Body"
    // Literal reference: "DataRequireKey::BodyInOne"
    // Literal reference: "DataRequireKey::BodyAdditionHuman"
    // Literal reference: "DataRequireKey::BodyAdditionJoint"
    // Literal reference: "DataRequireKey::BodyAdditionContour"
    // Literal reference: "DataRequireKey::BodyAdditionNeck"
    // Literal reference: "DataRequireKey::BodyAdditionBreast"
    // Literal reference: "DataRequireKey::ARGyroscopeQuaternion"
    // Literal reference: "DataRequireKey::ARFaceMesh"
    // Literal reference: "DataRequireKey::ARPointCloud"
    // Literal reference: "DataRequireKey::ARWorldTracking"
    // Literal reference: "DataRequireKey::ARPlaneAnchor"
    // Literal reference: "DataRequireKey::ARLightEstimate"
    // Literal reference: "DataRequireKey::ARInstantPlacement"
    // Literal reference: "DataRequireKey::ARSkeleton"
    // Literal reference: "DataRequireKey::CG"
    // Literal reference: "DataRequireKey::CGAdditionCPU"
    // Literal reference: "DataRequireKey::CGAdditionGPU"
    // Literal reference: "DataRequireKey::CompactBeautyData"
    // Literal reference: "DataRequireKey::Human3D"
    // Literal reference: "DataRequireKey::SpaceDepth"
    // Literal reference: "DataRequireKey::SpaceNormal"
    // Literal reference: "DataRequireKey::InteractiveMask"
    // Literal reference: "DataRequireKey::OutstandingMask"
    // Literal reference: "DataRequireKey::MultiInstanceMask"
    // Literal reference: "DataRequireKey::UserDefinedMask"
    // Literal reference: "DataRequireKey::BodySlim3DAbundantButtocks"
    // Literal reference: "DataRequireKey::BodySlim3DThinLowerAbdomens"
    // Literal reference: "DataRequireKey::BodySlim3DShoulderBrace"
    // Literal reference: "DataRequireKey::BodySlim3DBreastLift"
    // Literal reference: "DataRequireKey::BodySlim3DButtLift"
    // Literal reference: "DataRequireKey::BodySlim3DAbundantBreasts"
    // Literal reference: "DataRequireKey::BodySlim3DBreastReduction"
    // Literal reference: "DataRequireKey::BodySlim3DTrapezius"
    // Literal reference: "DataRequireKey::BodyBeautyBGFilling"
    return (void*)0;
}
