// Function: sub_C69318
// RVA: 0xc69318, Size: 2208 bytes
int64_t sub_C69318(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    const char* str = "gl_SemanticsAcquire must not be used with (image) atomic store";
    (*x8)(...);
    (*x8)(...);
    const char* str = "gl_SemanticsRelease must not be used with (image) atomic load";
    (*x8)(...);
    (*x8)(...);
    const char* str = "gl_SemanticsAcquireRelease must not be used with (image) atomic load/store";
    (*x8)(...);
    (*x8)(...);
    const char* str = "Invalid semantics value";
    (*x8)(...);
    (*x8)(...);
    const char* str = "Invalid storage class semantics value";
    (*x8)(...);
    const char* str = "Semantics must include exactly one of gl_SemanticsRelease, gl_SemanticsAcquire, or gl_SemanticsAcquireRelease";
    (*x8)(...);
    const char* str = "Semantics must not include multiple of gl_SemanticsRelease, gl_SemanticsAcquire, or gl_SemanticsAcquireRelease";
    (*x8)(...);
    const char* str = "semUnequal must not include multiple of gl_SemanticsRelease, gl_SemanticsAcquire, or gl_SemanticsAcquireRelease";
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    const char* str = "Storage class semantics must not be zero";
    (*x8)(...);
    (*x8)(...);
    const char* str = "Storage class semantics must not be zero";
    (*x8)(...);
    (*x8)(...);
    const char* str = "semUnequal must not be gl_SemanticsRelease or gl_SemanticsAcquireRelease";
    (*x8)(...);
    (*x8)(...);
    const char* str = "gl_SemanticsMakeAvailable requires gl_SemanticsRelease or gl_SemanticsAcquireRelease";
    (*x8)(...);
    (*x8)(...);
    const char* str = "gl_SemanticsMakeVisible requires gl_SemanticsAcquire or gl_SemanticsAcquireRelease";
    (*x8)(...);
    (*x8)(...);
    const char* str = "gl_SemanticsVolatile must not be used with memoryBarrier or controlBarrier";
    (*x8)(...);
    return a0;
    (*x8)(...);
    const char* str = "semEqual and semUnequal must either both include gl_SemanticsVolatile or neither";
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
    (*x8)(...);
}
