// Function: sub_CA1308
// RVA: 0xca1308, Size: 4096 bytes
int64_t sub_CA1308(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    sub_C9FF14(...); // call internal func at 0xca1344
    void* g_2daeb0 = (void*)0x2daeb0; // global ref
    const char* s_20b87d = "Sequence
"; // string xref
    const char* s_19d164 = "node is still EOpNull!"; // string xref
    sub_C158BC(...); // call internal func at 0xca138c
    const char* s_20b887 = "Scope
"; // string xref
    const char* s_2680b1 = "Function Definition: "; // string xref
    const char* s_24bac9 = "ldexp"; // string xref
    const char* s_1c0c80 = "smoothstep"; // string xref
    const char* s_1d5efb = "min3"; // string xref
    const char* s_1db739 = "max"; // string xref
    const char* s_24c221 = "Function Call: "; // string xref
    sub_C2C594(...); // call internal func at 0xca13e8
    (*x8)(...); // indirect call at 0xca13f8
    sub_C2C6F0(...); // call internal func at 0xca1404
    const char* s_1c0b22 = "subgroupBarrier"; // string xref
    const char* s_252d3d = "Equal"; // string xref
    const char* s_23c76d = "reflect"; // string xref
    const char* s_1c8148 = "fma"; // string xref
    const char* s_1a297d = "min"; // string xref
    const char* s_281819 = "pow"; // string xref
    const char* s_22285b = "arc tangent"; // string xref
    const char* s_28175d = "subgroupPartitionedInclusiveMulNV"; // string xref
    const char* s_1fa5b4 = "face-forward"; // string xref
    const char* s_22bd62 = "interpolateAtOffset"; // string xref
    const char* s_1e49bf = "subgroupShuffleDown"; // string xref
    const char* s_281744 = "subgroupBallotBitExtract"; // string xref
    const char* s_252e17 = "Function Parameters: "; // string xref
    const char* s_23c68f = "subgroupMemoryBarrier"; // string xref
    const char* s_1b3088 = "subgroupPartitionedExclusiveMaxNV"; // string xref
    const char* s_23d06d = "Construct int16_t"; // string xref
    const char* s_211b4a = "Construct int64"; // string xref
    const char* s_1f35c0 = "AtomicCounterMax"; // string xref
    const char* s_1c0a6c = "max3"; // string xref
    const char* s_23d0bb = "AtomicStore"; // string xref
    const char* s_1c8a24 = "Construct float"; // string xref
    const char* s_18f9e9 = "subgroupPartitionedXorNV"; // string xref
    const char* s_1dcf92 = "MemoryBarrierAtomicCounter"; // string xref
    const char* s_21c467 = "AtomicCounterXor"; // string xref
    const char* s_1e519b = "swizzleInvocations"; // string xref
    const char* s_20b0de = "subgroupAll"; // string xref
    const char* s_1ec059 = "MemoryBarrierImage"; // string xref
    const char* s_1eb876 = "frexp"; // string xref
    const char* s_1a3f75 = "Construct mat4x2"; // string xref
    const char* s_1ace78 = "MulAdd cooperative matrices KHR"; // string xref
    const char* s_21bd71 = "subgroupBallotBitCount"; // string xref
    const char* s_28217a = "Construct mat4x3"; // string xref
    const char* s_22c6a9 = "Construct dvec2"; // string xref
    const char* s_1fa54e = "Construct u16vec2"; // string xref
    const char* s_22bd9f = "subgroupQuadSwapVertical"; // string xref
    const char* s_1d5f98 = "subgroupMin"; // string xref
    const char* s_1e5145 = "Construct bvec3"; // string xref
    const char* s_1fa53f = "Construct vec2"; // string xref
    const char* s_1b304b = "subgroupBallotFindLSB"; // string xref
    const char* s_1ba261 = "modf"; // string xref
    const char* s_2353f7 = "subgroupPartitionedExclusiveOrNV"; // string xref
    const char* s_19d1af = "Construct i16vec4"; // string xref
    const char* s_235ba6 = "Construct u16vec4"; // string xref
    const char* s_1a3f96 = "Construct umat2"; // string xref
    const char* s_20b8d8 = "Barrier"; // string xref
    const char* s_2228ac = "Construct int8_t"; // string xref
    const char* s_1bab5e = "MemoryBarrier"; // string xref
    const char* s_1c8a34 = "Construct bool"; // string xref
    const char* s_235c39 = "Load cooperative matrix NV"; // string xref
    const char* s_260663 = "Construct bmat2"; // string xref
    const char* s_25a0d9 = "Construct u64vec3"; // string xref
    const char* s_22c6b9 = "Construct int"; // string xref
    const char* s_1bab29 = "Construct u64vec2"; // string xref
    const char* s_1c13b9 = "Construct dmat2"; // string xref
    const char* s_20b8e0 = "writeInvocation"; // string xref
    const char* s_2525eb = "subgroupPartitionedInclusiveMinNV"; // string xref
    const char* s_20b8c4 = "Construct f16mat2x3"; // string xref
    const char* s_20b0ea = "subgroupExclusiveMul"; // string xref
    const char* s_19d1c1 = "Construct dmat3"; // string xref
    const char* s_281821 = "mix"; // string xref
    const char* s_1fa560 = "Construct imat3"; // string xref
    const char* s_1ba1a5 = "subgroupPartitionedInclusiveXorNV"; // string xref
    const char* s_25a0fa = "readInvocation"; // string xref
    const char* s_1ace98 = "Debug printf"; // string xref
    const char* s_196abb = "Construct imat4x3"; // string xref
    const char* s_1ace18 = "Construct double"; // string xref
    const char* s_19d1e3 = "Construct bmat3x4"; // string xref
    const char* s_1ba266 = "textureSize"; // string xref
    const char* s_259843 = "subgroupShuffleXor"; // string xref
    const char* s_21c478 = "textureFetch"; // string xref
    const char* s_1cf0b5 = "MulAdd cooperative matrices NV"; // string xref
    const char* s_1fa580 = "Construct umat4"; // string xref
    const char* s_19d1f5 = "Construct combined texture-sampler"; // string xref
    const char* s_202357 = "subgroupAny"; // string xref
    const char* s_1f9c9f = "colorAttachmentReadEXT"; // string xref
    const char* s_260654 = "Construct mat2"; // string xref
    const char* s_19d19d = "Construct i16vec3"; // string xref
    const char* s_19cad3 = "subgroupPartitionedExclusiveMinNV"; // string xref
    const char* s_1dcf80 = "Construct umat3x4"; // string xref
    const char* s_24c240 = "Construct u16vec3"; // string xref
    const char* s_1e5155 = "Construct bmat2x3"; // string xref
    const char* s_1e4a4c = "imageStore"; // string xref
    const char* s_2029c2 = "imageStoreLod"; // string xref
    const char* s_235bdc = "textureClamp"; // string xref
    const char* s_23c6b9 = "subgroupExclusiveMin"; // string xref
    const char* s_242ff7 = "subgroupMemoryBarrierBuffer"; // string xref
    const char* s_25fe33 = "imageAtomicLoad"; // string xref
    const char* s_19d1d1 = "Construct umat3x2"; // string xref
    const char* s_25a109 = "textureFetchOffset"; // string xref
    const char* s_1d66d1 = "AtomicCounterAnd"; // string xref
    const char* s_190175 = "Construct f16vec3"; // string xref
    const char* s_1bab6c = "imageSampleFootprintClampNV"; // string xref
    const char* s_2228df = "Construct umat4x2"; // string xref
    const char* s_260685 = "GroupMemoryBarrier"; // string xref
    const char* s_1fa5a0 = "Construct f16mat4x3"; // string xref
    const char* s_1c81e9 = "subgroupMemoryBarrierImage"; // string xref
    const char* s_211b7e = "textureOffsetClamp"; // string xref
    const char* s_1e4a57 = "imageAtomicStore"; // string xref
    const char* s_2704e3 = "Construct f16mat2"; // string xref
    const char* s_24ba4a = "subgroupClusteredXor"; // string xref
    const char* s_2228fb = "imageSampleFootprintLodNV"; // string xref
    const char* s_1e51ae = "sparseTextureOffsetClamp"; // string xref
    const char* s_1d66e2 = "textureGatherLod"; // string xref
    const char* s_1c13a8 = "Construct u8vec2"; // string xref
    const char* s_19d218 = "IsHelperInvocation"; // string xref
    const char* s_24ba5f = "subgroupPartitionedMinNV"; // string xref
    const char* s_1b4b1c = "Construct i64vec4"; // string xref
    const char* s_23d0a3 = "outer product"; // string xref
    const char* s_211b6c = "Construct f16mat4"; // string xref
    const char* s_1b4b0a = "Construct i64vec3"; // string xref
    const char* s_1cf038 = "Construct reference"; // string xref
    const char* s_2228f1 = "AtomicAdd"; // string xref
    const char* s_1a3fbd = "subBorrow"; // string xref
    const char* s_259915 = "textureLodOffset"; // string xref
    const char* s_1fa5ff = "sparseTextureGradOffset"; // string xref
    const char* s_235be9 = "textureGatherLodOffset"; // string xref
    const char* s_235c1d = "Load cooperative matrix KHR"; // string xref
    const char* s_1c0bd6 = "ignoreIntersectionNV"; // string xref
    const char* s_21bd5f = "subgroupBroadcast"; // string xref
    const char* s_22c6e6 = "Construct cooperative matrix NV"; // string xref
    const char* s_260673 = "Construct f16vec4"; // string xref
    const char* s_211303 = "subgroupInclusiveAnd"; // string xref
    const char* s_2029eb = "iMulExtended"; // string xref
    const char* s_1b4ac2 = "imageQuerySize"; // string xref
    const char* s_1f2e93 = "subgroupExclusiveXor"; // string xref
    const char* s_2029d0 = "sparseTextureGatherOffsets"; // string xref
    const char* s_20b915 = "Store cooperative matrix NV"; // string xref
    const char* s_1e496b = "rayQueryGetIntersectionPrimitiveIndexEXT"; // string xref
    const char* s_1fa570 = "Construct imat4"; // string xref
    const char* s_196a19 = "Compare Less Than"; // string xref
    const char* s_28218b = "Construct bmat3x2"; // string xref
    const char* s_20239a = "EmitVertex"; // string xref
    const char* s_211bad = "sparseTextureGatherLod"; // string xref
    const char* s_235bb8 = "Construct dmat2x4"; // string xref
    const char* s_1a36c3 = "rayQueryGetWorldRayOriginEXT"; // string xref
    const char* s_1fa5d7 = "sparseTextureLod"; // string xref
    const char* s_1b4aea = "Construct u8vec3"; // string xref
    const char* s_26fe22 = "subgroupPartitionedInclusiveOrNV"; // string xref
    const char* s_252e3d = "Construct uvec3"; // string xref
    const char* s_1e517b = "Construct f16mat4x2"; // string xref
    const char* s_2704d1 = "Construct f16vec2"; // string xref
    const char* s_1ce6e6 = "subgroupExclusiveAdd"; // string xref
    const char* s_1baaf1 = "imageQuerySamples"; // string xref
    const char* s_1f2f12 = "textureProjGradOffset"; // string xref
    const char* s_2353ba = "subgroupClusteredAnd"; // string xref
    const char* s_23c628 = "imageAtomicAnd"; // string xref
    const char* s_2704f5 = "textureGradClamp"; // string xref
    const char* s_20afb0 = "textureGather"; // string xref
    const char* s_1f2ec1 = "writePackedPrimitiveIndices4x8NV"; // string xref
    const char* s_202363 = "subgroupInclusiveAdd"; // string xref
    const char* s_235c00 = "addCarry"; // string xref
    const char* s_1b30d2 = "reportIntersectionNV"; // string xref
    const char* s_22c75a = "HitObjectRecordHitMotionNV"; // string xref
    const char* s_202288 = "rayQueryGetIntersectionInstanceIdEXT"; // string xref
    const char* s_1a3fa6 = "textureGradOffsetClamp"; // string xref
    const char* s_28167c = "rayQueryGetIntersectionCandidateAABBOpaqueEXT"; // string xref
    const char* s_2597a2 = "rayQueryGetRayFlagsEXT"; // string xref
    const char* s_1dc85e = "bitfieldInsert"; // string xref
    const char* s_2436e5 = "HitObjectRecordHitWithIndexMotionNV"; // string xref
    const char* s_2436c7 = "HitObjectRecordHitWithIndexNV"; // string xref
    const char* s_1f9bdd = "imageAtomicCompSwap"; // string xref
    const char* s_26fe43 = "subgroupPartitionedExclusiveAndNV"; // string xref
    const char* s_1cf04c = "imageLoadLod"; // string xref
    const char* s_1ac5ed = "terminateRayNV"; // string xref
    const char* s_252eca = "HitObjectGetRayTMinNV"; // string xref
    const char* s_1dcfd1 = "HitObjectRecordMissNV"; // string xref
    const char* s_22be85 = "subpassLoadMS"; // string xref
    const char* s_1f35b2 = "cross-product"; // string xref
    const char* s_252680 = "textureQueryLod"; // string xref
    const char* s_1dcffd = "HitObjectGetPrimitiveIndexNV"; // string xref
    const char* s_252ea4 = "executeCallableKHR"; // string xref
    const char* s_21c437 = "Construct dvec4"; // string xref
    const char* s_1b4a24 = "Compare Less Than or Equal"; // string xref
    const char* s_22bd42 = "rayQueryGetWorldRayDirectionEXT"; // string xref
    const char* s_2821df = "HitObjectGetShaderBindingTableRecordIndexNV"; // string xref
    const char* s_1fa617 = "HitObjectRecordMissMotionNV"; // string xref
    const char* s_1fa590 = "Construct bmat3"; // string xref
    const char* s_1f9c7d = "subgroupPartitionedInclusiveAndNV"; // string xref
    const char* s_23530e = "rayQueryGetIntersectionFrontFaceEXT"; // string xref
    const char* s_22bea0 = "textureGrad"; // string xref
    const char* s_252e4d = "Construct dmat3x2"; // string xref
    const char* s_1eb7c7 = "subgroupBallotFindMSB"; // string xref
    const char* s_20b88e = "Construct uint16_t"; // string xref
    const char* s_196298 = "subgroupClusteredMax"; // string xref
    const char* s_1dc68f = "rayQueryGetIntersectionTypeEXT"; // string xref
    const char* s_1ba272 = "textureQueryLevels"; // string xref
    const char* s_1901ac = "imageSampleFootprintGradNV"; // string xref
    const char* s_21c485 = "HitObjectGetCurrentTimeNV"; // string xref
    const char* s_1d606a = "textureProjOffset"; // string xref
    const char* s_1fa5c1 = "AtomicCounterSubtract"; // string xref
    const char* s_252e85 = "mageSampleFootprintGradClampNV"; // string xref
    const char* s_281655 = "rayQueryGetIntersectionBarycentricsEXT"; // string xref
    const char* s_2436b0 = "WorkgroupMemoryBarrier"; // string xref
    const char* s_1c1406 = "HitObjectTraceRayNV"; // string xref
    const char* s_20fd1e = "texture"; // string xref
    const char* s_196237 = "rayQueryConfirmIntersectionEXT"; // string xref
    const char* s_196313 = "SetMeshOutputsEXT"; // string xref
    const char* s_2680fd = "HitObjectGetAttributesNV"; // string xref
    const char* s_1c13c9 = "Construct umat3"; // string xref
    const char* s_2436a9 = "sincos"; // string xref
    const char* s_20299f = "Construct i8vec3"; // string xref
    const char* s_25fd79 = "subgroupPartitionedExclusiveAddNV"; // string xref
    const char* s_2228bd = "Construct uvec2"; // string xref
    const char* s_25a11c = "HitObjectGetObjectRayOriginNV"; // string xref
    const char* s_24366f = "Construct imat2x3"; // string xref
    const char* s_1b4b90 = "HitObjectGetObjectRayDirectionNV"; // string xref
    const char* s_25fcff = "rayQueryGetIntersectionTriangleVertexPositionsEXT"; // string xref
    const char* s_22c706 = "Construct acceleration structure"; // string xref
    const char* s_26ff0b = "imageLoad"; // string xref
    const char* s_235c54 = "HitObjectGetHitKindNV"; // string xref
    const char* s_25fe6a = "textureLod"; // string xref
    const char* s_21bcf2 = "rayQueryInitializeEXT"; // string xref
    const char* s_1dcfad = "WorkgroupMemoryBarrierWithGroupSync"; // string xref
    const char* s_1b4b5e = "AllMemoryBarrierWithGroupSync"; // string xref
    const char* s_21c447 = "Construct bvec4"; // string xref
    const char* s_267395 = "stencilAttachmentReadEXT"; // string xref
    const char* s_20b113 = "depthAttachmentReadEXT"; // string xref
    const char* s_1dc742 = "subgroupExclusiveAnd"; // string xref
    const char* s_1cf081 = "sparseTextureClamp"; // string xref
    const char* s_1fa5e8 = "sparseTextureLodOffset"; // string xref
    const char* s_1ec079 = "HitObjectExecuteShaderNV"; // string xref
    const char* s_25fd4b = "subgroupInclusiveMul"; // string xref
    const char* s_1c8ab3 = "HitObjectGetGeometryIndexNV"; // string xref
    const char* s_22c740 = "sparseTextureGatherOffset"; // string xref
    const char* s_1f9c44 = "rayQueryGetIntersectionWorldToObjectEXT"; // string xref
    const char* s_20b146 = "bitfieldExtract"; // string xref
    const char* s_1d6724 = "HitObjectGetObjectToWorldNV"; // string xref
    const char* s_211263 = "rayQueryGenerateIntersectionEXT"; // string xref
    const char* s_1cf094 = "DeviceMemoryBarrierWithGroupSync"; // string xref
    const char* s_1a3788 = "EmitMeshTasksEXT"; // string xref
    const char* s_20b015 = "rayQueryTerminateEXT"; // string xref
    const char* s_243709 = "HitObjectGetWorldToObjectNV"; // string xref
    const char* s_24c2c4 = "HitObjectReadShaderRecordBufferHandleNV"; // string xref
    const char* s_1b4b7c = "DeviceMemoryBarrier"; // string xref
    const char* s_1901e9 = "HitObjectGetInstaneIdNV"; // string xref
    const char* s_23d101 = "ReorderThreadNV"; // string xref
    const char* s_2606a7 = "mul"; // string xref
    const char* s_252eb7 = "HitObjectIsEmptyNV"; // string xref
    const char* s_1d670d = "HitObjectRecordEmptyNV"; // string xref
    const char* s_1c1396 = "Construct uint8_t"; // string xref
    const char* s_19d18b = "Construct i16vec2"; // string xref
    const char* s_1ec015 = "Construct uint64"; // string xref
    const char* s_1c8a43 = "Construct i8vec2"; // string xref
    const char* s_1cf014 = "Construct uvec4"; // string xref
    const char* s_1b4b2e = "Construct float16_t"; // string xref
    const char* s_260698 = "AtomicSubtract"; // string xref
    const char* s_2022ad = "rayQueryGetIntersectionObjectRayOriginEXT"; // string xref
    const char* s_23d091 = "Construct bmat4x3"; // string xref
    const char* s_1ac662 = "EndPrimitive"; // string xref
    const char* s_1e494c = "imageAtomicMax"; // string xref
    const char* s_19cb8c = "textureProj"; // string xref
    const char* s_2023b3 = "textureSamples"; // string xref
    const char* s_1ace61 = "imageSampleFootprintNV"; // string xref
    const char* s_1c8a93 = "HitObjectGetWorldRayDirectionNV"; // string xref
    const char* s_24c27d = "sparseTextureGatherLodOffsets"; // string xref
    const char* s_1c0c8b = "textureProjGrad"; // string xref
    const char* s_1ba285 = "textureProjLod"; // string xref
    const char* s_267402 = "textureGatherOffset"; // string xref
    const char* s_1b3073 = "subgroupInclusiveMax"; // string xref
    const char* s_1dc737 = "subgroupOr"; // string xref
    const char* s_21bd88 = "subgroupMul"; // string xref
    const char* s_1f9cf6 = "textureProjLodOffset"; // string xref
    const char* s_1d66f3 = "HitObjectTraceRayMotionNV"; // string xref
    const char* s_1901c7 = "HitObjectGetInstanceCustomIndexNV"; // string xref
    const char* s_211283 = "rayQueryGetRayTMinEXT"; // string xref
    const char* s_20b02a = "rayQueryGetIntersectionObjectToWorldEXT"; // string xref
    const char* s_1f9c31 = "rayQueryProceedEXT"; // string xref
    const char* s_2606ab = "HitObjectGetWorldRayOriginNV"; // string xref
    const char* s_1a3fc7 = "HitObjectIsHitNV"; // string xref
    const char* s_1acea5 = "HitObjectIsMissNV"; // string xref
    const char* s_281831 = "textureGradOffset"; // string xref
    const char* s_1b3061 = "subgroupShuffleUp"; // string xref
    const char* s_2821ca = "HitObjectRecordHitNV"; // string xref
    const char* s_20b77a = "Compare Greater Than"; // string xref
    const char* s_23c6a5 = "subgroupInclusiveOr"; // string xref
    const char* s_1dcfe7 = "HitObjectGetRayTMaxNV"; // string xref
    const char* s_2821ba = "terminateRayKHR"; // string xref
    const char* s_2597b9 = "rayQueryGetIntersectionInstanceCustomIndexEXT"; // string xref
    const char* s_1a0e0f = "time"; // string xref
    const char* s_1eb762 = "imageAtomicMin"; // string xref
    const char* s_20b000 = "textureGatherOffsets"; // string xref
    const char* s_2598e7 = "subpassLoad"; // string xref
    const char* s_24c29b = "traceRayKHR"; // string xref
    const char* s_1c0aa5 = "rayQueryGetIntersectionTEXT"; // string xref
    const char* s_1a3f86 = "Construct imat2"; // string xref
    const char* s_20b8fa = "AtomicOr"; // string xref
    const char* s_23d07f = "Construct bmat4x2"; // string xref
    const char* s_20b156 = "textureOffset"; // string xref
    const char* s_1ac4c5 = "rayQueryGetIntersectionInstanceShaderBindingTableRecordOffsetEXT"; // string xref
    const char* s_1d5f28 = "rayQueryGetIntersectionObjectRayDirectionEXT"; // string xref
    const char* s_1c0bb9 = "traceRayMotionNV"; // string xref
    const char* s_190187 = "MemoryBarrierShared"; // string xref
    const char* s_2352e3 = "imageAtomicOr"; // string xref
    const char* s_28219d = "sparseTextureGatherLodOffset"; // string xref
    const char* s_1ac5e5 = "traceNV"; // string xref
    const char* s_1cf059 = "textureGatherLodOffsets"; // string xref
    const char* s_1c0ac1 = "rayQueryGetIntersectionGeometryIndexEXT"; // string xref
    const char* s_2021c6 = "sparseTexture"; // string xref
    const char* s_1ec06c = "uMulExtended"; // string xref
    const char* s_2680e9 = "sparseTextureOffset"; // string xref
    const char* s_20b8b2 = "Construct dmat2x3"; // string xref
    const char* s_267370 = "subgroupShuffle"; // string xref
    const char* s_1dc7b4 = "executeCallableNV"; // string xref
    const char* s_1dc729 = "subgroupElect"; // string xref
    const char* s_1ec038 = "Construct cooperative matrix KHR"; // string xref
    const char* s_2671d2 = "sparseTextureGather"; // string xref
    const char* s_235bca = "Construct dmat4x2"; // string xref
    const char* s_2525d3 = "subgroupPartitionedOrNV"; // string xref
    const char* s_24c2a7 = "Store cooperative matrix KHR"; // string xref
    const char* s_19019b = "sparseTexelFetch"; // string xref
    const char* s_25fd60 = "subgroupPartitionedMaxNV"; // string xref
    const char* s_211b5a = "Construct dmat3x4"; // string xref
    const char* s_1c13d9 = "MemoryBarrierBuffer"; // string xref
    const char* s_1cf071 = "sparseImageLoad"; // string xref
    const char* s_24c26e = "AtomicExchange"; // string xref
    const char* s_1c8a7c = "sparseTextureGradClamp"; // string xref
    const char* s_211b91 = "sparseTextureGradOffsetClam"; // string xref
    const char* s_1f2df0 = "imageAtomicXor"; // string xref
    const char* s_1dcf6e = "Construct imat3x2"; // string xref
    const char* s_243681 = "Construct imat2x4"; // string xref
}
