// FUNCTION: sub_8e1bc8
// LIBRARY: libarkernel3.so
// RVA: 0x8e1bc8 | SIZE: 3316 bytes | SHA256: 70095F7B4582DE958FE1CCED8970A029AA0A5FD207B1E790468875777840207E
// SEMANTIC_LABEL: HAIR_COLOR_PIPELINE | CONFIDENCE: HIGH_CONFIDENCE
// IMPORTED_APIS: __stack_chk_fail
// STRING_XREFS: lipstick mode, Matte, Satin, Moist, HightLight, Pearl, MetalLight, BittenLips, Diamond, ParticlePearl, LocateMethod Type, ALIGN_LEFT_BOTTOM, SINGLE, SCREEN, TRIANGLES, REFERENCES, TRACKING_RECT, SPARSE_TRIANGLE, TRIANGLES_LEFT_EYE, TRIANGLES_RIGHT_EYE, TRIANGLES_LEFT_EYEBROW, TRIANGLES_RIGHT_EYEBROW, TRIANGLES_DYNAMIC, FULL_SCREEN, TRIANGLES_LEFT_EYESHADOW, TRIANGLES_RIGHT_EYESHADOW, REFERENCES_ALIGN, SELF_TEST_ALIGN_IN_CENTER, SELF_TEST_ALIGN_OUT_CENTER, ALIGN_LEFT_TOP, ALIGN_RIGHT_TOP, ALIGN_RIGHT_BOTTOM, ALIGN_MIDDLE_TOP, ALIGN_MIDDLE_BOTTOM, ALIGN_MIDDLE_LEFT, ALIGN_MIDDLE_RIGHT, SELF_TEST_FULL_SCREEN, FACE_RECT, SELF_TEST_ALIGN_IN_TOP, SIMPLE_GESTURE, SELF_TEST_ALIGN_IN_BOTTOM, SELF_TEST_ALIGN_IN_LEFT, SELF_TEST_ALIGN_IN_RIGHT, SELF_TEST_ALIGN_OUT_TOP, SELF_TEST_ALIGN_OUT_BOTTOM, SELF_TEST_ALIGN_OUT_LEFT, SELF_TEST_ALIGN_OUT_RIGHT, TRIANGLES_LEFT_EYE_FIT_HEIGHT, TRIANGLES_RIGHT_EYE_FIT_HEIGHT, TRIANGLES_LEFT_3DEYELASH, TRIANGLES_RIGHT_3DEYELASH, NewLeftEyebrow, NewRightEyebrow, TRIANGLESOptimizeForMouth, TRIANGLES_LEFT_CONDENSE_EYEBROW, TRIANGLES_RIGHT_CONDENSE_EYEBROW, TRIANGLES_DynamicSkinMask, TRIANGLES_LEFT_UP_EYELINER, TRIANGLES_RIGHT_UP_EYELINER, TRIANGLES_MIRROR_EYEBROW, TRIANGLES_VERSION2_LEFT_EYEBROW, TRIANGLES_VERSION2_RIGHT_EYEBROW, TRIANGLES_3D_UP_LIPSTICK, TRIANGLES_3D_DOWN_LIPSTICK, TRIANGLES_3D_LEFT_EYELASH, TRIANGLES_3D_RIGHT_EYELASH, TRIANGLES_3D_UP_EYESHADOW, TRIANGLES_3D_DOWN_EYESHADOW, TRIANGLES_3D_EYE_PUPILS, TRIANGLES_2D_LEFT_EYE_PUPILS, TRIANGLES_2D_RIGHT_EYE_PUPILS, TRIANGLES_NEWFULLFACEMESH, TRIANGLES_2D_LEFT_EYE_SOCKET, TRIANGLES_2D_RIGHT_EYE_SOCKET, TRIANGLES_312, makeup lipstick part config, LipstickMode, ORGBA, Operation, TeethWhiten, WhitenDegree, ShimmerMetalPath, ShimmerPeralPath, GlossAlpha, LightAlpha, Rectangle, LocateMethod, LightColorRGBA, MetalShimmerColor, DiamondMixColor1, DiamondMixColor2, DiamondShimmerColor, DoubleMouthMaskSecond, SecondORGBA, DoubleMouthModel, MultiplyOverlayMode, HighDiffDegree, ColorfulPath, MaskNum, ORGBA3rd, ORGBA4th, ForceCloseDiffEnvMouth, RemoveHighlight, InputMouthMask, TeethBlurParam, NewMouthLight, NewMouthLightAlpha, NewMouthLightAreaParam, GuideFilter, InputParticleMask, ParticleAlpha, ParticleOverlayMode, InputShimmerMask, ParticleFirstColor, ParticleSecondColor, makeup lipstick part

#include <stdint.h>
#include <jni.h>

// Reconstructed C++ Native Implementation
extern "C" JNIEXPORT void* sub_8e1bc8(JNIEnv* env, jobject thiz) {
    // Function entrypoint at 0x8e1bc8
    // Call imported API: __stack_chk_fail
    // Literal reference: "lipstick mode"
    // Literal reference: "Matte"
    // Literal reference: "Satin"
    // Literal reference: "Moist"
    // Literal reference: "HightLight"
    // Literal reference: "Pearl"
    // Literal reference: "MetalLight"
    // Literal reference: "BittenLips"
    // Literal reference: "Diamond"
    // Literal reference: "ParticlePearl"
    // Literal reference: "LocateMethod Type"
    // Literal reference: "ALIGN_LEFT_BOTTOM"
    // Literal reference: "SINGLE"
    // Literal reference: "SCREEN"
    // Literal reference: "TRIANGLES"
    // Literal reference: "REFERENCES"
    // Literal reference: "TRACKING_RECT"
    // Literal reference: "SPARSE_TRIANGLE"
    // Literal reference: "TRIANGLES_LEFT_EYE"
    // Literal reference: "TRIANGLES_RIGHT_EYE"
    // Literal reference: "TRIANGLES_LEFT_EYEBROW"
    // Literal reference: "TRIANGLES_RIGHT_EYEBROW"
    // Literal reference: "TRIANGLES_DYNAMIC"
    // Literal reference: "FULL_SCREEN"
    // Literal reference: "TRIANGLES_LEFT_EYESHADOW"
    // Literal reference: "TRIANGLES_RIGHT_EYESHADOW"
    // Literal reference: "REFERENCES_ALIGN"
    // Literal reference: "SELF_TEST_ALIGN_IN_CENTER"
    // Literal reference: "SELF_TEST_ALIGN_OUT_CENTER"
    // Literal reference: "ALIGN_LEFT_TOP"
    // Literal reference: "ALIGN_RIGHT_TOP"
    // Literal reference: "ALIGN_RIGHT_BOTTOM"
    // Literal reference: "ALIGN_MIDDLE_TOP"
    // Literal reference: "ALIGN_MIDDLE_BOTTOM"
    // Literal reference: "ALIGN_MIDDLE_LEFT"
    // Literal reference: "ALIGN_MIDDLE_RIGHT"
    // Literal reference: "SELF_TEST_FULL_SCREEN"
    // Literal reference: "FACE_RECT"
    // Literal reference: "SELF_TEST_ALIGN_IN_TOP"
    // Literal reference: "SIMPLE_GESTURE"
    // Literal reference: "SELF_TEST_ALIGN_IN_BOTTOM"
    // Literal reference: "SELF_TEST_ALIGN_IN_LEFT"
    // Literal reference: "SELF_TEST_ALIGN_IN_RIGHT"
    // Literal reference: "SELF_TEST_ALIGN_OUT_TOP"
    // Literal reference: "SELF_TEST_ALIGN_OUT_BOTTOM"
    // Literal reference: "SELF_TEST_ALIGN_OUT_LEFT"
    // Literal reference: "SELF_TEST_ALIGN_OUT_RIGHT"
    // Literal reference: "TRIANGLES_LEFT_EYE_FIT_HEIGHT"
    // Literal reference: "TRIANGLES_RIGHT_EYE_FIT_HEIGHT"
    // Literal reference: "TRIANGLES_LEFT_3DEYELASH"
    // Literal reference: "TRIANGLES_RIGHT_3DEYELASH"
    // Literal reference: "NewLeftEyebrow"
    // Literal reference: "NewRightEyebrow"
    // Literal reference: "TRIANGLESOptimizeForMouth"
    // Literal reference: "TRIANGLES_LEFT_CONDENSE_EYEBROW"
    // Literal reference: "TRIANGLES_RIGHT_CONDENSE_EYEBROW"
    // Literal reference: "TRIANGLES_DynamicSkinMask"
    // Literal reference: "TRIANGLES_LEFT_UP_EYELINER"
    // Literal reference: "TRIANGLES_RIGHT_UP_EYELINER"
    // Literal reference: "TRIANGLES_MIRROR_EYEBROW"
    // Literal reference: "TRIANGLES_VERSION2_LEFT_EYEBROW"
    // Literal reference: "TRIANGLES_VERSION2_RIGHT_EYEBROW"
    // Literal reference: "TRIANGLES_3D_UP_LIPSTICK"
    // Literal reference: "TRIANGLES_3D_DOWN_LIPSTICK"
    // Literal reference: "TRIANGLES_3D_LEFT_EYELASH"
    // Literal reference: "TRIANGLES_3D_RIGHT_EYELASH"
    // Literal reference: "TRIANGLES_3D_UP_EYESHADOW"
    // Literal reference: "TRIANGLES_3D_DOWN_EYESHADOW"
    // Literal reference: "TRIANGLES_3D_EYE_PUPILS"
    // Literal reference: "TRIANGLES_2D_LEFT_EYE_PUPILS"
    // Literal reference: "TRIANGLES_2D_RIGHT_EYE_PUPILS"
    // Literal reference: "TRIANGLES_NEWFULLFACEMESH"
    // Literal reference: "TRIANGLES_2D_LEFT_EYE_SOCKET"
    // Literal reference: "TRIANGLES_2D_RIGHT_EYE_SOCKET"
    // Literal reference: "TRIANGLES_312"
    // Literal reference: "makeup lipstick part config"
    // Literal reference: "LipstickMode"
    // Literal reference: "ORGBA"
    // Literal reference: "Operation"
    // Literal reference: "TeethWhiten"
    // Literal reference: "WhitenDegree"
    // Literal reference: "ShimmerMetalPath"
    // Literal reference: "ShimmerPeralPath"
    // Literal reference: "GlossAlpha"
    // Literal reference: "LightAlpha"
    // Literal reference: "Rectangle"
    // Literal reference: "LocateMethod"
    // Literal reference: "LightColorRGBA"
    // Literal reference: "MetalShimmerColor"
    // Literal reference: "DiamondMixColor1"
    // Literal reference: "DiamondMixColor2"
    // Literal reference: "DiamondShimmerColor"
    // Literal reference: "DoubleMouthMaskSecond"
    // Literal reference: "SecondORGBA"
    // Literal reference: "DoubleMouthModel"
    // Literal reference: "MultiplyOverlayMode"
    // Literal reference: "HighDiffDegree"
    // Literal reference: "ColorfulPath"
    // Literal reference: "MaskNum"
    // Literal reference: "ORGBA3rd"
    // Literal reference: "ORGBA4th"
    // Literal reference: "ForceCloseDiffEnvMouth"
    // Literal reference: "RemoveHighlight"
    // Literal reference: "InputMouthMask"
    // Literal reference: "TeethBlurParam"
    // Literal reference: "NewMouthLight"
    // Literal reference: "NewMouthLightAlpha"
    // Literal reference: "NewMouthLightAreaParam"
    // Literal reference: "GuideFilter"
    // Literal reference: "InputParticleMask"
    // Literal reference: "ParticleAlpha"
    // Literal reference: "ParticleOverlayMode"
    // Literal reference: "InputShimmerMask"
    // Literal reference: "ParticleFirstColor"
    // Literal reference: "ParticleSecondColor"
    // Literal reference: "makeup lipstick part"
    return (void*)0;
}
