// FUNCTION: sub_774ea4
// LIBRARY: libarkernel3.so
// RVA: 0x774ea4 | SIZE: 4096 bytes | SHA256: 6AC18A869419347B26C23C037D24D56CB719AA3BA967DD0CA3656FDEE34B4D64
// SEMANTIC_LABEL: HAIR_COLOR_PIPELINE | CONFIDENCE: HIGH_CONFIDENCE
// IMPORTED_APIS: None
// STRING_XREFS: script effect type, none, face lift, makeup, face lift makeup, segment mask type, invalid, body reverse, body, source, face reverse, face, sky, sky reverse, hair, hair reverse, eraser, head, head reverse, skin, skin reverse, cloth, cloth reverse, date require type, UserDefined, SourceGrayImage, SourceColorImage, SourceTexture, TouchListener, Animal, Food, Face, FaceEar, FaceNeck, SegmentMouthMask, SegmentFaceMask, FacePosEstimator, FaceGender, FaceEmotion, Face2DReconstructor, Face3DReconstructor, Shoulder, Hand, MultiHand, HandPose, BodySegment, HairSegment, SkySegment, SkinSegment, HeadSegment, BodyJoint, BodyContour, ARGyroscopeQuaternionData, ARFaceMesh, ARPointCloud, ARWorldTracking, ARPlaneAnchor, ARLightEstimate, FaceAge, ARInstantPlacement, FaceEyelid, Face2DBackgroundReconstructor, FaceDL3DReconstructor, CGTexture, Nails, FaceDL3DNet, FaceHead, BodyInOne, FaceDL3DRigging, ClothSegment, Face3DFA, Face3DFAMesh, EyePupil, AiKit, AiDetect, Face2DReconstructorV1, Face2DReconstructorV3, HorizontalARPlaneAnchor, VerticalARPlaneAnchor, ARSkeleton, Human3D, BodyInOneNeck, BodyInOneBreast, SpaceDepth, SpaceNormal, ParamTableType, MVAR, CCD, StyleMakeup, MTXX, StyleMTXX, StyleFilter, MakeupControlType, Undefined, Eyebrow, Eyeshadow, Eyelash, Eyelid, Eyeliner, Lipstick, Rouge, Foundation, Contour, 3dLightEffect, FaceMask, Hair, Mole, WoCan, RenZhong, FaceLighting3d, Script, ParamControlConfig, Key, Type, EnglishTip, ChineseTip, Flag, DefaultValue, DefaultOpacity, MinValue, MaxValue, DefaultRGBA, script part, ScriptPath, ParamTableType, EnableTouch, EnableTouchGesture, EnableSlam, EnableARInstantPlacement, EnableARPlane, EnableHorizontalARPlane, EnableVerticalARPlane, EnableARSkeleton, EnableGesture, EnableFaceSegmemt, ScriptEffectType, EnableFood, EnableAnimal, EnableHandPose

#include <stdint.h>
#include <jni.h>

// Reconstructed C++ Native Implementation
extern "C" JNIEXPORT void* sub_774ea4(JNIEnv* env, jobject thiz) {
    // Function entrypoint at 0x774ea4
    // Literal reference: "script effect type"
    // Literal reference: "none"
    // Literal reference: "face lift"
    // Literal reference: "makeup"
    // Literal reference: "face lift makeup"
    // Literal reference: "segment mask type"
    // Literal reference: "invalid"
    // Literal reference: "body reverse"
    // Literal reference: "body"
    // Literal reference: "source"
    // Literal reference: "face reverse"
    // Literal reference: "face"
    // Literal reference: "sky"
    // Literal reference: "sky reverse"
    // Literal reference: "hair"
    // Literal reference: "hair reverse"
    // Literal reference: "eraser"
    // Literal reference: "head"
    // Literal reference: "head reverse"
    // Literal reference: "skin"
    // Literal reference: "skin reverse"
    // Literal reference: "cloth"
    // Literal reference: "cloth reverse"
    // Literal reference: "date require type"
    // Literal reference: "UserDefined"
    // Literal reference: "SourceGrayImage"
    // Literal reference: "SourceColorImage"
    // Literal reference: "SourceTexture"
    // Literal reference: "TouchListener"
    // Literal reference: "Animal"
    // Literal reference: "Food"
    // Literal reference: "Face"
    // Literal reference: "FaceEar"
    // Literal reference: "FaceNeck"
    // Literal reference: "SegmentMouthMask"
    // Literal reference: "SegmentFaceMask"
    // Literal reference: "FacePosEstimator"
    // Literal reference: "FaceGender"
    // Literal reference: "FaceEmotion"
    // Literal reference: "Face2DReconstructor"
    // Literal reference: "Face3DReconstructor"
    // Literal reference: "Shoulder"
    // Literal reference: "Hand"
    // Literal reference: "MultiHand"
    // Literal reference: "HandPose"
    // Literal reference: "BodySegment"
    // Literal reference: "HairSegment"
    // Literal reference: "SkySegment"
    // Literal reference: "SkinSegment"
    // Literal reference: "HeadSegment"
    // Literal reference: "BodyJoint"
    // Literal reference: "BodyContour"
    // Literal reference: "ARGyroscopeQuaternionData"
    // Literal reference: "ARFaceMesh"
    // Literal reference: "ARPointCloud"
    // Literal reference: "ARWorldTracking"
    // Literal reference: "ARPlaneAnchor"
    // Literal reference: "ARLightEstimate"
    // Literal reference: "FaceAge"
    // Literal reference: "ARInstantPlacement"
    // Literal reference: "FaceEyelid"
    // Literal reference: "Face2DBackgroundReconstructor"
    // Literal reference: "FaceDL3DReconstructor"
    // Literal reference: "CGTexture"
    // Literal reference: "Nails"
    // Literal reference: "FaceDL3DNet"
    // Literal reference: "FaceHead"
    // Literal reference: "BodyInOne"
    // Literal reference: "FaceDL3DRigging"
    // Literal reference: "ClothSegment"
    // Literal reference: "Face3DFA"
    // Literal reference: "Face3DFAMesh"
    // Literal reference: "EyePupil"
    // Literal reference: "AiKit"
    // Literal reference: "AiDetect"
    // Literal reference: "Face2DReconstructorV1"
    // Literal reference: "Face2DReconstructorV3"
    // Literal reference: "HorizontalARPlaneAnchor"
    // Literal reference: "VerticalARPlaneAnchor"
    // Literal reference: "ARSkeleton"
    // Literal reference: "Human3D"
    // Literal reference: "BodyInOneNeck"
    // Literal reference: "BodyInOneBreast"
    // Literal reference: "SpaceDepth"
    // Literal reference: "SpaceNormal"
    // Literal reference: "ParamTableType"
    // Literal reference: "MVAR"
    // Literal reference: "CCD"
    // Literal reference: "StyleMakeup"
    // Literal reference: "MTXX"
    // Literal reference: "StyleMTXX"
    // Literal reference: "StyleFilter"
    // Literal reference: "MakeupControlType"
    // Literal reference: "Undefined"
    // Literal reference: "Eyebrow"
    // Literal reference: "Eyeshadow"
    // Literal reference: "Eyelash"
    // Literal reference: "Eyelid"
    // Literal reference: "Eyeliner"
    // Literal reference: "Lipstick"
    // Literal reference: "Rouge"
    // Literal reference: "Foundation"
    // Literal reference: "Contour"
    // Literal reference: "3dLightEffect"
    // Literal reference: "FaceMask"
    // Literal reference: "Hair"
    // Literal reference: "Mole"
    // Literal reference: "WoCan"
    // Literal reference: "RenZhong"
    // Literal reference: "FaceLighting3d"
    // Literal reference: "Script"
    // Literal reference: "ParamControlConfig"
    // Literal reference: "Key"
    // Literal reference: "Type"
    // Literal reference: "EnglishTip"
    // Literal reference: "ChineseTip"
    // Literal reference: "Flag"
    // Literal reference: "DefaultValue"
    // Literal reference: "DefaultOpacity"
    // Literal reference: "MinValue"
    // Literal reference: "MaxValue"
    // Literal reference: "DefaultRGBA"
    // Literal reference: "script part"
    // Literal reference: "ScriptPath"
    // Literal reference: "ParamTableType"
    // Literal reference: "EnableTouch"
    // Literal reference: "EnableTouchGesture"
    // Literal reference: "EnableSlam"
    // Literal reference: "EnableARInstantPlacement"
    // Literal reference: "EnableARPlane"
    // Literal reference: "EnableHorizontalARPlane"
    // Literal reference: "EnableVerticalARPlane"
    // Literal reference: "EnableARSkeleton"
    // Literal reference: "EnableGesture"
    // Literal reference: "EnableFaceSegmemt"
    // Literal reference: "ScriptEffectType"
    // Literal reference: "EnableFood"
    // Literal reference: "EnableAnimal"
    // Literal reference: "EnableHandPose"
    return (void*)0;
}
