// Function: sub_C36638
// RVA: 0xc36638, Size: 4096 bytes
int64_t sub_C36638(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    strcmp(...); // call PLT API at 0xc3670c
    strcmp(...); // call PLT API at 0xc367e0
    sub_C37D64(...); // call internal at 0xc3684c
    const char* str = "GL_AMD_gpu_shader_half_float_fetch";
    (*x9)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types_float64";
    const char* str = "GL_EXT_shader_explicit_arithmetic_types";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types_float32";
    const char* str = "GL_AMD_gpu_shader_half_float";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types_float16";
    const char* str = "GL_EXT_spirv_intrinsics";
    const char* str = "GL_ARB_shader_image_load_store";
    (*x9)(...);
    const char* str = "GL_EXT_shader_image_int64";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types_int32";
    const char* str = "GL_EXT_shader_explicit_arithmetic_types";
    (*x8)(...);
    const char* str = "GL_EXT_shader_8bit_storage";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types_int8";
    const char* str = "GL_ARB_gpu_shader_int64";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types_int64";
    const char* str = "GL_AMD_gpu_shader_int16";
    (*x8)(...);
    const char* str = "GL_EXT_shader_16bit_storage";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types";
    (*x8)(...);
    const char* str = "GL_EXT_shader_explicit_arithmetic_types_int16";
    const char* str = "GL_NV_ray_tracing";
    const char* str = "GL_EXT_ray_tracing";
    (*x8)(...);
    const char* str = "GL_EXT_ray_query";
    const char* str = "GL_EXT_shader_image_int64";
    (*x8)(...);
    (*x9)(...);
    const char* str = "GL_ARB_texture_cube_map_array";
    const char* str = "GL_AMD_gpu_shader_half_float";
    (*x8)(...);
    const char* str = "GL_EXT_shader_16bit_storage";
    const char* str = "GL_ARB_gpu_shader_fp64";
    (*x8)(...);
    const char* str = "GL_ARB_vertex_attrib_64bit";
    const char* str = "GL_EXT_shader_image_int64";
    (*x8)(...);
    const char* str = "GL_NV_mesh_shader";
    (*x9)(...);
    (*x9)(...);
    (*x8)(...);
    (*x9)(...);
    const char* str = "GL_EXT_ray_tracing";
    const char* str = "GL_NV_integer_cooperative_matrix";
    const char* str = "GL_ARB_texture_rectangle";
    (*x8)(...);
    const char* str = "texture-rectangle sampler keyword";
    (*x8)(...);
    const char* str = "GL_EXT_shader_image_int64";
    (*x8)(...);
    (*x8)(...);
    (*x9)(...);
    const char* str = "GL_EXT_shader_image_int64";
    (*x8)(...);
    (*x8)(...);
    const char* str = "GL_EXT_mesh_shader";
    (*x9)(...);
    const char* str = "GL_NV_shader_noperspective_interpolation";
    (*x8)(...);
    const char* str = "GL_EXT_terminate_invocation";
    const char* str = "GL_OES_EGL_image_external";
    (*x8)(...);
    const char* str = "GL_OES_EGL_image_external_essl3";
    const char* str = "GL_AMD_shader_explicit_vertex_parameter";
    const char* str = "GL_OES_texture_3D";
}
