// Function: sub_CA00E0
// RVA: 0xca00e0, Size: 4096 bytes
int64_t sub_CA00E0(int64_t a0, int64_t a1, int64_t a2, int64_t a3) {
    sub_C9FF14(...); // call internal func at 0xca0118
    void* g_2da8ba = (void*)0x2da8ba; // global ref
    const char* s_1fa470 = "Negate conditional"; // string xref
    const char* s_20b79a = "Bitwise not"; // string xref
    const char* s_252d6b = "Convert bool to uint"; // string xref
    const char* s_21c3f9 = "Convert bool to in16t_t"; // string xref
    const char* s_20290c = "Convert bool to float"; // string xref
    const char* s_1b4a58 = "Convert int16_t to uint16_t"; // string xref
    const char* s_2227b6 = "Convert int16_t to float16_t"; // string xref
    const char* s_2820e2 = "Convert int to uint64"; // string xref
    const char* s_1c1304 = "Convert int8_t to double"; // string xref
    const char* s_252d80 = "Convert bool to int64"; // string xref
    const char* s_1dced8 = "Convert int16_t to bool"; // string xref
    const char* s_23cfdd = "Convert int16_t to int64"; // string xref
    const char* s_252dc9 = "Convert int to uint"; // string xref
    const char* s_196a42 = "Convert bool to double"; // string xref
    const char* s_1f350d = "Convert int64 to int16_t"; // string xref
    const char* s_1fa4b4 = "Convert int64 to float16_t"; // string xref
    const char* s_1acd87 = "Convert double to int8_t"; // string xref
    const char* s_1dcf3a = "Convert uint64_t to acceleration structure"; // string xref
    const char* s_20b83f = "Convert float to int8_t"; // string xref
    const char* s_211b21 = "Convert uint16_t to int16_t"; // string xref
    const char* s_1c89fe = "Convert uint16_t to uint"; // string xref
    const char* s_1d664b = "Convert int16_t to uint8_t"; // string xref
    const char* s_1ebfa8 = "Convert int to double"; // string xref
    const char* s_1a3f26 = "Convert double to float16_t"; // string xref
    const char* s_243603 = "Convert float16_t to float"; // string xref
    const char* s_26803c = "Convert uint64 to int64"; // string xref
    const char* s_2023a5 = "radians"; // string xref
    const char* s_1f2e65 = "floatBitsToUint"; // string xref
    const char* s_1900c9 = "Convert int to int64"; // string xref
    const char* s_18fa80 = "int16BitsToFloat16"; // string xref
    const char* s_25a059 = "arc hyp. sine"; // string xref
    const char* s_1c8a17 = "hyp. tangent"; // string xref
    const char* s_222877 = "arc hyp. tangent"; // string xref
    const char* s_26806d = "Convert float to int64"; // string xref
    const char* s_1eb849 = "packInt2x32"; // string xref
    const char* s_25a024 = "Convert float16_t to int16_t"; // string xref
    const char* s_2354fb = "log2"; // string xref
    const char* s_270461 = "Convert float to int"; // string xref
    const char* s_22278e = "Pre-Decrement"; // string xref
    const char* s_22c629 = "Convert uint16_t to bool"; // string xref
    const char* s_1dcf1f = "Convert float16_t to int64"; // string xref
    const char* s_222888 = "Ceiling"; // string xref
    const char* s_23c784 = "isinf"; // string xref
    const char* s_1ce6d6 = "unpackUnorm2x16"; // string xref
    const char* s_260635 = "noise"; // string xref
    const char* s_27043b = "Post-Decrement"; // string xref
    const char* s_196a59 = "Convert int64 to int"; // string xref
    const char* s_22c68d = "Convert pointer to uint64_t"; // string xref
    const char* s_1b4aaa = "Convert int to uint16_t"; // string xref
    const char* s_1dc729 = "subgroupElect"; // string xref
    const char* s_22c642 = "Convert uint64 to bool"; // string xref
    const char* s_1a3f0f = "Convert uint to double"; // string xref
    const char* s_1ebf8b = "Convert uint8_t to float16_t"; // string xref
    const char* s_19cb61 = "float16BitsToUint16"; // string xref
    const char* s_1c0c15 = "unpackUint2x16"; // string xref
    const char* s_23cff6 = "Convert uint to float16_t"; // string xref
    const char* s_2113b5 = "transpose"; // string xref
    const char* s_19d14a = "Convert int16_t to uint64"; // string xref
    const char* s_1f34f7 = "Convert uint to float"; // string xref
    const char* s_1900f2 = "Convert uint64 to uint8_t"; // string xref
    const char* s_1a3799 = "int64BitsToDouble"; // string xref
    const char* s_222826 = "Convert uvec2 to acceleration strucuture "; // string xref
    const char* s_25264e = "uint16BitsToFloat16"; // string xref
    const char* s_25266e = "unpack32"; // string xref
    const char* s_2598cf = "unpack8"; // string xref
    const char* s_22280c = "Convert double to int16_t"; // string xref
    const char* s_1eb7c7 = "subgroupBallotFindMSB"; // string xref
    const char* s_1fa4e8 = "dPdxCoarse"; // string xref
    const char* s_23d04a = "Convert float to uint"; // string xref
    const char* s_1acd41 = "Convert int to int16_t"; // string xref
    const char* s_21c411 = "Convert double to int64"; // string xref
    const char* s_1eb837 = "doubleBitsToInt64"; // string xref
    const char* s_20b0de = "subgroupAll"; // string xref
    const char* s_24ba2f = "unpackHalf2x16"; // string xref
    const char* s_1c8215 = "subgroupClusteredAdd"; // string xref
    const char* s_21be00 = "uint64BitsToDouble"; // string xref
    const char* s_202956 = "Convert float to uint8_t"; // string xref
    const char* s_24babd = "packInt2x16"; // string xref
    const char* s_267370 = "subgroupShuffle"; // string xref
    const char* s_25a076 = "dPdyCoarse"; // string xref
    const char* s_196a6e = "Convert int64 to double"; // string xref
    const char* s_1cefdd = "UnpackDouble2x32"; // string xref
    const char* s_1ce6fb = "subgroupClusteredMul"; // string xref
    const char* s_1ce6e6 = "subgroupExclusiveAdd"; // string xref
    const char* s_24c17f = "Convert int8_t to float16_t"; // string xref
    const char* s_1e49bf = "subgroupShuffleDown"; // string xref
    const char* s_24c19b = "Convert int16_t to int"; // string xref
    const char* s_1b4a3f = "Convert bool to uint16_t"; // string xref
    const char* s_20b857 = "hyp. cosine"; // string xref
    const char* s_25fe25 = "unpackInt2x16"; // string xref
    const char* s_1acda8 = "hyp. sine"; // string xref
    const char* s_252662 = "packInt4x16"; // string xref
    const char* s_2820c7 = "Convert uint16_t to double"; // string xref
    const char* s_2353cf = "subgroupClusteredOr"; // string xref
    const char* s_1c8204 = "subgroupAllEqual"; // string xref
    const char* s_267380 = "subgroupInclusiveMin"; // string xref
    const char* s_28208c = "Negate value"; // string xref
    const char* s_1f356d = "Convert float16_t to int"; // string xref
    const char* s_243013 = "subgroupAdd"; // string xref
    const char* s_20b825 = "Convert float16_t to uint"; // string xref
    const char* s_24ba5f = "subgroupPartitionedMinNV"; // string xref
    const char* s_196a86 = "Convert double to uint16_t"; // string xref
    const char* s_1fa4cf = "Convert uint64 to int8_t"; // string xref
    const char* s_1f2ef3 = "unpackInt4x16"; // string xref
    const char* s_1f358f = "PackDouble2x32"; // string xref
    const char* s_22c61d = "copy object"; // string xref
    const char* s_1e49d3 = "subgroupQuadBroadcast"; // string xref
    const char* s_1c1367 = "Convert double to uint64"; // string xref
    const char* s_1e4a45 = "pack16"; // string xref
    const char* s_23c6a5 = "subgroupInclusiveOr"; // string xref
    const char* s_1900de = "Convert uint to int"; // string xref
    const char* s_282165 = "maxInvocations"; // string xref
    const char* s_1ac561 = "floatBitsToInt"; // string xref
    const char* s_24ba1f = "unpackSnorm2x16"; // string xref
    const char* s_1ebfbe = "Convert uint to uint8_t"; // string xref
    const char* s_2820ad = "Convert uint8_t to int8_t"; // string xref
    const char* s_26fdd2 = "subgroupExclusiveMax"; // string xref
    const char* s_1d6666 = "Convert uint16_t to int"; // string xref
    const char* s_28181d = "log"; // string xref
    const char* s_252ddd = "Convert uint64 to double"; // string xref
    const char* s_222890 = "addInvocationsInclusiveScan"; // string xref
    const char* s_2435ea = "Convert int64 to uint8_t"; // string xref
    const char* s_24ba3e = "subgroupMax"; // string xref
    const char* s_282157 = "arc sine"; // string xref
    const char* s_1c0c24 = "unpackFloat2x16"; // string xref
    const char* s_1a3716 = "packHalf2x16"; // string xref
    const char* s_211398 = "pack32"; // string xref
    const char* s_21bd71 = "subgroupBallotBitCount"; // string xref
    const char* s_24361e = "Convert float to uint16_t"; // string xref
    const char* s_1ebff0 = "dPdy"; // string xref
    const char* s_259843 = "subgroupShuffleXor"; // string xref
    const char* s_26fdb2 = "subgroupBallotInclusiveBitCount"; // string xref
    const char* s_18f9e9 = "subgroupPartitionedXorNV"; // string xref
    const char* s_2353ba = "subgroupClusteredAnd"; // string xref
    const char* s_1f2ea8 = "subgroupPartitionedMulNV"; // string xref
    const char* s_202983 = "addInvocationsExclusiveScan"; // string xref
    const char* s_2353f7 = "subgroupPartitionedExclusiveOrNV"; // string xref
    const char* s_1b3061 = "subgroupShuffleUp"; // string xref
    const char* s_1b4ad1 = "maxInvocationsNonUniform"; // string xref
    const char* s_19cad3 = "subgroupPartitionedExclusiveMinNV"; // string xref
    const char* s_22bd9f = "subgroupQuadSwapVertical"; // string xref
    const char* s_1fa519 = "maxInvocationsExclusiveScanNonUniform"; // string xref
    const char* s_1fa4f3 = "minInvocationsExclusiveScanNonUniform"; // string xref
    const char* s_24b980 = "fwidthFine"; // string xref
    const char* s_1ac652 = "unpack16"; // string xref
    const char* s_25fd60 = "subgroupPartitionedMaxNV"; // string xref
    const char* s_1cde35 = "any"; // string xref
    const char* s_1cefee = "addInvocationsExclusiveScanNonUniform"; // string xref
    const char* s_211b06 = "Convert uint8_t to int16_t"; // string xref
    const char* s_28210d = "Convert int64 to int8_t"; // string xref
    const char* s_2597fe = "interpolateAtCentroid"; // string xref
    const char* s_18faa0 = "EmitStreamVertex"; // string xref
    const char* s_252680 = "textureQueryLod"; // string xref
    const char* s_2525d3 = "subgroupPartitionedOrNV"; // string xref
    const char* s_25a0a4 = "maxInvocationsInclusiveScan"; // string xref
    const char* s_2023b3 = "textureSamples"; // string xref
    const char* s_1c1380 = "mbcnt"; // string xref
    const char* s_24ba11 = "packUnorm2x16"; // string xref
    const char* s_282125 = "Convert uint64 to int"; // string xref
    const char* s_1acdd9 = "minInvocationsNonUniform"; // string xref
    const char* s_1ac570 = "subgroupBallot"; // string xref
    const char* s_1ce7f0 = "exp2"; // string xref
    const char* s_1ebf73 = "Convert int8_t to float"; // string xref
    const char* s_25fd79 = "subgroupPartitionedExclusiveAddNV"; // string xref
    const char* s_1c828f = "EndStreamPrimitive"; // string xref
    const char* s_1eb7dd = "subgroupClusteredMin"; // string xref
    const char* s_22bd8a = "sparseTexelsResident"; // string xref
    const char* s_202357 = "subgroupAny"; // string xref
    const char* s_196298 = "subgroupClusteredMax"; // string xref
    const char* s_2680a2 = "addInvocations"; // string xref
    const char* s_252e12 = "clip"; // string xref
    const char* s_1bab03 = "addInvocationsInclusiveScanNonUniform"; // string xref
    const char* s_25a081 = "readFirstInvocation"; // string xref
    const char* s_26fe22 = "subgroupPartitionedInclusiveOrNV"; // string xref
    const char* s_28175d = "subgroupPartitionedInclusiveMulNV"; // string xref
    const char* s_1f2ddf = "fragmentFetchAMD"; // string xref
    const char* s_1acd0c = "Convert uint8_t to int64"; // string xref
    const char* s_1f9cd2 = "doubleBitsToUint64"; // string xref
    const char* s_2354b8 = "bitCount"; // string xref
    const char* s_1acda0 = "tangent"; // string xref
    const char* s_25a0c0 = "Construct reference type"; // string xref
    const char* s_1b3183 = "trunc"; // string xref
    const char* s_19011b = "array length"; // string xref
    const char* s_267fde = "Convert bool to int8_t"; // string xref
    const char* s_243638 = "log10"; // string xref
    const char* s_25a041 = "Convert double to float"; // string xref
    const char* s_1b310a = "unpackUint4x16"; // string xref
    const char* s_23d010 = "Convert float16_t to uint16_t"; // string xref
    const char* s_2598c8 = "pack64"; // string xref
    const char* s_1ba272 = "textureQueryLevels"; // string xref
    const char* s_19cb75 = "allInvocations"; // string xref
    const char* s_2525eb = "subgroupPartitionedInclusiveMinNV"; // string xref
    const char* s_20b86c = "isfinite"; // string xref
    const char* s_222180 = "findMSB"; // string xref
    const char* s_24363e = "rcp"; // string xref
    const char* s_1dcf65 = "saturate"; // string xref
    const char* s_21bd94 = "subgroupInclusiveXor"; // string xref
    const char* s_202363 = "subgroupInclusiveAdd"; // string xref
    const char* s_196aad = "cubeFaceCoord"; // string xref
    const char* s_211af0 = "Convert int8_t to int"; // string xref
    const char* s_1ba266 = "textureSize"; // string xref
    const char* s_211303 = "subgroupInclusiveAnd"; // string xref
    const char* s_1acdf2 = "maxInvocationsInclusiveScanNonUniform"; // string xref
    const char* s_19ca9f = "subgroupQuadSwapHorizontal"; // string xref
    const char* s_2598e7 = "subpassLoad"; // string xref
    const char* s_1f9c7d = "subgroupPartitionedInclusiveAndNV"; // string xref
    const char* s_25fc7c = "countTrailingZeros"; // string xref
    const char* s_26fe00 = "subgroupPartitionedInclusiveAddNV"; // string xref
    const char* s_1ac57f = "subgroupPartitionedInclusiveMaxNV"; // string xref
    const char* s_26ff0b = "imageLoad"; // string xref
    const char* s_21bc96 = "fragmentMaskFetchAMD"; // string xref
    const char* s_2111f6 = "countLeadingZeros"; // string xref
    const char* s_1f9c9f = "colorAttachmentReadEXT"; // string xref
    const char* s_1acdc9 = "bitFieldReverse"; // string xref
    const char* s_26ff03 = "findLSB"; // string xref
    const char* s_2704a8 = "AtomicCounterIncrement"; // string xref
    const char* s_235b98 = "cubeFaceIndex"; // string xref
    const char* s_1fa49d = "Convert uint to uint64"; // string xref
    const char* s_20b7ee = "Convert uint8_t to uint64"; // string xref
    const char* s_2435d1 = "Convert uint8_t to float"; // string xref
    const char* s_222850 = "arc cosine"; // string xref
    const char* s_24c1f6 = "UnpackUnorm4x8"; // string xref
    const char* s_190128 = "minInvocationsInclusiveScan"; // string xref
    const char* s_25a067 = "UnpackSnorm4x8"; // string xref
    const char* s_282160 = "dPdx"; // string xref
    const char* s_23c753 = "anyInvocation"; // string xref
    const char* s_196aa6 = "ballot"; // string xref
    const char* s_1f2e93 = "subgroupExclusiveXor"; // string xref
    const char* s_1baaf1 = "imageQuerySamples"; // string xref
    const char* s_20b0ff = "subgroupExclusiveOr"; // string xref
    const char* s_281744 = "subgroupBallotBitExtract"; // string xref
    const char* s_21bd5f = "subgroupBroadcast"; // string xref
    const char* s_1b302b = "subgroupBallotExclusiveBitCount"; // string xref
    const char* s_1ba182 = "subgroupBroadcastFirst"; // string xref
    const char* s_243642 = "minInvocationsExclusiveScan"; // string xref
    const char* s_22be85 = "subpassLoadMS"; // string xref
    const char* s_1ce710 = "subgroupPartitionedExclusiveMulNV"; // string xref
    const char* s_1a3f4f = "minInvocationsInclusiveScanNonUniform"; // string xref
    const char* s_1ba1a5 = "subgroupPartitionedInclusiveXorNV"; // string xref
    const char* s_1b4ac2 = "imageQuerySize"; // string xref
    const char* s_21c429 = "AtomicCounter"; // string xref
    const char* s_1acdb2 = "AtomicCounterDecrement"; // string xref
    const char* s_22211c = "subgroupInverseBallot"; // string xref
    const char* s_24c205 = "maxInvocationsExclusiveScan"; // string xref
    const char* s_28213b = "Convert float16_t to int8_t"; // string xref
    const char* s_26ff15 = "all"; // string xref
    const char* s_26fe43 = "subgroupPartitionedExclusiveAndNV"; // string xref
    const char* s_1f3554 = "Convert uint64 to uint16"; // string xref
    const char* s_1ce7f5 = "normalize"; // string xref
    const char* s_1b304b = "subgroupBallotFindLSB"; // string xref
    const char* s_2220f9 = "fwidthCoarse"; // string xref
    const char* s_26800d = "Convert int8_t to uint64"; // string xref
    const char* s_252d53 = "Convert uint8_t to bool"; // string xref
    const char* s_19caba = "subgroupPartitionedAddNV"; // string xref
    const char* s_27048c = "Convert uint64_t to pointer"; // string xref
    const char* s_1b3088 = "subgroupPartitionedExclusiveMaxNV"; // string xref
    const char* s_196a2b = "Convert double to bool"; // string xref
    const char* s_24c1df = "Convert uint64 to uint"; // string xref
    const char* s_2227d3 = "Convert uint16_t to float16_t"; // string xref
    const char* s_2435bb = "Convert int64 to bool"; // string xref
    const char* s_26809c = "Floor"; // string xref
    const char* s_1a3f42 = "PackSnorm4x8"; // string xref
    const char* s_259901 = "allInvocationsEqual"; // string xref
    const char* s_1d5fa4 = "subgroupPartitionedExclusiveXorNV"; // string xref
    const char* s_26063b = "addInvocationsNonUniform"; // string xref
    const char* s_2353e3 = "subgroupPartitionNV"; // string xref
    const char* s_24b958 = "fwidth"; // string xref
    const char* s_1dc742 = "subgroupExclusiveAnd"; // string xref
    const char* s_270476 = "Convert double to int"; // string xref
    const char* s_26fde7 = "subgroupQuadSwapDiagonal"; // string xref
    const char* s_21bd88 = "subgroupMul"; // string xref
    const char* s_25a095 = "minInvocations"; // string xref
    const char* s_1d5f98 = "subgroupMin"; // string xref
    const char* s_24ba4a = "subgroupClusteredXor"; // string xref
    const char* s_1acd6f = "Convert float to double"; // string xref
    const char* s_2353ae = "subgroupAnd"; // string xref
    const char* s_19632e = "exp"; // string xref
    const char* s_1f34dc = "Convert uint16_t to int8_t"; // string xref
    const char* s_1c822a = "subgroupPartitionedAndNV"; // string xref
    const char* s_1b30fd = "packUint4x16"; // string xref
    const char* s_1b3073 = "subgroupInclusiveMax"; // string xref
    const char* s_202976 = "inverse sqrt"; // string xref
    const char* s_1dc737 = "subgroupOr"; // string xref
    const char* s_22be93 = "sqrt"; // string xref
    const char* s_18fae0 = "determinant"; // string xref
    const char* s_20b0ea = "subgroupExclusiveMul"; // string xref
    const char* s_23c6b9 = "subgroupExclusiveMin"; // string xref
    const char* s_24c1c9 = "Convert uint to int64"; // string xref
    const char* s_20b863 = "dPdxFine"; // string xref
    const char* s_268026 = "Convert int to int8_t"; // string xref
    const char* s_1ba257 = "roundEven"; // string xref
    const char* s_1b9323 = "round"; // string xref
    const char* s_22c659 = "Convert bool to float16_t"; // string xref
    const char* s_22015e = "length"; // string xref
    const char* s_25fd4b = "subgroupInclusiveMul"; // string xref
    const char* s_196aa1 = "Sign"; // string xref
    const char* s_211b3d = "PackUnorm4x8"; // string xref
    const char* s_268054 = "Convert float to int16_t"; // string xref
    const char* s_2820f8 = "Convert int to float"; // string xref
    const char* s_1ac644 = "packFloat2x16"; // string xref
    const char* s_19010c = "Absolute value"; // string xref
    const char* s_22be98 = "inverse"; // string xref
    const char* s_23d02e = "Convert float16_t to double"; // string xref
    const char* s_1ba199 = "subgroupXor"; // string xref
    const char* s_1c1350 = "Convert double to uint"; // string xref
    const char* s_1e4a7c = "isnan"; // string xref
    const char* s_1ebfd6 = "Convert double to uint8_t"; // string xref
    const char* s_1acd58 = "Convert int64 to float"; // string xref
    const char* s_1d601a = "float16BitsToInt16"; // string xref
    const char* s_22c673 = "Convert int16_t to double"; // string xref
    const char* s_252db0 = "Convert int16_t to float"; // string xref
    const char* s_267362 = "packSnorm2x16"; // string xref
    const char* s_1c1337 = "Convert uint to uint16_t"; // string xref
    const char* s_1f2e75 = "intBitsToFloat"; // string xref
    const char* s_1f3586 = "Fraction"; // string xref
    const char* s_25a00a = "Convert uint64 to int16_t"; // string xref
    const char* s_1c89e6 = "Convert uint8_t to uint"; // string xref
    const char* s_267ff5 = "Convert bool to uint8_t"; // string xref
    const char* s_20293a = "Convert uint64 to float16_t"; // string xref
    const char* s_23539e = "uintBitsToFloat"; // string xref
    const char* s_22285b = "arc tangent"; // string xref
    const char* s_1d66b6 = "dPdyFine"; // string xref
    const char* s_19cb84 = "degrees"; // string xref
    const char* s_2435a6 = "Convert uint to bool"; // string xref
    const char* s_1d602d = "packUint2x32"; // string xref
    const char* s_268084 = "Convert float to uint64"; // string xref
    const char* s_1ba239 = "packUint2x16"; // string xref
    const char* s_252df6 = "Convert float16_t to uint64"; // string xref
    const char* s_20b7c0 = "Convert int8_t to uint"; // string xref
    const char* s_222867 = "arc hyp. cosine"; // string xref
    const char* s_1dc833 = "unpackUint2x32"; // string xref
    const char* s_1ba22b = "unpackInt2x32"; // string xref
    const char* s_1baad9 = "Convert uint64 to float"; // string xref
}
