// FUNCTION: sub_86fcdc
// LIBRARY: libarkernel3.so
// RVA: 0x86fcdc | SIZE: 4096 bytes | SHA256: 8354346B7E3805E0ED24BBB787448963DF3CC8737284EE12467497938C88706A
// SEMANTIC_LABEL: HAIR_COLOR_PIPELINE | CONFIDENCE: HIGH_CONFIDENCE
// IMPORTED_APIS: None
// STRING_XREFS: AREffect type, UNDEFINE, MAKEUP, NOMAKEUP, STICKER, NOSTICKER, NUM, Blend Mode, BlendNone, BlendNormal, BlendDissolve, BlendDarken, BlendMultiply, BlendColorBurn, BlendLinearBurn, BlendDarkerColor, BlendLighten, BlendScreen, BlendColorDodge, BlendLinearDodgeAdd, BlendLighterColor, BlendOverlay, BlendSoftLight, BlendHardLight, BlendVividLight, BlendLinearLight, BlendPinLight, BlendHardMix, BlendDifference, BlendExlusion, BlendSubtract, BlendDivide, BlendHue, BlendSaturation, BlendColor, BlendLuminosity, BlendIntensity, BlendMaxNum, Filter type, None, BaseTexture, ColorNormal, TextureNormal, ColorMultiply, TextureMultiply, ColorSoftlight, TextureSoftligh, ColorLight, TextureLight, ColorScreen, TextureScreen, ColorOverlay, TextureOverlay, ColorBurn, TextureBurn, ColorSunshine, TextureSunshine, ColorDarken, TextureDarken, ColorColor, TextureColor, ColorIntensity, TextureIntensit, MaskVideo, DeEyeBrow, 3DMeshNormal, 3DMultiply, 3DIntensity, MaskHightLight, MaskShadow, ColorLipstick, TextureLipstick, ColorHardLight, TextureHardLigh, ColorDodge, TextureDodge, MapGlobal, ColorMap, MapMask, ColorMapLipstic, MapMaskLipstick, White2Black, Comic, GaussianBlurH, GaussianBlurV, 3DEyeLash, SegmentDepthMas, Common, BlendModePs, Num, MU Type, undefined, common, mouth, eyebrow, eye, cheek, accessories, hair, nose, other, lift, logo_preview, logo_preview_mask, logo_ml, count, LocateMethod Type, ALIGN_LEFT_BOTTOM, SINGLE, SCREEN, TRIANGLES, REFERENCES, TRACKING_RECT, SPARSE_TRIANGLE, TRIANGLES_LEFT_EYE, TRIANGLES_RIGHT_EYE, TRIANGLES_LEFT_EYEBROW, TRIANGLES_RIGHT_EYEBROW, TRIANGLES_DYNAMIC, FULL_SCREEN, TRIANGLES_LEFT_EYESHADOW, TRIANGLES_RIGHT_EYESHADOW, REFERENCES_ALIGN, SELF_TEST_ALIGN_IN_CENTER, SELF_TEST_ALIGN_OUT_CENTER, ALIGN_LEFT_TOP, ALIGN_RIGHT_TOP, ALIGN_LEFT_BOTTOM, ALIGN_RIGHT_BOTTOM, ALIGN_MIDDLE_TOP

#include <stdint.h>
#include <jni.h>

// Reconstructed C++ Native Implementation
extern "C" JNIEXPORT void* sub_86fcdc(JNIEnv* env, jobject thiz) {
    // Function entrypoint at 0x86fcdc
    // Literal reference: "AREffect type"
    // Literal reference: "UNDEFINE"
    // Literal reference: "MAKEUP"
    // Literal reference: "NOMAKEUP"
    // Literal reference: "STICKER"
    // Literal reference: "NOSTICKER"
    // Literal reference: "NUM"
    // Literal reference: "Blend Mode"
    // Literal reference: "BlendNone"
    // Literal reference: "BlendNormal"
    // Literal reference: "BlendDissolve"
    // Literal reference: "BlendDarken"
    // Literal reference: "BlendMultiply"
    // Literal reference: "BlendColorBurn"
    // Literal reference: "BlendLinearBurn"
    // Literal reference: "BlendDarkerColor"
    // Literal reference: "BlendLighten"
    // Literal reference: "BlendScreen"
    // Literal reference: "BlendColorDodge"
    // Literal reference: "BlendLinearDodgeAdd"
    // Literal reference: "BlendLighterColor"
    // Literal reference: "BlendOverlay"
    // Literal reference: "BlendSoftLight"
    // Literal reference: "BlendHardLight"
    // Literal reference: "BlendVividLight"
    // Literal reference: "BlendLinearLight"
    // Literal reference: "BlendPinLight"
    // Literal reference: "BlendHardMix"
    // Literal reference: "BlendDifference"
    // Literal reference: "BlendExlusion"
    // Literal reference: "BlendSubtract"
    // Literal reference: "BlendDivide"
    // Literal reference: "BlendHue"
    // Literal reference: "BlendSaturation"
    // Literal reference: "BlendColor"
    // Literal reference: "BlendLuminosity"
    // Literal reference: "BlendIntensity"
    // Literal reference: "BlendMaxNum"
    // Literal reference: "Filter type"
    // Literal reference: "None"
    // Literal reference: "BaseTexture"
    // Literal reference: "ColorNormal"
    // Literal reference: "TextureNormal"
    // Literal reference: "ColorMultiply"
    // Literal reference: "TextureMultiply"
    // Literal reference: "ColorSoftlight"
    // Literal reference: "TextureSoftligh"
    // Literal reference: "ColorLight"
    // Literal reference: "TextureLight"
    // Literal reference: "ColorScreen"
    // Literal reference: "TextureScreen"
    // Literal reference: "ColorOverlay"
    // Literal reference: "TextureOverlay"
    // Literal reference: "ColorBurn"
    // Literal reference: "TextureBurn"
    // Literal reference: "ColorSunshine"
    // Literal reference: "TextureSunshine"
    // Literal reference: "ColorDarken"
    // Literal reference: "TextureDarken"
    // Literal reference: "ColorColor"
    // Literal reference: "TextureColor"
    // Literal reference: "ColorIntensity"
    // Literal reference: "TextureIntensit"
    // Literal reference: "MaskVideo"
    // Literal reference: "DeEyeBrow"
    // Literal reference: "3DMeshNormal"
    // Literal reference: "3DMultiply"
    // Literal reference: "3DIntensity"
    // Literal reference: "MaskHightLight"
    // Literal reference: "MaskShadow"
    // Literal reference: "ColorLipstick"
    // Literal reference: "TextureLipstick"
    // Literal reference: "ColorHardLight"
    // Literal reference: "TextureHardLigh"
    // Literal reference: "ColorDodge"
    // Literal reference: "TextureDodge"
    // Literal reference: "MapGlobal"
    // Literal reference: "ColorMap"
    // Literal reference: "MapMask"
    // Literal reference: "ColorMapLipstic"
    // Literal reference: "MapMaskLipstick"
    // Literal reference: "White2Black"
    // Literal reference: "Comic"
    // Literal reference: "GaussianBlurH"
    // Literal reference: "GaussianBlurV"
    // Literal reference: "3DEyeLash"
    // Literal reference: "SegmentDepthMas"
    // Literal reference: "Common"
    // Literal reference: "BlendModePs"
    // Literal reference: "Num"
    // Literal reference: "MU Type"
    // Literal reference: "undefined"
    // Literal reference: "common"
    // Literal reference: "mouth"
    // Literal reference: "eyebrow"
    // Literal reference: "eye"
    // Literal reference: "cheek"
    // Literal reference: "accessories"
    // Literal reference: "hair"
    // Literal reference: "nose"
    // Literal reference: "other"
    // Literal reference: "lift"
    // Literal reference: "logo_preview"
    // Literal reference: "logo_preview_mask"
    // Literal reference: "logo_ml"
    // Literal reference: "count"
    // Literal reference: "LocateMethod Type"
    // Literal reference: "ALIGN_LEFT_BOTTOM"
    // Literal reference: "SINGLE"
    // Literal reference: "SCREEN"
    // Literal reference: "TRIANGLES"
    // Literal reference: "REFERENCES"
    // Literal reference: "TRACKING_RECT"
    // Literal reference: "SPARSE_TRIANGLE"
    // Literal reference: "TRIANGLES_LEFT_EYE"
    // Literal reference: "TRIANGLES_RIGHT_EYE"
    // Literal reference: "TRIANGLES_LEFT_EYEBROW"
    // Literal reference: "TRIANGLES_RIGHT_EYEBROW"
    // Literal reference: "TRIANGLES_DYNAMIC"
    // Literal reference: "FULL_SCREEN"
    // Literal reference: "TRIANGLES_LEFT_EYESHADOW"
    // Literal reference: "TRIANGLES_RIGHT_EYESHADOW"
    // Literal reference: "REFERENCES_ALIGN"
    // Literal reference: "SELF_TEST_ALIGN_IN_CENTER"
    // Literal reference: "SELF_TEST_ALIGN_OUT_CENTER"
    // Literal reference: "ALIGN_LEFT_TOP"
    // Literal reference: "ALIGN_RIGHT_TOP"
    // Literal reference: "ALIGN_LEFT_BOTTOM"
    // Literal reference: "ALIGN_RIGHT_BOTTOM"
    // Literal reference: "ALIGN_MIDDLE_TOP"
    return (void*)0;
}
