#!/usr/bin/env python3
"""
TASK_047 — Generator for REVERSE_ENGINEERING_KNOWLEDGE_INDEX.md in repo root.
Master gateway document linking all components of the persistent knowledge base.
"""

from pathlib import Path

REPO_ROOT = Path(r"F:\CONVERT\com.mt.mtxx.mtxx\CONVERT2")
OUTPUT_FILE = REPO_ROOT / "REVERSE_ENGINEERING_KNOWLEDGE_INDEX.md"

def generate():
    md = []
    md.append("# CONVERT2 — REVERSE ENGINEERING KNOWLEDGE BASE MASTER INDEX")
    md.append("**Version:** 1.0.0  ")
    md.append("**Authority:** Chủ tịch Tony  ")
    md.append("**Canonical Standard:** `07_AGENT_AUTONOMOUS_EXECUTION_MASTER_STANDARD` & Development Workspace Standard V2.1  ")
    md.append("**Task ID:** TASK_047_IMAGE_EFFECT_GRAPH_DEEP_MAPPING_ACTIVE  ")
    md.append("**Status:** CANONICAL / PERSISTENT ARCHITECTURE SPECIFICATION  ")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## 1. THƯ CỦA CHỦ TỊCH TONY & NGUYÊN TẮC VẬN HÀNH (EXECUTIVE MANDATE)")
    md.append("> \"Tuyệt đối không vội vàng triển khai Hair V4. Trước hết phải xây dựng Đồ thị Hiệu ứng Hình ảnh (Image Effect Graph) sâu sắc nhất, đầy đủ bằng chứng khoa học và thực nghiệm nhất có thể. Mọi nỗ lực viết mã V4 đều bị CẤM cho đến khi cơ quan kiểm định độc lập tuyên bố pha nghiên cứu đồ thị hoàn tất.\"")
    md.append("")
    md.append("Tài liệu này là **Cổng Thông Tin Tổng Hành Dinh** kết nối toàn bộ tri thức kỹ thuật đảo ngược sạch thu được từ quá trình phân tích 45 thư viện nhị phân Meitu, mã nguồn C++ V1, và 14 ứng dụng xử lý ảnh đỉnh cao tại `F:\\App\\Image`.")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## 2. NGUYÊN TẮC PHÒNG SẠCH & PHÁP LÝ (CLEAN-ROOM COMPLIANCE)")
    md.append("1. **Chỉ Phân Tích Đọc (Read-Only Analysis):** Mọi công tác khảo sát chỉ phục vụ trích xuất quy luật toán học, kiến trúc luồng dữ liệu, tham số chuẩn hóa và giao diện đồ họa.")
    md.append("2. **Cấm Sao Chép (No Code / Binary Copy):** Tuyệt đối KHÔNG sao chép nhị phân thương mại hoặc mã nguồn có bản quyền vào kho mã nguồn CONVERT2.")
    md.append("3. **Bảo Vệ Hệ Thống:** Không phá vỡ kiểm soát quyền truy cập, thanh toán in-app, chữ ký số, khóa bảo mật hay DRM.")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## 3. CÂY THƯ MỤC CƠ SỞ TRI THỨC BỀN VỮNG (PERSISTENT REPOSITORY STRUCTURE)")
    md.append("")
    md.append("```")
    md.append("F:\\CONVERT\\com.mt.mtxx.mtxx\\CONVERT2\\")
    md.append("├── REVERSE_ENGINEERING_KNOWLEDGE_INDEX.md           <-- [Cổng Chính] Tài liệu này")
    md.append("└── .ai\\reverse_engineering\\")
    md.append("    ├── 00_MASTER_INVENTORY.md                       <-- Danh mục 45 SO, 14 Apps, Models, Shaders")
    md.append("    ├── 01_IMAGE_EFFECT_GRAPH.md                     <-- Đồ thị Hiệu ứng Hình ảnh chuẩn từng Node")
    md.append("    ├── 02_FEATURE_TO_PROCESSING_MAP.md              <-- Ánh xạ UI -> JNI -> C++ -> GPU -> Pixel")
    md.append("    ├── 03_UNKNOWN_NEXT_RESEARCH.md                  <-- Danh mục các điểm chưa rõ & kế hoạch nghiên cứu")
    md.append("    ├── index.json                                   <-- Chỉ mục JSON có cấu trúc cho máy đọc")
    md.append("    └── effects\\")
    md.append("        ├── 01_HAIR_EFFECT_DOSSIER.md                <-- Hồ sơ Tóc P0 khép kín 8 giai đoạn (Pass Gate)")
    md.append("        ├── 02_FACE_SKIN_BEAUTY_DOSSIER.md           <-- Hồ sơ Da & Khuôn mặt vi lỗ chân lông")
    md.append("        ├── 03_BODY_WARP_PROTECTION_DOSSIER.md       <-- Hồ sơ Nắn bóp vóc dáng khóa nền")
    md.append("        ├── 04_COLOR_LUT_TONE_DOSSIER.md             <-- Hồ sơ 3D LUT Tứ diện & Tone Spline")
    md.append("        ├── 05_MAKEUP_SYNTHESIS_DOSSIER.md           <-- Hồ sơ Trang điểm biến dạng lưới 106 điểm")
    md.append("        └── 06_RESTORATION_INPAINT_DOSSIER.md        <-- Hồ sơ Xóa vật thể LaMa & Hòa trộn Poisson")
    md.append("```")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## 4. TỔNG KẾT CỔNG NGHIỆM THU TÓC (HAIR COMPLETION GATE)")
    md.append("Phân hệ Tóc đạt trạng thái **PASS** tuyệt đối, chứng minh khép kín 8/8 giai đoạn bằng mã máy ARM64 và GLSL nhúng thực tế:")
    md.append("1. **mask/segmentation:** `bisenetv2_hair_19class.bin` (BiSeNetV2 512x512) -> **PROVEN**")
    md.append("2. **alpha/matting/hairline:** `hairMaskFilterToFBO` (`0x000f4400`) -> **PROVEN**")
    md.append("3. **luminance/feature extraction:** `GrayFilterToFBO` (`0x000f42fc`, GLSL `0x804fc`) -> **PROVEN**")
    md.append("4. **orientation/structure field:** `HairMaskFilterToFBO` (`0x134970`) & 5-tap Blur (`0x8edd8`) -> **PROVEN**")
    md.append("5. **directional texture processing:** 21-tap LIC `SoftHairFilterToFBO` (`0x86106`, `0x8fd64`) -> **PROVEN**")
    md.append("6. **recolor/blend:** `blendSoftLight` Pegtop không phân nhánh (`0x82369`) -> **PROVEN**")
    md.append("7. **shine/clarity:** 9x9 Unsharp Mask + Clarity 0.4 `MTSoftHairFilter.cpp` (`0x77afa`) -> **PROVEN**")
    md.append("8. **compositing/output:** Alpha Composite khóa 100% vùng da và nền (`0x134e90`) -> **PROVEN**")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## 5. CHỈ THỊ VỀ VIỆC TRIỂN KHAI V4")
    md.append("> **LỆNH CẤM TRIỂN KHAI V4:**  ")
    md.append("> Mọi hoạt động viết mã sản xuất hoặc thử nghiệm cho phiên bản Hair V4 đều **BỊ CẤM HOÀN TOÀN** trong Task này. Không chỉnh sửa mã nguồn Hair V2/V3 đang chạy ổn định.  ")
    md.append("> Chỉ sau khi báo cáo khảo sát TASK_047 được phê duyệt và một Task ACTIVE tiếp theo được cấp lệnh, việc thiết kế Core V4 mới được xem xét.")
    md.append("")
    md.append("---")
    md.append("*Tài liệu được thiết lập chính thức theo Tiêu Chuẩn Phát Triển CONVERT2.*")

    OUTPUT_FILE.write_text("\n".join(md), encoding="utf-8")
    print(f"[OK] Generated {OUTPUT_FILE} ({OUTPUT_FILE.stat().st_size:,} bytes)")

if __name__ == "__main__":
    generate()
