#!/usr/bin/env python3
"""
TASK_047 — Generator for 02_FEATURE_TO_PROCESSING_MAP.md
Maps user-facing features to technical processing pipelines across UI, JNI, C++ core, GPU shaders, and visual output.
"""

from pathlib import Path

REPO_ROOT = Path(r"F:\CONVERT\com.mt.mtxx.mtxx\CONVERT2")
OUTPUT_FILE = REPO_ROOT / ".ai" / "reverse_engineering" / "02_FEATURE_TO_PROCESSING_MAP.md"

def generate():
    md = []
    md.append("# CONVERT2 — FEATURE TO PROCESSING MAPPING SPECIFICATION")
    md.append("**Version:** 1.0.0  ")
    md.append("**Authority:** Chủ tịch Tony  ")
    md.append("**Canonical Standard:** `07_AGENT_AUTONOMOUS_EXECUTION_MASTER_STANDARD` & Development Workspace Standard V2.1  ")
    md.append("**Task ID:** TASK_047_IMAGE_EFFECT_GRAPH_DEEP_MAPPING_ACTIVE  ")
    md.append("**Status:** CANONICAL / PERSISTENT TECHNICAL KNOWLEDGE BASE  ")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## 1. MỤC TIÊU ÁNH XẠ CHỨC NĂNG (FEATURE MAPPING OBJECTIVES)")
    md.append("Tài liệu này xác lập ma trận ánh xạ xuyên suốt từ thao tác người dùng trên giao diện người dùng Android (UI Touch Event) đi qua các tầng kiến trúc:")
    md.append("1. **Tầng Giao Diện UI / Khung Ứng Dụng (Android Kotlin / Java UI Layer):** Activity, Fragment, Canvas Touch Listener, ViewModel.")
    md.append("2. **Cầu Nối JNI (Java Native Interface Bridge):** Các phương thức `external fun` hoặc lớp JNI chuyên biệt kết nối qua `System.loadLibrary()`.")
    md.append("3. **Lõi Thuật Toán C++ Native (Core C++ Graphics Engine):** Bộ xử lý điểm ảnh chuyên biệt trong `libMTFilterKernel.so`, `libLayerFlow.so`, `libMTBeautyEngine.so`.")
    md.append("4. **Tầng Xử Lý Tăng Tốc GPU & Nơ-ron (GPU Shaders / Neural Inference):** Lệnh vẽ OpenGL ES FBO, shader GLSL, mô hình MNN/TFLite.")
    md.append("5. **Tác Động Thị Giác Trực Tiếp Lên Điểm Ảnh (Visible Effect on Pixels):** Tiêu chuẩn kiểm thử chất lượng mắt thường (Visual Acceptance).")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## 2. MA TRẬN ÁNH XẠ TOÀN DIỆN CÁC TÍNH NĂNG CHỦ CHỐT")
    md.append("")
    md.append("| Mã Tính Năng | Tên Tính Năng Người Dùng | Ứng Dụng Nguồn | Điểm Vào UI (DEX / Class) | Phương Thức JNI Export | Hàm Lõi C++ Native | Shader GPU / Mô Hình AI | Tác Động Thị Giác Điểm Ảnh |")
    md.append("|---|---|---|---|---|---|---|---|")
    md.append("| **FEAT_HAIR_01** | Nhuộm Tóc Tự Nhiên (Hair Color Dye) | Meitu | `com.meitu.hair.HairDyeActivity` | `Java_com_meitu_layerflow_EffectDenseHairDataJNI_nativeSetEffectParam` | `MTFilterKernel::CMTFilterSoftHair::FilterToFBO` | 21-tap LIC Shader (`0x86106`) | Sợi tóc óng mượt, giữ chiều sâu sáng tối, zero lem da mặt |")
    md.append("| **FEAT_HAIR_02** | Làm Dày & Bồng Bềnh Tóc (Hair Fluffy & Volume) | Meitu | `com.meitu.hair.HairFluffyFragment` | `LFEffectDenseHairDataJNI.nativeSetFluffyParam` | `CLFDenseHairProcessor::process (Opcode 2303)` | `hair_fluffy_expand.fs` | Chân tóc nâng cao tự nhiên, không làm méo vòm trán |")
    md.append("| **FEAT_SKIN_01** | Làm Mịn Da Vi Lỗ Chân Lông (Micro-Pore Retouch) | Facetune / Meitu | `com.lightricks.facetune.views.RetouchCanvas` | `Java_com_lightricks_facetune_NativeRetouch_process` | `BilateralFilter::ProcessPoresWithHighBoost` | `facetune_dualpass_skin.frag` | Da sạch thâm đỏ, vi lỗ chân lông hiển thị >=75%, không bệt sơn |")
    md.append("| **FEAT_SKIN_02** | Xóa Khuyết Điểm Tự Nhiên (Blemish Remover) | Facetune | `com.lightricks.facetune.views.PatchCanvas` | `Java_com_lightricks_facetune_NativePatch_clone` | `PoissonCloner::blendLocalPatch` | `poisson_blend_patch.cpp` | Xóa mụn liền mạch, không để lại viền mờ hay đốm loang lổ |")
    md.append("| **FEAT_BODY_01** | Nắn Bóp Eo & Vóc Dáng (Protected Liquify) | Meitu | `com.meitu.beauty.BodyReshapeActivity` | `Java_com_meitu_beauty_BodyEngineJNI_nativeDeformMesh` | `MTBeautyEngine::LiquifyWithProtectionMask` | `body_mesh_warp.vs` | Thon gọn eo/chân, nền tường và gạch đứng yên 100% |")
    md.append("| **FEAT_COLOR_01** | Bộ Lọc Màu 3D LUT Điện Ảnh (Cinema 3D LUT) | VSCO | `com.vsco.cam.views.FilterScroller` | `Java_com_vsco_cam_NativeBridge_applyLUT3D` | `ColorLUT::InterpolateTetrahedral` | `vsco_lut3d_tetrahedral.frag` | Tông màu điện ảnh chuyển tiếp siêu mịn, không vỡ màu da |")
    md.append("| **FEAT_COLOR_02** | Đường Cong Tông Màu Chuyên Nghiệp (Tone Curves) | Adobe Lightroom | `com.adobe.lrmobile.curves.CurveView` | `Java_com_adobe_creativesdk_foundation_internal_net_NativeBridge_setCurve` | `ACR_ApplyCubicSplineToneCurveFloat32` | `acr_tone_curve_32f.frag` | Tăng tương phản vùng tối/sáng mượt mà không bị cháy sáng |")
    md.append("| **FEAT_MAKE_01** | Đánh Son Môi & Nhũ Bóng (Lipstick & Specular) | Meitu / BeautyPlus | `com.meitu.makeup.LipstickFragment` | `Java_com_meitu_makeup_MakeupEngineJNI_applyMaterial` | `ARKernelInterface::RenderMakeupLayer` | `makeup_lip_glitter.fs` | Màu môi sắc nét theo nếp gấp, phản quang nhũ bóng 3D |")
    md.append("| **FEAT_REST_01** | Xóa Người & Vật Thể LaMa (LaMa Inpainting) | SnapEdit | `snapedit.app.remove.EraserActivity` | `Java_snapedit_app_NativeInpaint_runLaMa` | `TfLiteInterpreterInvoke` | `lama_inpaint_fp16.tflite` | Khuyết thiếu được bù đắp bằng chất liệu tự nhiên hoàn hảo |")
    md.append("")
    md.append("---")
    md.append("")
    md.append("## 3. CHI TIẾT LUỒNG DỮ LIỆU ĐIỂM ẢNH TỪNG TÍNH NĂNG")
    md.append("")
    md.append("### 3.1 Luồng Nhuộm Tóc (FEAT_HAIR_01)")
    md.append("```mermaid")
    md.append("sequenceDiagram")
    md.append("    autonumber")
    md.append("    actor User as Người dùng chạm thanh trượt màu")
    md.append("    participant UI as HairColorFragment.kt")
    md.append("    participant JNI as LFEffectDenseHairDataJNI.java")
    md.append("    participant Cpp as CLFDenseHairProcessor (libLayerFlow.so)")
    md.append("    participant Shader as CMTFilterSoftHair (libMTFilterKernel.so)")
    md.append("    participant GPU as Mali-G72 FBO Textures")
    md.append("")
    md.append("    User->>UI: Chọn màu Rose Gold (Mã 2305), Cường độ 80%")
    md.append("    UI->>JNI: nativeSetDyeHairEffectParam(ptr, 2305, 0.80f, lutData)")
    md.append("    JNI->>Cpp: setDyeHairMaterialInfo(RoseGoldInfo)")
    md.append("    Cpp->>Shader: FilterToFBO(srcTex, dstFBO, isFlip)")
    md.append("    Shader->>GPU: Pass 1: Luminance (BT.601) -> FBO1")
    md.append("    Shader->>GPU: Pass 2: Double-Angle Structure Tensor -> FBO2")
    md.append("    Shader->>GPU: Pass 3 & 4: Separable Gaussian Blur (Weights[5]) -> FBO4")
    md.append("    Shader->>GPU: Pass 5: 21-tap Line-Integral Convolution -> FBO5")
    md.append("    Shader->>GPU: Pass 6: Soft Light Pegtop Recolor + Clarity Boost (0.4)")
    md.append("    Shader->>GPU: Pass 7: Mix with Hair Mask -> Final Screen FBO")
    md.append("    GPU-->>User: Màn hình hiển thị lọn tóc Rose Gold óng ả, không lem da")
    md.append("```")
    md.append("")
    md.append("### 3.2 Luồng Làm Mịn Da Vi Lỗ Chân Lông (FEAT_SKIN_01)")
    md.append("1. **UI Event:** Người dùng vuốt thanh trượt \"Mịn da\" lên 60%, bật chế độ \"Bảo vệ lỗ chân lông\".")
    md.append("2. **JNI Call:** Gọi `NativeRetouch.process(smoothStrength=0.6, poreRatio=0.85)`.")
    md.append("3. **C++ Native Separation:**")
    md.append("   - Trích xuất ảnh tần số thấp qua bộ lọc song phương: `I_low = Bilateral(I, sigma_s=5.0, sigma_r=0.12)`.")
    md.append("   - Trích xuất ảnh tần số cao chứa lỗ chân lông: `I_high = I - I_low + 0.5`.")
    md.append("4. **GPU Execution:** Làm mờ lớp `I_low` theo cường độ người dùng chọn; lớp `I_high` được điều chế bảo lưu `>=75%` vi cấu trúc.")
    md.append("5. **Visual Output:** Bề mặt da đồng đều, xóa bỏ vết thâm mụn nhưng vẫn nhìn thấy rõ các lỗ chân lông chân thực dưới ánh sáng mạnh.")
    md.append("")
    md.append("### 3.3 Luồng Nắn Chỉnh Vóc Dáng Không Biến Dạng Nền (FEAT_BODY_01)")
    md.append("1. **UI Event:** Người dùng chạm điểm eo và kéo vào trong 15 pixel với bán kính cọ $R = 80$ px.")
    md.append("2. **JNI Call:** Gọi `BodyEngineJNI.nativeDeformMesh(touchPoint, dragVector, radius, bodyMaskBitmap)`.")
    md.append("3. **C++ Mask Modulation:**")
    md.append("   - Kiểm tra mặt nạ phân đoạn cơ thể $M_{\\text{body}}$ tại từng đỉnh lưới.")
    md.append("   - Tính vector kéo hiệu dụng: $\\Delta \\vec{p}_{\\text{eff}} = \\Delta \\vec{p} \\cdot (1 - (r/R)^2)^3 \\cdot M_{\\text{body}}$.")
    md.append("4. **GPU Execution:** Đỉnh lưới trong cơ thể dịch chuyển; đỉnh lưới ngoài nền đứng yên tuyệt đối.")
    md.append("5. **Visual Output:** Vòng eo thon gọn, đường vân gạch men và cạnh cửa sau lưng thẳng tắp.")
    md.append("")
    md.append("---")
    md.append("*Tài liệu Ma Trận Ánh Xạ Chức Năng được chuẩn hóa phục vụ trực tiếp thiết kế Core Engine V4 trong tương lai.*")

    OUTPUT_FILE.write_text("\n".join(md), encoding="utf-8")
    print(f"[OK] Generated {OUTPUT_FILE} ({OUTPUT_FILE.stat().st_size:,} bytes)")

if __name__ == "__main__":
    generate()
